export {
  calculateExponentialRegression,
  calculateLinearRegression,
  calculateLogarithmicRegression,
  calculatePolynomialRegression,
  calculatePowerRegression,
  generateExponentialTrendline,
  generateLinearTrendline,
  generateLogarithmicTrendline,
  generateMovingAverageTrendline,
  generatePolynomialTrendline,
  generatePowerTrendline,
  generateTrendlinePoints,
  type ExponentialCoefficients,
  type LinearCoefficients,
  type LogarithmicCoefficients,
  type MovingAverageCoefficients,
  type PolynomialCoefficients,
  type PowerCoefficients,
  type TrendlineCoefficients,
  type TrendlineResult,
} from '../math/trendlines';
export { collectMarks } from './chart-engine';
export { chartDataToRows, configToSpec } from './config-to-spec';
export {
  DEFAULT_EXCEL_BAR_GAP_WIDTH,
  DEFAULT_EXCEL_CLUSTERED_BAR_OVERLAP,
  DEFAULT_EXCEL_STACKED_BAR_OVERLAP,
  barBaselinePixelForDomain,
  barBaselineValueForDomain,
  barGroupingForConfig,
  barGroupingForConfigSpec,
  barOrientationForChartType,
  chartImportSourceDialect,
  buildBarColumnRectangleModel,
  effectiveBarGeometry,
  effectiveBarGeometryFromSpec,
  effectiveGapWidth,
  effectiveOverlap,
  excelBarSlotGeometry,
  hasExcelBarGeometryConfig,
  hasExcelBarGeometrySpec,
  isBarLikeChartType,
  isImportedStandardOoxmlChart,
  isStackedBarGrouping,
  resolveBarGeometryGroups,
  stackModeForChartType,
  type BarGeometryGroup,
  type BarColumnRectangleModel,
  type BarColumnRectangleModelInput,
  type BarColumnRectangleModelOffset,
  type BarColumnRectangleModelPlotArea,
  type BarColumnRectangleModelRectangle,
  type BarColumnRectangleModelSeries,
  type BarSlotGeometry,
  type ResolveBarGeometryGroupsOptions,
} from './config-to-spec/bar-geometry';
export {
  buildExcelCartesianGeometryPlan,
  type ExcelCartesianGeometryPlan,
} from './config-to-spec/excel-cartesian-geometry';
export {
  buildPieDoughnutGeometry,
  maxEffectivePieDoughnutExplosionPercent,
  pieColorKey,
  pieDisplayLabel,
  pieDoughnutColorDomain,
  pieDoughnutLayoutHintsForConfig,
  pieDoughnutRowsFromGeometry,
  pieLegendKey,
  piePointKey,
  type PieDoughnutGeometry,
  type PieDoughnutGeometryFamily,
  type PieDoughnutGeometryInput,
  type PieDoughnutGeometryRing,
  type PieDoughnutGeometrySlice,
} from './config-to-spec/pie-doughnut-geometry';
export { pieLegendDisplayLabel } from './config-to-spec/legend';
export {
  clampPieDoughnutExplosionPercent,
  defaultPieLikeExplosionPercent,
  effectivePieLikeExplosionPercent,
  pieDoughnutArcFrame,
  pieDoughnutExplosionOffset,
  type PieDoughnutArcFrame,
  type PieDoughnutLayoutFamily,
  type PieDoughnutLayoutAuthority,
  type PieDoughnutLayoutHints,
  type PieDoughnutLayoutReservation,
  type PieDoughnutManualLayoutSource,
  type PieDoughnutLegendPosition,
  type PieDoughnutPlotArea,
  type PieDoughnutStyleContextReservationMode,
  type PieDoughnutStyleContextStatus,
  type PieDoughnutVisualStatus,
} from './config-to-spec/pie-like';
export { resolveSeriesColorAuthority } from './config-to-spec/color-authority';
export {
  resolveRadarVisualContract,
  type RadarPointMarkerVisualContract,
  type RadarSeriesVisualContract,
  type RadarVisualContract,
} from './config-to-spec/radar-visual-contract';
export {
  RADAR_LABEL_GAP,
  RADAR_DEFAULT_FILLED_OPACITY,
  RADAR_DEFAULT_SERIES_STROKE_WIDTH,
  RADAR_DEFAULT_MARKER_SIZE,
  RADAR_DEFAULT_GRID_COLOR,
  RADAR_DEFAULT_GRID_WIDTH,
  RADAR_DEFAULT_SPOKE_COLOR,
  RADAR_DEFAULT_SPOKE_WIDTH,
  RADAR_DEFAULT_CATEGORY_LABEL_COLOR,
  RADAR_DEFAULT_CATEGORY_LABEL_FONT_SIZE,
  RADAR_DEFAULT_VALUE_LABEL_COLOR,
  RADAR_DEFAULT_VALUE_LABEL_FONT_SIZE,
  RADAR_DEFAULT_FONT_FAMILY,
  RADAR_AUTO_VALUE_TICK_COUNT,
  RADAR_PLOT_INSET,
  RADAR_START_ANGLE,
  radarAutomaticMarkerShape,
  radarBlankPolicyFromDisplayBlanksAs,
  radarGeometryForPlotArea,
  radarPointAt,
  radarRadiusForValue,
  radarValueDomainFromValues,
  resolveRadarBlankPolicy,
  resolveRadarValueScale,
  type RadarGeometry,
  type RadarBlankPolicy,
  type RadarBlankPolicyAuthority,
  type RadarBlankPolicyResolution,
  type RadarPolarPoint,
  type ResolveRadarBlankPolicyInput,
  type ResolveRadarValueScaleInput,
  type RadarValueDomain,
  type RadarValueScale,
  type RadarValueScaleAuthority,
} from './radar-semantics';
export * from './style-resolver';
export {
  rustToTsChartType,
  tsToRustChartType,
  type RustBarDirection,
  type RustChartType,
  type RustChartTypeResult,
} from './chart-type-bridge';
export {
  ObjectCellAccessor,
  HIDDEN_CHART_CELL,
  detectSeriesOrientation,
  extractChartData,
  extractChartDataFromRange,
  isHiddenChartCellValue,
  parseRange,
  type CellDataAccessor,
  type CellRange,
  type ChartCellValue,
} from './data-extractor';
export {
  stockRolePlan,
  stockRolePlanWithEvidence,
  type StockRole,
  type StockRolePlan,
  type StockRolePlanWithEvidence,
} from './stock-role-plan';
export {
  chartDataSeriesIdentity,
  seriesConfigForDataSeries,
  seriesConfigSourceIndex,
  seriesConfigSourceKey,
  seriesOrderForDataSeries,
  seriesSourceIndex,
  seriesSourceKey,
  withSeriesConfigIdentity,
} from './series-identity';
export { renderedPointValueForRows } from './config-to-spec/data-point-values';
export {
  asStockConfig,
  expectedStockRolesForSubtype,
  hasStockRoleSeries,
  hasStockSubtype,
  isRenderableStockPoint,
  requiredStockPriceRolesForSubtype,
  shouldProjectStockSeries,
  shouldRenderStockChart,
  stockRenderedPointProjection,
  stockRenderedRoleValueProjectionFromRoleValues,
  stockRenderedPointProjectionFromRoleValues,
  stockSourceCompositionFromConfig,
  stockSourceRoleOrder,
  stockRoleOrder,
  stockSubTypeFromConfig,
  stockSubTypeFromRolePresence,
  stockValueAxisRoles,
  stockVolumeAxisPolicy,
  type StockRenderedRoleValueProjection,
  type StockRenderedPointProjection,
  type StockPointValue,
  type StockRoleValueArrays,
  type StockSourceRoleValueArrays,
} from './stock-semantics';
