use std::collections::HashMap;
use std::sync::LazyLock;

use value_types::Color;

use crate::types::TableStyleDef;

// =============================================================================
// Built-in Style Definitions (67 styles: 28 Light + 28 Medium + 11 Dark)
// =============================================================================

/// Helper to create a TableStyleDef from the raw color data.
///
/// Maps:
///   headerBackground  -> header_fill
///   headerText        -> header_font_color
///   totalBackground   -> totals_fill
///   totalText         -> totals_font_color
///   columnHighlight   -> first_column_fill / last_column_fill (with headerBackground fallback)
///   headerText        -> first_column_font_color / last_column_font_color
///   rowBackground1    -> odd_row_fill  (also odd_col_fill)
///   rowBackground2    -> even_row_fill (also even_col_fill)
///   dataText          -> data_font_color
///   borderColor       -> border_color
fn hex(s: &str) -> Color {
    Color::from_hex(s).unwrap()
}

#[allow(clippy::too_many_arguments)]
fn def(
    id: &str,
    name: &str,
    header_background: &str,
    header_text: &str,
    row_background1: &str,
    row_background2: &str,
    data_text: &str,
    total_background: &str,
    total_text: &str,
    border_color: &str,
    column_highlight: Option<&str>,
) -> (String, TableStyleDef) {
    let col_fill = column_highlight.unwrap_or(header_background);
    (
        id.to_string(),
        TableStyleDef {
            id: id.to_string(),
            name: name.to_string(),
            header_fill: Some(hex(header_background)),
            header_font_color: Some(hex(header_text)),
            totals_fill: Some(hex(total_background)),
            totals_font_color: Some(hex(total_text)),
            first_column_fill: Some(hex(col_fill)),
            first_column_font_color: Some(hex(header_text)),
            last_column_fill: Some(hex(col_fill)),
            last_column_font_color: Some(hex(header_text)),
            odd_row_fill: Some(hex(row_background1)),
            even_row_fill: Some(hex(row_background2)),
            odd_col_fill: Some(hex(row_background1)),
            even_col_fill: Some(hex(row_background2)),
            data_font_color: Some(hex(data_text)),
            border_color: Some(hex(border_color)),
        },
    )
}

/// All 67 built-in Excel table style definitions.
static BUILT_IN_STYLES: LazyLock<HashMap<String, TableStyleDef>> = LazyLock::new(|| {
    let entries = vec![
        // ─── Light 1–21 (from TS) ───
        def(
            "TableStyleLight1",
            "Light 1",
            "#000000",
            "#FFFFFF",
            "#FFFFFF",
            "#F2F2F2",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#000000",
            None,
        ),
        def(
            "TableStyleLight2",
            "Light 2",
            "#4472C4",
            "#FFFFFF",
            "#FFFFFF",
            "#D6DCE5",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleLight3",
            "Light 3",
            "#ED7D31",
            "#FFFFFF",
            "#FFFFFF",
            "#FCE4D6",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleLight4",
            "Light 4",
            "#A5A5A5",
            "#FFFFFF",
            "#FFFFFF",
            "#EDEDED",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleLight5",
            "Light 5",
            "#FFC000",
            "#000000",
            "#FFFFFF",
            "#FFF2CC",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleLight6",
            "Light 6",
            "#5B9BD5",
            "#FFFFFF",
            "#FFFFFF",
            "#DDEBF7",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleLight7",
            "Light 7",
            "#70AD47",
            "#FFFFFF",
            "#FFFFFF",
            "#E2EFDA",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleLight8",
            "Light 8",
            "#FFFFFF",
            "#4472C4",
            "#FFFFFF",
            "#D6DCE5",
            "#000000",
            "#FFFFFF",
            "#4472C4",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleLight9",
            "Light 9",
            "#FFFFFF",
            "#ED7D31",
            "#FFFFFF",
            "#FCE4D6",
            "#000000",
            "#FFFFFF",
            "#ED7D31",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleLight10",
            "Light 10",
            "#FFFFFF",
            "#A5A5A5",
            "#FFFFFF",
            "#EDEDED",
            "#000000",
            "#FFFFFF",
            "#A5A5A5",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleLight11",
            "Light 11",
            "#FFFFFF",
            "#FFC000",
            "#FFFFFF",
            "#FFF2CC",
            "#000000",
            "#FFFFFF",
            "#FFC000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleLight12",
            "Light 12",
            "#FFFFFF",
            "#5B9BD5",
            "#FFFFFF",
            "#DDEBF7",
            "#000000",
            "#FFFFFF",
            "#5B9BD5",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleLight13",
            "Light 13",
            "#FFFFFF",
            "#70AD47",
            "#FFFFFF",
            "#E2EFDA",
            "#000000",
            "#FFFFFF",
            "#70AD47",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleLight14",
            "Light 14",
            "#4472C4",
            "#FFFFFF",
            "#D6DCE5",
            "#B4C6E7",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#2F5496",
            None,
        ),
        def(
            "TableStyleLight15",
            "Light 15",
            "#ED7D31",
            "#FFFFFF",
            "#FCE4D6",
            "#F8CBAD",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#C65911",
            None,
        ),
        def(
            "TableStyleLight16",
            "Light 16",
            "#A5A5A5",
            "#FFFFFF",
            "#EDEDED",
            "#DBDBDB",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#7F7F7F",
            None,
        ),
        def(
            "TableStyleLight17",
            "Light 17",
            "#FFC000",
            "#000000",
            "#FFF2CC",
            "#FFE699",
            "#000000",
            "#FFC000",
            "#000000",
            "#BF8F00",
            None,
        ),
        def(
            "TableStyleLight18",
            "Light 18",
            "#5B9BD5",
            "#FFFFFF",
            "#DDEBF7",
            "#BDD7EE",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#2E75B6",
            None,
        ),
        def(
            "TableStyleLight19",
            "Light 19",
            "#70AD47",
            "#FFFFFF",
            "#E2EFDA",
            "#C6E0B4",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#538135",
            None,
        ),
        def(
            "TableStyleLight20",
            "Light 20",
            "#9E480E",
            "#FFFFFF",
            "#FFFFFF",
            "#F4B183",
            "#000000",
            "#9E480E",
            "#FFFFFF",
            "#9E480E",
            None,
        ),
        def(
            "TableStyleLight21",
            "Light 21",
            "#7030A0",
            "#FFFFFF",
            "#FFFFFF",
            "#E2D1F2",
            "#000000",
            "#7030A0",
            "#FFFFFF",
            "#7030A0",
            None,
        ),
        // ─── Light 22–28 (BUG FIX: missing from TS) ───
        def(
            "TableStyleLight22",
            "Light 22",
            "#4472C4",
            "#FFFFFF",
            "#FFFFFF",
            "#D6E4F0",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#8FAADC",
            None,
        ),
        def(
            "TableStyleLight23",
            "Light 23",
            "#ED7D31",
            "#FFFFFF",
            "#FFFFFF",
            "#F8CBAD",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#F4B183",
            None,
        ),
        def(
            "TableStyleLight24",
            "Light 24",
            "#A5A5A5",
            "#FFFFFF",
            "#FFFFFF",
            "#D9D9D9",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#C0C0C0",
            None,
        ),
        def(
            "TableStyleLight25",
            "Light 25",
            "#FFC000",
            "#FFFFFF",
            "#FFFFFF",
            "#FFE699",
            "#000000",
            "#FFC000",
            "#FFFFFF",
            "#FFD966",
            None,
        ),
        def(
            "TableStyleLight26",
            "Light 26",
            "#5B9BD5",
            "#FFFFFF",
            "#FFFFFF",
            "#BDD7EE",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#9DC3E6",
            None,
        ),
        def(
            "TableStyleLight27",
            "Light 27",
            "#70AD47",
            "#FFFFFF",
            "#FFFFFF",
            "#C6EFCE",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#A9D18E",
            None,
        ),
        def(
            "TableStyleLight28",
            "Light 28",
            "#264478",
            "#FFFFFF",
            "#FFFFFF",
            "#B4C6E7",
            "#000000",
            "#264478",
            "#FFFFFF",
            "#8DB4E2",
            None,
        ),
        // ─── Medium 1–28 ───
        def(
            "TableStyleMedium1",
            "Medium 1",
            "#FFFFFF",
            "#000000",
            "#FFFFFF",
            "#F2F2F2",
            "#000000",
            "#FFFFFF",
            "#000000",
            "#9B9B9B",
            None,
        ),
        def(
            "TableStyleMedium2",
            "Medium 2",
            "#4472C4",
            "#FFFFFF",
            "#FFFFFF",
            "#D6DCE5",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#8FAADC",
            None,
        ),
        def(
            "TableStyleMedium3",
            "Medium 3",
            "#ED7D31",
            "#FFFFFF",
            "#FFFFFF",
            "#FCE4D6",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#F4B183",
            None,
        ),
        def(
            "TableStyleMedium4",
            "Medium 4",
            "#A5A5A5",
            "#FFFFFF",
            "#FFFFFF",
            "#EDEDED",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#C9C9C9",
            None,
        ),
        def(
            "TableStyleMedium5",
            "Medium 5",
            "#FFC000",
            "#000000",
            "#FFFFFF",
            "#FFF2CC",
            "#000000",
            "#FFC000",
            "#000000",
            "#FFD966",
            None,
        ),
        def(
            "TableStyleMedium6",
            "Medium 6",
            "#5B9BD5",
            "#FFFFFF",
            "#FFFFFF",
            "#DDEBF7",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#9DC3E6",
            None,
        ),
        def(
            "TableStyleMedium7",
            "Medium 7",
            "#70AD47",
            "#FFFFFF",
            "#FFFFFF",
            "#E2EFDA",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#A9D18E",
            None,
        ),
        def(
            "TableStyleMedium8",
            "Medium 8",
            "#4472C4",
            "#FFFFFF",
            "#D6DCE5",
            "#B4C6E7",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleMedium9",
            "Medium 9",
            "#ED7D31",
            "#FFFFFF",
            "#FCE4D6",
            "#F8CBAD",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleMedium10",
            "Medium 10",
            "#A5A5A5",
            "#FFFFFF",
            "#EDEDED",
            "#DBDBDB",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleMedium11",
            "Medium 11",
            "#FFC000",
            "#000000",
            "#FFF2CC",
            "#FFE699",
            "#000000",
            "#FFC000",
            "#000000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleMedium12",
            "Medium 12",
            "#5B9BD5",
            "#FFFFFF",
            "#DDEBF7",
            "#BDD7EE",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleMedium13",
            "Medium 13",
            "#70AD47",
            "#FFFFFF",
            "#E2EFDA",
            "#C6E0B4",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleMedium14",
            "Medium 14",
            "#FFFFFF",
            "#4472C4",
            "#FFFFFF",
            "#D6DCE5",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleMedium15",
            "Medium 15",
            "#FFFFFF",
            "#ED7D31",
            "#FFFFFF",
            "#FCE4D6",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleMedium16",
            "Medium 16",
            "#FFFFFF",
            "#A5A5A5",
            "#FFFFFF",
            "#EDEDED",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleMedium17",
            "Medium 17",
            "#FFFFFF",
            "#BF8F00",
            "#FFFFFF",
            "#FFF2CC",
            "#000000",
            "#FFC000",
            "#000000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleMedium18",
            "Medium 18",
            "#FFFFFF",
            "#5B9BD5",
            "#FFFFFF",
            "#DDEBF7",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleMedium19",
            "Medium 19",
            "#FFFFFF",
            "#70AD47",
            "#FFFFFF",
            "#E2EFDA",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleMedium20",
            "Medium 20",
            "#FFFFFF",
            "#000000",
            "#FFFFFF",
            "#D9D9D9",
            "#000000",
            "#000000",
            "#FFFFFF",
            "#000000",
            None,
        ),
        def(
            "TableStyleMedium21",
            "Medium 21",
            "#4472C4",
            "#FFFFFF",
            "#FFFFFF",
            "#B4C6E7",
            "#000000",
            "#4472C4",
            "#FFFFFF",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleMedium22",
            "Medium 22",
            "#ED7D31",
            "#FFFFFF",
            "#FFFFFF",
            "#F8CBAD",
            "#000000",
            "#ED7D31",
            "#FFFFFF",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleMedium23",
            "Medium 23",
            "#A5A5A5",
            "#FFFFFF",
            "#FFFFFF",
            "#DBDBDB",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleMedium24",
            "Medium 24",
            "#FFC000",
            "#000000",
            "#FFFFFF",
            "#FFE699",
            "#000000",
            "#FFC000",
            "#000000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleMedium25",
            "Medium 25",
            "#5B9BD5",
            "#FFFFFF",
            "#FFFFFF",
            "#BDD7EE",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleMedium26",
            "Medium 26",
            "#70AD47",
            "#FFFFFF",
            "#FFFFFF",
            "#C6E0B4",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleMedium27",
            "Medium 27",
            "#9E480E",
            "#FFFFFF",
            "#FFFFFF",
            "#F4B183",
            "#000000",
            "#9E480E",
            "#FFFFFF",
            "#9E480E",
            None,
        ),
        def(
            "TableStyleMedium28",
            "Medium 28",
            "#7030A0",
            "#FFFFFF",
            "#FFFFFF",
            "#CDA3DE",
            "#000000",
            "#7030A0",
            "#FFFFFF",
            "#7030A0",
            None,
        ),
        // ─── Dark 1–11 ───
        def(
            "TableStyleDark1",
            "Dark 1",
            "#000000",
            "#FFFFFF",
            "#737373",
            "#595959",
            "#FFFFFF",
            "#000000",
            "#FFFFFF",
            "#000000",
            None,
        ),
        def(
            "TableStyleDark2",
            "Dark 2",
            "#4472C4",
            "#FFFFFF",
            "#8FAADC",
            "#6F92D2",
            "#FFFFFF",
            "#4472C4",
            "#FFFFFF",
            "#4472C4",
            None,
        ),
        def(
            "TableStyleDark3",
            "Dark 3",
            "#ED7D31",
            "#FFFFFF",
            "#F4B183",
            "#E9956A",
            "#FFFFFF",
            "#ED7D31",
            "#FFFFFF",
            "#ED7D31",
            None,
        ),
        def(
            "TableStyleDark4",
            "Dark 4",
            "#A5A5A5",
            "#FFFFFF",
            "#C9C9C9",
            "#B7B7B7",
            "#000000",
            "#A5A5A5",
            "#FFFFFF",
            "#A5A5A5",
            None,
        ),
        def(
            "TableStyleDark5",
            "Dark 5",
            "#FFC000",
            "#000000",
            "#FFD966",
            "#FFC93D",
            "#000000",
            "#FFC000",
            "#000000",
            "#FFC000",
            None,
        ),
        def(
            "TableStyleDark6",
            "Dark 6",
            "#5B9BD5",
            "#FFFFFF",
            "#9DC3E6",
            "#7DAFE0",
            "#000000",
            "#5B9BD5",
            "#FFFFFF",
            "#5B9BD5",
            None,
        ),
        def(
            "TableStyleDark7",
            "Dark 7",
            "#70AD47",
            "#FFFFFF",
            "#A9D18E",
            "#8CC265",
            "#000000",
            "#70AD47",
            "#FFFFFF",
            "#70AD47",
            None,
        ),
        def(
            "TableStyleDark8",
            "Dark 8",
            "#4472C4",
            "#FFFFFF",
            "#4472C4",
            "#2F5496",
            "#FFFFFF",
            "#2F5496",
            "#FFFFFF",
            "#2F5496",
            None,
        ),
        def(
            "TableStyleDark9",
            "Dark 9",
            "#ED7D31",
            "#FFFFFF",
            "#ED7D31",
            "#C65911",
            "#FFFFFF",
            "#C65911",
            "#FFFFFF",
            "#C65911",
            None,
        ),
        def(
            "TableStyleDark10",
            "Dark 10",
            "#A5A5A5",
            "#FFFFFF",
            "#A5A5A5",
            "#7F7F7F",
            "#FFFFFF",
            "#7F7F7F",
            "#FFFFFF",
            "#7F7F7F",
            None,
        ),
        def(
            "TableStyleDark11",
            "Dark 11",
            "#5B9BD5",
            "#FFFFFF",
            "#5B9BD5",
            "#2E75B6",
            "#FFFFFF",
            "#2E75B6",
            "#FFFFFF",
            "#2E75B6",
            None,
        ),
    ];

    let mut map = HashMap::with_capacity(entries.len());
    for (id, style_def) in entries {
        map.insert(id, style_def);
    }
    map
});

pub(super) fn get(id: &str) -> Option<&'static TableStyleDef> {
    if let Some(style) = BUILT_IN_STYLES.get(id) {
        return Some(style);
    }

    let canonical = canonical_builtin_id(id)?;
    BUILT_IN_STYLES.get(canonical.as_str())
}

pub(super) fn all() -> Vec<&'static TableStyleDef> {
    BUILT_IN_STYLES.values().collect()
}

fn canonical_builtin_id(id: &str) -> Option<String> {
    let trimmed = id.trim();
    for (prefix, family, max) in [
        ("light", "Light", 28_u8),
        ("medium", "Medium", 28_u8),
        ("dark", "Dark", 11_u8),
    ] {
        if let Some(index) = parse_style_index(trimmed, prefix, max) {
            return Some(format!("TableStyle{family}{index}"));
        }

        let full_prefix = format!("TableStyle{family}");
        if let Some(index) = parse_style_index(trimmed, &full_prefix, max) {
            return Some(format!("TableStyle{family}{index}"));
        }
    }

    None
}

fn parse_style_index(id: &str, prefix: &str, max: u8) -> Option<u8> {
    if id.len() <= prefix.len() || !id.get(..prefix.len())?.eq_ignore_ascii_case(prefix) {
        return None;
    }

    let suffix = &id[prefix.len()..];
    if suffix.is_empty() || !suffix.chars().all(|ch| ch.is_ascii_digit()) {
        return None;
    }

    let index = suffix.parse::<u8>().ok()?;
    (1..=max).contains(&index).then_some(index)
}
