from typing import Optional

class MogError(Exception): ...
class ComputeError(MogError): ...
class NativeApiError(ComputeError): ...
class AddressError(MogError): ...
class SheetNotFoundError(MogError): ...
class EngineShutdownError(MogError): ...
class UnsupportedApiError(MogError):
    api_path: str
    python_path: str
    reason_code: str
    owner_package: str
    replacement: Optional[str]
    docs_key: Optional[str]
    def to_dict(self) -> dict[str, Optional[str]]: ...
