from typing import Any, Optional

class Workbook:
    active_sheet: Any
    def address_to_index(self, address: Any) -> Any: ...
    def batch(self, label: Any, fn: Any) -> Any: ...
    def calculate(self, options: Any = ...) -> Any: ...
    def describe_ranges(self, requests: Any, includeStyle: Any = ...) -> list[Any]: ...
    def dispose(self) -> None: ...
    def get_or_create_sheet(self, name: Any) -> Any: ...
    def get_settings(self) -> Any: ...
    def get_sheet(self, name: Any) -> Any: ...
    def get_sheet_by_id(self, sheetId: Any) -> Any: ...
    def get_sheet_by_index(self, index: Any) -> Any: ...
    def get_sheet_count(self) -> float: ...
    def get_sheet_names(self) -> list[Any]: ...
    def get_workbook_snapshot(self) -> Any: ...
    def index_to_address(self, row: Any, col: Any) -> str: ...
    def make_principal(self, tags: Any) -> Any: ...
    def on(self, event: Any, handler: Any) -> Any: ...
    def security_active(self) -> bool: ...
    def set_active_principal(self, principal: Any) -> None: ...
    def set_settings(self, updates: Any) -> None: ...
    sheet_count: Any
    sheet_names: Any
    def to_buffer(self, options: Any = ...) -> Any: ...
    @property
    def history(self) -> Any: ...
    @property
    def names(self) -> Any: ...
    @property
    def notifications(self) -> Any: ...
    @property
    def protection(self) -> Any: ...
    @property
    def security(self) -> Any: ...
    @property
    def sheets(self) -> Any: ...
    @property
    def slicers(self) -> Any: ...
    @property
    def theme(self) -> Any: ...
    @property
    def viewport(self) -> Any: ...
