from typing import Any, Optional

class Worksheet:
    def clear(self, range: Any, applyTo: Any = ...) -> Any: ...
    def clear_data(self, range: Any) -> Any: ...
    def describe(self, address: Any = ...) -> str: ...
    def describe_range(self, range: Any = ..., includeStyle: Any = ...) -> str: ...
    def find_by_formula(self, pattern: Any, range: Any = ...) -> list[Any]: ...
    def find_by_value(self, value: Any, range: Any = ...) -> list[Any]: ...
    def find_data_edge(self, row: Any, col: Any, direction: Any) -> Any: ...
    def get_cell(self, address: Any) -> Any: ...
    def get_current_region(self, row: Any, col: Any) -> Any: ...
    def get_data(self) -> list[Any]: ...
    def get_dependents(self, address: Any) -> list[Any]: ...
    def get_display_value(self, address: Any) -> str: ...
    def get_formula(self, address: Any) -> Any: ...
    def get_formulas(self, range: Any) -> list[Any]: ...
    def get_index(self) -> float: ...
    def get_name(self) -> str: ...
    def get_precedents(self, address: Any) -> list[Any]: ...
    def get_range(self, range: Any) -> list[Any]: ...
    def get_range_with_identity(self, range: Any) -> list[Any]: ...
    def get_raw_cell_data(self, address: Any, includeFormula: Any = ...) -> Any: ...
    def get_raw_range_data(self, range: Any, options: Any = ...) -> list[Any]: ...
    def get_used_range(self) -> Any: ...
    def get_value(self, address: Any) -> Any: ...
    def get_visibility(self) -> Any: ...
    name: Any
    def regex_search(self, patterns: Any, options: Any = ...) -> list[Any]: ...
    def set_cell(self, address: Any, value: Any, options: Any = ...) -> None: ...
    def set_cells(self, cells: Any) -> Any: ...
    def set_name(self, name: Any) -> None: ...
    def set_range(self, range: Any, values: Any) -> None: ...
    def set_visibility(self, state: Any) -> None: ...
    sheet_id: Any
    def sort_range(self, range: Any, options: Any) -> None: ...
    def summarize(self, options: Any = ...) -> str: ...
    def to_csv(self, options: Any = ...) -> str: ...
    def to_json(self, options: Any = ...) -> list[Any]: ...
    @property
    def changes(self) -> Any: ...
    @property
    def charts(self) -> Any: ...
    @property
    def comments(self) -> Any: ...
    @property
    def conditional_formats(self) -> Any: ...
    @property
    def filters(self) -> Any: ...
    @property
    def form_controls(self) -> Any: ...
    @property
    def formats(self) -> Any: ...
    @property
    def hyperlinks(self) -> Any: ...
    @property
    def layout(self) -> Any: ...
    @property
    def names(self) -> Any: ...
    @property
    def objects(self) -> Any: ...
    @property
    def outline(self) -> Any: ...
    @property
    def pictures(self) -> Any: ...
    @property
    def pivots(self) -> Any: ...
    @property
    def print_(self) -> Any: ...
    @property
    def protection(self) -> Any: ...
    @property
    def settings(self) -> Any: ...
    @property
    def shapes(self) -> Any: ...
    @property
    def slicers(self) -> Any: ...
    @property
    def sparklines(self) -> Any: ...
    @property
    def structure(self) -> Any: ...
    @property
    def tables(self) -> Any: ...
    @property
    def text_boxes(self) -> Any: ...
    @property
    def validation(self) -> Any: ...
    @property
    def view(self) -> Any: ...
