/**
 * Workbook Sub-API Interfaces — Barrel Export
 *
 * All workbook namespace interfaces for the unified spreadsheet API.
 */

export type { WorkbookHistory } from './history';
export type {
  CheckoutVersionResult,
  GetVersionHeadInput,
  JsonValue,
  ListVersionCommitsInput,
  ListVersionRefsInput,
  ObjectDigest,
  PageCursor,
  Paged,
  RedactionPolicy,
  RedactionSummary,
  RedactedVersionAuthor,
  VerificationSummary,
  VersionAnnotationText,
  VersionApplyMergeInput,
  VersionApplyMergeAttemptMetadata,
  VersionApplyMergeMutationGuarantee,
  VersionApplyMergeOptions,
  VersionApplyMergeResolution,
  VersionApplyMergeResult,
  VersionBranchName,
  VersionBranchRefReadResult,
  VersionBranchSelector,
  VersionCapability,
  VersionCapabilityDependency,
  VersionCapabilityError,
  VersionCapabilityState,
  VersionCheckoutDependencyRole,
  VersionCheckoutDependencySummary,
  VersionCheckoutMutationGuarantee,
  VersionCheckoutOptions,
  VersionCheckoutPlan,
  VersionCheckoutResolvedTarget,
  VersionCheckoutResult,
  VersionCheckoutTarget,
  VersionCommitish,
  VersionCommitExpectedHead,
  VersionCommitMode,
  VersionCommitOptions,
  VersionCommitPage,
  VersionCreateBranchOptions,
  VersionDegradedHeadResult,
  VersionDeleteRefOptions,
  VersionDiffDisplay,
  VersionDiffDisplayValue,
  VersionDiffEntry,
  VersionDiffInput,
  VersionDiffOptions,
  VersionDiffStructuralMetadata,
  VersionDiffValue,
  VersionDiagnostic,
  VersionDiagnosticCode,
  VersionDiagnosticMessageId,
  VersionDiagnosticPublicPayload,
  VersionDiagnosticSeverity,
  VersionError,
  VersionFastForwardBranchOptions,
  VersionGetMergeConflictDetailRequest,
  VersionGetHeadOptions,
  VersionHead,
  VersionListCommitsOptions,
  VersionListRefsOptions,
  VersionMainRefName,
  VersionMergeAttemptKind,
  VersionMergeAttemptMetadata,
  VersionMergeAttemptPersistence,
  VersionMergeChange,
  VersionMergeConflict,
  VersionMergeConflictDetailBase,
  VersionMergeConflictDetailPurpose,
  VersionMergeConflictDetailResolutionOption,
  VersionMergeConflictDetailResult,
  VersionMergeConflictResolutionOption,
  VersionMergeConflictResolutionOptionKind,
  VersionMergeConflictValuePageRef,
  VersionMergeConflictValueRole,
  VersionMergeEndpointDeniedStatus,
  VersionMergeInput,
  VersionMergeMutationGuarantee,
  VersionMergeOptions,
  VersionMergeResolutionPayloadPurpose,
  VersionMergeResult,
  VersionMergeResultId,
  VersionPage,
  VersionPageOrder,
  VersionPageToken,
  VersionRecordRevision,
  VersionRedactedValue,
  VersionRef,
  VersionRefListResult,
  VersionRefMutationResult,
  VersionRefName,
  VersionRefNamespace,
  VersionRefReadResult,
  VersionRefSelector,
  VersionRedactionClass,
  VersionResult,
  VersionPutMergeResolutionPayloadRequest,
  VersionPutMergeResolutionPayloadResult,
  VersionSaveMergeResolutionsRequest,
  VersionSaveMergeResolutionsResult,
  VersionSemanticDiffPage,
  VersionSemanticValue,
  VersionSealedResolutionPayloadRef,
  VersionSealedResolutionPayloadStorageMode,
  VersionStoreDiagnostic,
  VersionSurfaceDiagnosticCode,
  VersionSurfaceDiagnosticSeverity,
  VersionSurfaceStage,
  VersionSurfaceStatus,
  VersionSurfaceStorageBackend,
  VersionSymbolicRef,
  VersionSymbolicRefReadResult,
  VersionUpdateBranchOptions,
  WorkbookDiffPage,
  WorkbookCommitAnnotationSummary,
  WorkbookCommitId,
  WorkbookCommitRef,
  WorkbookCommitSummary,
  WorkbookVersion,
  WorkbookVersionCapabilityStage,
  WorkbookVersionCapabilityStatus,
  WorkbookVersionDependency,
  WorkbookVersionDiagnostic,
  WorkbookVersionDiagnosticCode,
  WorkbookVersionDiagnosticSeverity,
  WorkbookVersionHead,
  WorkbookVersionHeadStatus,
  WorkbookVersionRolloutStage,
  WorkbookVersionStatus,
} from './version';
export type {
  FormulaReferenceDiagnostic,
  FormulaReferenceDiagnosticsOptions,
  FormulaReferenceDiagnosticsPage,
  FormulaReferenceEdgeDiagnostic,
  FormulaReferenceEdgeDiagnosticRow,
  ImportDiagnosticDetails,
  ImportDiagnosticDto,
  ImportDiagnosticLocation,
  ImportDiagnosticPhase,
  ImportDiagnosticRecoverability,
  ImportDiagnosticSeverity,
  ImportFilterUnsupportedReason,
  FormulaReferenceLocation,
  FormulaReferenceParseDiagnosticRow,
  MaterializationPhase,
  MaterializationState,
  ResolvedChartSpecDiagnosticsOptions,
  RuntimeDiagnosticsOptions,
  RuntimeDiagnosticsPage,
  RuntimeOperationDiagnostic,
  CheckErrorsOptions,
  ValidateWorkbookOptions,
  WorkbookBlankRegionCheckInput,
  WorkbookDiagnostics,
  WorkbookExternalReferenceCheckOptions,
  WorkbookFormulaShapeCheckInput,
  WorkbookFormulaShapeRangeRequest,
  WorkbookValidationCheckKind,
  WorkbookValidationCheckResult,
  WorkbookValidationCheckStatus,
  WorkbookValidationFinding,
  WorkbookValidationRangeRequest,
  WorkbookValidationResult,
  WorkbookValidationScanOptions,
  WorkbookValidationSeverity,
} from './diagnostics';
export type { WorkbookNames } from './names';
export type { NotificationId, WorkbookNotifications } from './notifications';
export type { WorkbookProtection } from './protection';
export type { WorkbookSecurity } from './security';
export type { WorkbookScenarios } from './scenarios';
export type { WorkbookSheets } from './sheets';
export type { WorkbookSlicerStyles, SlicerStyleInfo, NamedSlicerStyle } from './slicer-styles';
export type { WorkbookSlicers } from './slicers';
export type {
  WorkbookTimelineStyles,
  TimelineStyleInfo,
  NamedTimelineStyle,
} from './timeline-styles';
export type { WorkbookPivotTableStyles, PivotTableStyleInfo } from './pivot-styles';
export type { WorkbookFunctions } from './functions';
export type { WorkbookTableStyles, TableStyleInfoWithReadOnly } from './table-styles';
export type {
  CellStyleCatalog,
  CellStyleCategoryInfo,
  CellStyleListOptions,
  CellStyleSource,
  WorkbookCellStyles,
} from './cell-styles';
export type { WorkbookTheme } from './theme';
export type { ViewportChangeEvent, ViewportRegion, WorkbookViewport } from './viewport';
export type { ViewportBounds as WorkbookViewportBounds } from './viewport';
export type { WorkbookStateProvider } from './state-provider';
export type { WorkbookProperties, DocumentProperties } from './properties';
export type {
  WorkbookChanges,
  WorkbookChangeTracker,
  WorkbookChangeRecord,
  WorkbookCollectResult,
  WorkbookTrackOptions,
} from './changes';
