/**
 * Workbook Sub-API Interfaces — Barrel Export
 *
 * All workbook namespace interfaces for the unified spreadsheet API.
 */

export type { WorkbookHistory } from './history';
export type * from './xlsx-export';
export type * from './version-diff';
export type * from './version-diff-metadata';
export type * from './version-working-tree-diff';
export type {
  AcceptAgentProposalInput,
  AgentProposal,
  AgentProposalAcceptResolutionPolicy,
  AgentProposalAcceptResult,
  AgentProposalId,
  AgentProposalStatus,
  AgentProposalSummary,
  AgentProposalWorkspaceHandle,
  AgentProposalWorkspaceSession,
  CheckoutVersionResult,
  CommitProposalWorkspaceInput,
  CreateAgentProposalInput,
  DisposeProposalWorkspaceInput,
  FailAgentProposalInput,
  GetVersionHeadInput,
  GetAgentProposalInput,
  GetProposalWorkspaceInput,
  JsonValue,
  ListVersionCommitsInput,
  ListVersionRefsInput,
  ListAgentProposalsInput,
  MarkAgentProposalVerifiedInput,
  ObjectDigest,
  OpenProposalReviewInput,
  PageCursor,
  Paged,
  RedactionPolicy,
  RedactionSummary,
  RedactedVersionAuthor,
  VerificationSummary,
  VersionAnnotationText,
  VersionApplyMergeInput,
  VersionApplyMergeAttemptMetadata,
  VersionApplyMergeMutationGuarantee,
  VersionApplyMergeOptions,
  VersionApplyMergeResolution,
  VersionApplyMergeResult,
  VersionAppendReviewDecisionInput,
  VersionAuthor,
  VersionBranchName,
  VersionBranchNameInput,
  VersionBranchRefReadResult,
  VersionBranchSelector,
  VersionCapability,
  VersionCapabilityDependency,
  VersionCapabilityError,
  VersionCapabilityState,
  VersionCheckoutDependencyRole,
  VersionCheckoutDependencySummary,
  VersionCheckoutMutationGuarantee,
  VersionCheckoutOptions,
  VersionCheckoutPlan,
  VersionCheckoutResolvedTarget,
  VersionCheckoutResult,
  VersionCheckoutTarget,
  VersionCommitish,
  VersionCommitExpectedHead,
  VersionCommitMode,
  VersionCommitOptions,
  VersionCommitPage,
  VersionCreateBranchOptions,
  VersionCreateReviewInput,
  VersionCounterRecordRevision,
  VersionDegradedHeadResult,
  VersionDeleteRefOptions,
  VersionDiffDisplay,
  VersionDiffDisplayValue,
  VersionDiffCursor,
  VersionDiffEntry,
  VersionDiffInput,
  VersionDiffOptions,
  VersionDiffResourceLimit,
  VersionDiffResourceLimitKind,
  VersionDiffResourceLimitSummary,
  VersionDiffResourceLimitUnit,
  VersionDiffStructuralMetadata,
  VersionDiffValue,
  VersionDiagnostic,
  VersionDiagnosticCode,
  VersionDiagnosticMessageId,
  VersionDiagnosticPublicPayload,
  VersionDiagnosticSeverity,
  VersionError,
  VersionFastForwardBranchOptions,
  VersionGetMergeConflictDetailRequest,
  VersionGetMergeReviewInput,
  VersionGetHeadOptions,
  VersionGetReviewDiffInput,
  VersionGetReviewInput,
  VersionHead,
  VersionListCommitsOptions,
  VersionListRefsOptions,
  VersionListReviewsInput,
  VersionLiveCollaborationState,
  VersionMainRefName,
  VersionMergeAttemptKind,
  VersionMergeAttemptMetadata,
  VersionMergeAttemptPersistence,
  VersionMergeChange,
  VersionMergeConflict,
  VersionMergeConflictDetailBase,
  VersionMergeConflictDetailPurpose,
  VersionMergeConflictDetailResolutionOption,
  VersionMergeConflictDetailResult,
  VersionMergeConflictResolutionOption,
  VersionMergeConflictResolutionOptionKind,
  VersionMergeConflictValuePageRef,
  VersionMergeConflictValueRole,
  VersionMergeReviewArtifactApi,
  VersionMergeReviewArtifactNamespace,
  VersionMergeEndpoint,
  VersionMergeEndpointDeniedStatus,
  VersionMergeInput,
  VersionMergeMutationGuarantee,
  VersionMergeOptions,
  VersionMergeResolutionPayloadPurpose,
  VersionMergeReview,
  VersionMergeReviewApplyOptions,
  VersionMergeReviewConflictDetailOptions,
  VersionMergeReviewStatus,
  VersionMergeResult,
  VersionMergeResultId,
  VersionPreviewMergeInput,
  VersionPreviewMergeOptions,
  VersionPage,
  VersionPageOrder,
  VersionPageToken,
  VersionPendingRemoteSegmentId,
  VersionPromotePendingRemoteDiagnostic,
  VersionPromotePendingRemoteDiagnosticCode,
  VersionPromotePendingRemoteOptions,
  VersionPromotePendingRemoteResult,
  VersionPromotePendingRemoteSkippedSegment,
  VersionPromotePendingRemoteSkipReason,
  VersionPromotePendingRemoteStatus,
  VersionCreateProposalPorcelainInput,
  VersionListProposalPorcelainOptions,
  VersionProposalApi,
  VersionProposalAcceptOptions,
  VersionProposalHandle,
  VersionProposalHandleOptions,
  VersionProposalPorcelainApi,
  VersionProposalRejectOptions,
  VersionProposalSupersedeOptions,
  VersionProposalVerificationOptions,
  VersionProposalWorkspaceCommitOptions,
  VersionProposalWorkspaceHandle,
  VersionRecordRevision,
  VersionRedactedValue,
  WorkbookVersionReviewApi,
  WorkbookVersionReviewNamespace,
  WorkbookVersionReviewApprovalEvidence,
  WorkbookVersionReviewApprovalTarget,
  WorkbookVersionReviewDecision,
  WorkbookVersionReviewDecisionDraft,
  WorkbookVersionReviewDecisionKind,
  WorkbookVersionReviewDecisionTarget,
  WorkbookVersionReviewDiffChange,
  WorkbookVersionReviewDiffChangeKind,
  WorkbookVersionReviewDiffEntity,
  WorkbookVersionReviewDiffPage,
  WorkbookVersionReviewRecord,
  WorkbookVersionReviewRecordSummary,
  WorkbookVersionReviewStatus,
  WorkbookVersionReviewSubject,
  VersionRef,
  VersionRefListResult,
  VersionRefMutationResult,
  VersionRefName,
  VersionRefNameInput,
  VersionRefReadResult,
  VersionRefSelector,
  VersionResolvedMergeEndpoint,
  VersionRedactionClass,
  VersionResult,
  VersionPutMergeResolutionPayloadRequest,
  VersionPutMergeResolutionPayloadResult,
  VersionSaveMergeResolutionsRequest,
  VersionSaveMergeResolutionsResult,
  VersionSemanticDiffPage,
  VersionSemanticValue,
  VersionSealedResolutionPayloadRef,
  VersionSealedResolutionPayloadStorageMode,
  VersionStoreDiagnostic,
  VersionSurfaceDiagnosticCode,
  VersionSurfaceDiagnosticSeverity,
  VersionSurfaceLiveCollaborationStatus,
  VersionSurfaceStage,
  VersionSurfaceStatus,
  VersionSurfaceStorageBackend,
  VersionSymbolicRef,
  VersionSymbolicRefReadResult,
  VersionUpdateBranchOptions,
  VersionUpdateReviewStatusInput,
  VersionWorkingTreeDiffId,
  VersionWorkingTreeDiffOptions,
  VersionWorkingTreeDiffPage,
  RejectAgentProposalInput,
  StartProposalWorkspaceInput,
  SupersedeAgentProposalInput,
  WorkbookDiffPage,
  WorkbookCommitAnnotationSummary,
  WorkbookCommitId,
  WorkbookCommitIdInput,
  WorkbookCommitRef,
  WorkbookCommitSummary,
  WorkbookVersion,
  WorkbookVersionRefsNamespace,
  WorkbookVersionCapabilityStage,
  WorkbookVersionCapabilityStatus,
  WorkbookVersionDependency,
  WorkbookVersionDiagnostic,
  WorkbookVersionDiagnosticCode,
  WorkbookVersionDiagnosticSeverity,
  WorkbookVersionHead,
  WorkbookVersionHeadStatus,
  WorkbookVersionRolloutStage,
  WorkbookVersionStatus,
} from './version';
export type * from './version-porcelain';
export type * from './version-revert';
export type {
  FormulaReferenceDiagnostic,
  FormulaReferenceDiagnosticsOptions,
  FormulaReferenceDiagnosticsPage,
  FormulaReferenceEdgeDiagnostic,
  FormulaReferenceEdgeDiagnosticRow,
  ImportDiagnosticDetails,
  ImportDiagnosticDto,
  ImportDiagnosticLocation,
  ImportDiagnosticPhase,
  ImportDiagnosticRecoverability,
  ImportDiagnosticSeverity,
  ImportFilterUnsupportedReason,
  FormulaReferenceLocation,
  FormulaReferenceParseDiagnosticRow,
  MaterializationPhase,
  MaterializationState,
  ResolvedChartSpecDiagnosticsOptions,
  RuntimeDiagnosticsOptions,
  RuntimeDiagnosticsPage,
  RuntimeOperationDiagnostic,
  CheckErrorsOptions,
  ValidateWorkbookOptions,
  WorkbookBlankRegionCheckInput,
  WorkbookDiagnostics,
  WorkbookExternalReferenceCheckOptions,
  WorkbookFormulaShapeCheckInput,
  WorkbookFormulaShapeRangeRequest,
  WorkbookValidationCheckKind,
  WorkbookValidationCheckResult,
  WorkbookValidationCheckStatus,
  WorkbookValidationFinding,
  WorkbookValidationRangeRequest,
  WorkbookValidationResult,
  WorkbookValidationScanOptions,
  WorkbookValidationSeverity,
} from './diagnostics';
export type { WorkbookNames } from './names';
export type { NotificationId, WorkbookNotifications } from './notifications';
export type { WorkbookProtection } from './protection';
export type { WorkbookSecurity } from './security';
export type { WorkbookScenarios } from './scenarios';
export type { WorkbookSheets } from './sheets';
export type { WorkbookSlicerStyles, SlicerStyleInfo, NamedSlicerStyle } from './slicer-styles';
export type { WorkbookSlicers } from './slicers';
export type {
  WorkbookTimelineStyles,
  TimelineStyleInfo,
  NamedTimelineStyle,
} from './timeline-styles';
export type { WorkbookPivotTableStyles, PivotTableStyleInfo } from './pivot-styles';
export type { WorkbookFunctions } from './functions';
export type { WorkbookTableStyles, TableStyleInfoWithReadOnly } from './table-styles';
export type {
  CellStyleCatalog,
  CellStyleCategoryInfo,
  CellStyleListOptions,
  CellStyleSource,
  WorkbookCellStyles,
} from './cell-styles';
export type { WorkbookTheme } from './theme';
export type { ViewportChangeEvent, ViewportRegion, WorkbookViewport } from './viewport';
export type { ViewportBounds as WorkbookViewportBounds } from './viewport';
export type { WorkbookStateProvider } from './state-provider';
export type { WorkbookProperties, DocumentProperties } from './properties';
export type {
  WorkbookChanges,
  WorkbookChangeTracker,
  WorkbookChangeRecord,
  WorkbookCollectResult,
  WorkbookTrackOptions,
} from './changes';
