/**
 * WorkbookSecurity -- Data access control sub-API interface.
 *
 * Provides methods to manage data access policies (Layer 2) for the workbook.
 * Policies control what access level a principal (matched by tag) has to
 * specific targets (workbook, sheet, or column).
 *
 * Methods forward through the ComputeService `wb_security_*` bridge methods;
 * all evaluation and attenuation happens in Rust.
 */
import type {
  AccessExplanation,
  AccessLevel,
  AccessPolicy,
  AccessPrincipal,
  AccessTarget,
  PolicyId,
} from '@mog-sdk/types-document/security';

export interface WorkbookSecurity {
  /**
   * Add a new access policy. Rust enforces capability attenuation: the
   * caller's effective workbook level must be >= the granted level.
   *
   * @returns The assigned PolicyId
   */
  addPolicy(policy: Omit<AccessPolicy, 'id'>): Promise<PolicyId>;

  /**
   * Remove a policy by ID. Idempotent at the store layer.
   */
  removePolicy(id: PolicyId): Promise<void>;

  /**
   * Update fields on an existing policy. Attenuation re-runs when `level`
   * is patched.
   */
  updatePolicy(id: PolicyId, updates: Partial<Omit<AccessPolicy, 'id'>>): Promise<void>;

  /**
   * Get all policies currently on the document, in stable id-sorted order.
   */
  getPolicies(): Promise<AccessPolicy[]>;

  /**
   * Get the effective access level for a principal at a target.
   */
  getEffectiveAccess(principal: AccessPrincipal, target: AccessTarget): Promise<AccessLevel>;

  /**
   * Explain why a principal has a given access level at a target.
   * Returns the winning policy, reason, candidates, and any warnings.
   */
  explainAccess(principal: AccessPrincipal, target: AccessTarget): Promise<AccessExplanation>;

  /**
   * Apply a named template, generating policies. The `templateId` is the
   * Rust tagged-enum variant name (e.g. `protect_workbook`, `protect_sheet`,
   * `agent_structure`); `options` merges into the wire payload under the
   * same keys the Rust `Template` variant expects.
   *
   * @returns The PolicyIds of the generated policies.
   */
  applyTemplate(templateId: string, options: Record<string, unknown>): Promise<PolicyId[]>;

  /**
   * Remove all policies generated by a template.
   */
  removeTemplate(templateId: string): Promise<void>;
}
