// AUTO-GENERATED by compute-wire/src/bin/generate_ts.rs
// Do not edit manually. Regenerate with:
//   cargo run -p compute-wire --bin generate-ts > kernel/src/bridges/wire/constants.gen.ts
//
// Source of truth: compute-core/crates/compute-wire/src/{constants,flags}.rs, domain-types/src/cell_format.rs

// ---------------------------------------------------------------------------
// Wire format layout constants
// ---------------------------------------------------------------------------

/** Wire protocol version — must match Rust WIRE_VERSION. */
export const WIRE_VERSION = 2;

/** Viewport header size in bytes. */
export const HEADER_SIZE = 36;

/** Size of a single cell record (bytes). */
export const CELL_STRIDE = 32;

/** Size of a merge record (bytes). */
export const MERGE_STRIDE = 16;

/** Size of a dimension record (bytes). */
export const DIM_STRIDE = 12;

/** Sentinel for 'no string' in u32 offset fields. */
export const NO_STRING = 0xffffffff;

/** Mutation header size in bytes. */
export const MUTATION_HEADER_SIZE = 16;

/** Mutation cell patch size (row + col + cell record). */
export const PATCH_STRIDE = 40;

// ---------------------------------------------------------------------------
// Cell record byte offsets (within each 32-byte cell record)
// ---------------------------------------------------------------------------

export const OFF_NUMBER_VALUE = 0;
export const OFF_DISPLAY_OFF = 8;
export const OFF_ERROR_OFF = 12;
export const OFF_FLAGS = 16;
export const OFF_FORMAT_IDX = 18;
export const OFF_DISPLAY_LEN = 20;
export const OFF_ERROR_LEN = 22;
export const OFF_BG_COLOR_OVERRIDE = 24;
export const OFF_FONT_COLOR_OVERRIDE = 28;

/** Size of a data bar entry in CF extras section (bytes). */
export const DATA_BAR_ENTRY_STRIDE = 24;

/** Size of an icon entry in CF extras section (bytes). */
export const ICON_ENTRY_STRIDE = 8;

/** Size of a position entry (f64) in bytes. */
export const POSITION_ENTRY_SIZE = 8;

// ---------------------------------------------------------------------------
// Flag bit definitions (cell flags u16 bitfield)
// ---------------------------------------------------------------------------

export const VALUE_TYPE_MASK = 0x7;
export const VALUE_TYPE_NULL = 0;
export const VALUE_TYPE_NUMBER = 1;
export const VALUE_TYPE_TEXT = 2;
export const VALUE_TYPE_BOOL = 3;
export const VALUE_TYPE_ERROR = 4;
export const VALUE_TYPE_IMAGE = 5;
export const HAS_FORMULA = 0x8;
export const HAS_COMMENT = 0x10;
export const HAS_SPARKLINE = 0x20;
export const HAS_HYPERLINK = 0x40;
export const IS_CHECKBOX = 0x80;
export const IS_SPILL_MEMBER = 0x100;
export const HAS_VALIDATION_ERROR = 0x200;
export const HAS_CF_EXTRAS = 0x400;
export const HAS_CELL_IMAGE = 0x800;

/** Value type enum (convenience wrapper over flag bits 0-2). */
export enum ValueType {
  Null = 0,
  Number = 1,
  Text = 2,
  Bool = 3,
  Error = 4,
  Image = 5,
}

// ---------------------------------------------------------------------------
// Mutation header flags (u8 bitfield at header offset 10)
// ---------------------------------------------------------------------------

/** Bit 0: mutation contains projection (spill) changes. */
export const MUT_HAS_PROJECTION_CHANGES = 0x01;
/** Bit 1: mutation contains cell errors. */
export const MUT_HAS_ERRORS = 0x02;
/** Bit 2: mutation contains a format palette delta. */
export const MUT_HAS_PALETTE = 0x04;

// ---------------------------------------------------------------------------
// Icon set names (matches CFIconSetName enum discriminant order)
// ---------------------------------------------------------------------------

/**
 * Icon set names — derived from Rust CFIconSetName::SERDE_NAMES.
 * Source of truth: compute-cf/src/types/enums.rs `CFIconSetName::SERDE_NAMES`.
 */
export const ICON_SET_NAMES: readonly string[] = [
  '3Arrows',
  '3ArrowsGray',
  '3Flags',
  '3TrafficLights1',
  '3TrafficLights2',
  '3Signs',
  '3Symbols',
  '3Symbols2',
  '3Stars',
  '3Triangles',
  '4Arrows',
  '4ArrowsGray',
  '4RedToBlack',
  '4Rating',
  '4TrafficLights',
  '5Arrows',
  '5ArrowsGray',
  '5Rating',
  '5Quarters',
  '5Boxes',
  'NoIcons',
  'Custom',
];

// ---------------------------------------------------------------------------
// Palette binary format constants
// ---------------------------------------------------------------------------

/** Palette section header size: u16 start_index + u16 format_count + u32 string_pool_bytes. */
export const PALETTE_HEADER_SIZE = 8;

/** Size of a string reference in the palette: u32 offset + u16 length. */
export const PALETTE_STR_REF_SIZE = 6;

/** Palette format record presence mask bit constants. */
export const BIT_FONT_FAMILY = 0x00000001;
export const BIT_FONT_SIZE = 0x00000002;
export const BIT_FONT_COLOR = 0x00000004;
export const BIT_BOLD = 0x00000008;
export const BIT_ITALIC = 0x00000010;
export const BIT_UNDERLINE_TYPE = 0x00000020;
export const BIT_STRIKETHROUGH = 0x00000040;
export const BIT_SUPERSCRIPT = 0x00000080;
export const BIT_SUBSCRIPT = 0x00000100;
export const BIT_FONT_OUTLINE = 0x00000200;
export const BIT_FONT_SHADOW = 0x00000400;
export const BIT_FONT_THEME = 0x00000800;
export const BIT_FONT_CHARSET = 0x00001000;
export const BIT_FONT_FAMILY_TYPE = 0x00002000;
export const BIT_HORIZONTAL_ALIGN = 0x00004000;
export const BIT_VERTICAL_ALIGN = 0x00008000;
export const BIT_WRAP_TEXT = 0x00010000;
export const BIT_INDENT = 0x00020000;
export const BIT_TEXT_ROTATION = 0x00040000;
export const BIT_SHRINK_TO_FIT = 0x00080000;
export const BIT_READING_ORDER = 0x00100000;
export const BIT_NUMBER_FORMAT = 0x00200000;
export const BIT_BACKGROUND_COLOR = 0x00400000;
export const BIT_PATTERN_TYPE = 0x00800000;
export const BIT_PATTERN_FG_COLOR = 0x01000000;
export const BIT_GRADIENT_FILL = 0x02000000;
export const BIT_BORDERS = 0x04000000;
export const BIT_LOCKED = 0x08000000;
export const BIT_HIDDEN = 0x10000000;

// ---------------------------------------------------------------------------
// CellFormat field names (Rust source of truth for drift detection)
// ---------------------------------------------------------------------------
//
// These are the camelCase JSON field names produced by serializing the Rust
// CellFormat struct. A TS test compares these against the hand-maintained
// CellFormat interface in @mog-sdk/spreadsheet-contracts to catch field drift.

export const RUST_CELL_FORMAT_FIELDS = [
  'autoIndent',
  'backgroundColor',
  'backgroundColorTint',
  'bold',
  'borders',
  'fontCharset',
  'fontColor',
  'fontColorTint',
  'fontFamily',
  'fontFamilyType',
  'fontOutline',
  'fontShadow',
  'fontSize',
  'fontTheme',
  'gradientFill',
  'hidden',
  'horizontalAlign',
  'indent',
  'italic',
  'locked',
  'numberFormat',
  'patternForegroundColor',
  'patternForegroundColorTint',
  'patternType',
  'quotePrefix',
  'readingOrder',
  'shrinkToFit',
  'strikethrough',
  'subscript',
  'superscript',
  'textRotation',
  'underlineType',
  'verticalAlign',
  'wrapText',
] as const;
