export const CANVAS_PIXELS_PER_POINT = 2;

export const EXCEL_AXIS_LABEL_FONT_SIZE_PT = 9;
export const DEFAULT_AXIS_LABEL_FONT_SIZE =
  EXCEL_AXIS_LABEL_FONT_SIZE_PT * CANVAS_PIXELS_PER_POINT;
export const DEFAULT_AXIS_LABEL_COLLISION_FONT_SIZE = 11;

export const EXCEL_AXIS_TITLE_FONT_SIZE_PT = 10;
export const DEFAULT_AXIS_TITLE_FONT_SIZE =
  EXCEL_AXIS_TITLE_FONT_SIZE_PT * CANVAS_PIXELS_PER_POINT;
