/**
 * @mog/charts - Charting library for the spreadsheet engine
 *
 * Provides Excel-compatible charts with custom rendering engine
 * and reactive data binding.
 *
 * Architecture:
 * - Grammar: Vega-Lite compatible spec system
 * - Components: Fluent API chart builders
 * - Primitives: Low-level marks, scales, and rendering
 *
 * Import guidelines:
 * - Use '@mog/charts' for commonly-used types and functions
 * - Use '@mog/charts/primitives' for scales, renderers, hit testing
 * - Use '@mog/charts/grammar' for spec compiler, layout, encoding, transforms
 * - Use '@mog/charts/export' for OOXML export
 * - Use '@mog/charts/interaction' for pick, tooltip, brush, zoom
 * - Use '@mog/charts/math' for statistics, regression, geometry
 * - Use '@mog/charts/utils' for chart color and OOXML theme color utilities
 */

// Types - chart config, serialization, and data types
export {
  DEFAULT_CHART_COLORS,
  DEFAULT_CHART_CONFIG,
  type AreaSubType,
  type AxisConfig,
  type AxisType,
  type BarSubType,
  type Chart,
  type ChartAnchorMode,
  type ChartConfig,
  type ChartCreateOptions,
  type ChartData,
  type ChartCategoryLevelData,
  type ChartDataPoint,
  type ChartDataSeries,
  type BoxplotConfig,
  type HeatmapConfig,
  type HierarchyChartConfig,
  type HierarchyChartRow,
  type HistogramConfig,
  type ChartLegendEntryIndexKind,
  type ChartLegendEntryVocabulary,
  type ChartSemanticLayer,
  type ChartStyleContext,
  type ChartStyleDiagnostic,
  type ChartStyleOwner,
  type ChartInstance,
  type ChartSeriesCategoryLevelCache,
  type ChartSeriesCategoryLevelsCache,
  type ChartSeriesProjectionAuthority,
  type ChartSeriesProjectionDiagnostic,
  type ChartSeriesProjectionDiagnosticReason,
  type ChartSeriesStockRole,
  type ChartSeriesPointCache,
  type ChartSeriesPointCachePoint,
  type ChartSeriesXRole,
  type ChartType,
  type ChartWorkbookThemeData,
  type CreateChartInput,
  type DataLabelConfig,
  type ImageExportFormat,
  type ImageExportOptions,
  type LegendConfig,
  type LegendPosition,
  type LineSubType,
  type PieSliceConfig,
  type PivotChartProjectionData,
  type RadarSubType,
  type ResolvedChartLegendEntrySnapshot,
  type ResolvedChartProjectedRoleMappingSnapshot,
  type ResolvedChartSourceSeriesSnapshot,
  type SerializedChart,
  type SeriesConfig,
  type SeriesOrientation,
  type SingleAxisConfig,
  type SunburstConfig,
  type StockExactnessEvidenceStatus,
  type StockSourceComposition,
  type StockSubType,
  type TreemapConfig,
  type StoredChartConfig,
  type SubTypeFor,
  type TrendlineConfig,
  type TrendlineType,
  type TypedChartConfig,
  type RegionMapConfig,
  type ViolinConfig,
  type WaterfallConfig,
} from './types';

// Core - pure computation functions
export {
  ObjectCellAccessor,
  HIDDEN_CHART_CELL,
  chartDataSeriesIdentity,
  chartDataToRows,
  chartImportSourceDialect,
  buildBarColumnRectangleModel,
  buildExcelCartesianGeometryPlan,
  buildPieDoughnutGeometry,
  clampPieDoughnutExplosionPercent,
  collectMarks,
  configToSpec,
  defaultPieLikeExplosionPercent,
  detectSeriesOrientation,
  effectivePieLikeExplosionPercent,
  effectiveBarGeometry,
  effectiveBarGeometryFromSpec,
  effectiveGapWidth,
  effectiveOverlap,
  excelBarSlotGeometry,
  extractChartData,
  extractChartDataFromRange,
  hasStockRoleSeries,
  hasStockSubtype,
  hasExcelBarGeometryConfig,
  hasExcelBarGeometrySpec,
  isHiddenChartCellValue,
  isBarLikeChartType,
  isImportedStandardOoxmlChart,
  maxEffectivePieDoughnutExplosionPercent,
  barBaselinePixelForDomain,
  barBaselineValueForDomain,
  pieColorKey,
  pieDisplayLabel,
  pieDoughnutColorDomain,
  pieLegendDisplayLabel,
  parseRange,
  pieLegendKey,
  piePointKey,
  pieDoughnutArcFrame,
  pieDoughnutExplosionOffset,
  pieDoughnutLayoutHintsForConfig,
  pieDoughnutRowsFromGeometry,
  RADAR_LABEL_GAP,
  RADAR_DEFAULT_FILLED_OPACITY,
  RADAR_DEFAULT_SERIES_STROKE_WIDTH,
  RADAR_DEFAULT_MARKER_SIZE,
  RADAR_DEFAULT_GRID_COLOR,
  RADAR_DEFAULT_GRID_WIDTH,
  RADAR_DEFAULT_SPOKE_COLOR,
  RADAR_DEFAULT_SPOKE_WIDTH,
  RADAR_DEFAULT_CATEGORY_LABEL_COLOR,
  RADAR_DEFAULT_CATEGORY_LABEL_FONT_SIZE,
  RADAR_DEFAULT_VALUE_LABEL_COLOR,
  RADAR_DEFAULT_VALUE_LABEL_FONT_SIZE,
  RADAR_DEFAULT_FONT_FAMILY,
  RADAR_AUTO_VALUE_TICK_COUNT,
  RADAR_PLOT_INSET,
  RADAR_START_ANGLE,
  radarAutomaticMarkerShape,
  radarBlankPolicyFromDisplayBlanksAs,
  radarGeometryForPlotArea,
  radarPointAt,
  radarRadiusForValue,
  radarValueDomainFromValues,
  resolveRadarBlankPolicy,
  resolveRadarValueScale,
  expectedStockRolesForSubtype,
  renderedPointValueForRows,
  resolveRadarVisualContract,
  resolveSeriesColorAuthority,
  resolveBarGeometryGroups,
  rustToTsChartType,
  stackModeForChartType,
  seriesConfigForDataSeries,
  seriesConfigSourceIndex,
  seriesConfigSourceKey,
  seriesOrderForDataSeries,
  seriesSourceIndex,
  seriesSourceKey,
  shouldProjectStockSeries,
  shouldRenderStockChart,
  stockRenderedPointProjection,
  stockRenderedRoleValueProjectionFromRoleValues,
  stockRenderedPointProjectionFromRoleValues,
  stockSourceCompositionFromConfig,
  stockSourceRoleOrder,
  stockRoleOrder,
  stockRolePlan,
  stockRolePlanWithEvidence,
  stockSubTypeFromConfig,
  stockSubTypeFromRolePresence,
  stockValueAxisRoles,
  stockVolumeAxisPolicy,
  withSeriesConfigIdentity,
  tsToRustChartType,
  asStockConfig,
  type BarGeometryGroup,
  type BarColumnRectangleModel,
  type BarColumnRectangleModelInput,
  type BarColumnRectangleModelOffset,
  type BarColumnRectangleModelPlotArea,
  type BarColumnRectangleModelRectangle,
  type BarColumnRectangleModelSeries,
  type BarSlotGeometry,
  type CellDataAccessor,
  type CellRange,
  type ChartCellValue,
  type ExcelCartesianGeometryPlan,
  type PieDoughnutArcFrame,
  type PieDoughnutGeometry,
  type PieDoughnutGeometryFamily,
  type PieDoughnutGeometryInput,
  type PieDoughnutGeometryRing,
  type PieDoughnutGeometrySlice,
  type PieDoughnutLayoutAuthority,
  type PieDoughnutLayoutFamily,
  type PieDoughnutLayoutHints,
  type PieDoughnutLayoutReservation,
  type PieDoughnutManualLayoutSource,
  type PieDoughnutLegendPosition,
  type PieDoughnutPlotArea,
  type PieDoughnutStyleContextReservationMode,
  type PieDoughnutStyleContextStatus,
  type PieDoughnutVisualStatus,
  type RustBarDirection,
  type RustChartType,
  type RustChartTypeResult,
  type ResolveBarGeometryGroupsOptions,
  type RadarGeometry,
  type RadarBlankPolicy,
  type RadarBlankPolicyAuthority,
  type RadarBlankPolicyResolution,
  type RadarPolarPoint,
  type ResolveRadarBlankPolicyInput,
  type ResolveRadarValueScaleInput,
  type RadarValueDomain,
  type RadarValueScale,
  type RadarValueScaleAuthority,
  type RadarPointMarkerVisualContract,
  type RadarSeriesVisualContract,
  type RadarVisualContract,
  type StockRenderedPointProjection,
  type StockRenderedRoleValueProjection,
  type StockRole,
  type StockRolePlan,
  type StockPointValue,
  type StockRoleValueArrays,
  type StockSourceRoleValueArrays,
} from './core';

// DOM - chart engine and instance management (requires browser environment)
export { ChartEngine, createChart, createChartEngine } from './dom';

// Primitives - commonly-used mark types and rendering
// For scales, color schemes, renderers, hit testing: import from '@mog/charts/primitives'
export {
  createPieArcs,
  hitTestArc,
  renderMark,
  renderMarks,
  type AnyMark,
  type ArcMark,
  type Mark,
  type MarkStyle,
  type PathMark,
  type PaintSpec,
  type RectMark,
  type ShadowSpec,
  type SymbolMark,
  type SymbolShape,
  type TextAlign,
  type TextBaseline,
  type TextMark,
  type TextRunSpec,
} from './primitives';

// Utils - common color helpers; chart theme/color resolvers live in '@mog/charts/utils'
export { darkenColor, generateGradient, getDefaultColor, lightenColor, withOpacity } from './utils';

// Grammar - Vega-Lite compatible spec types and compiler
export {
  // Transform type guards
  isAggregateTransform,
  isBinTransform,
  isCalculateTransform,
  isDensityTransform,
  isFilterTransform,
  isFoldTransform,
  // Spec type guards
  isLayerSpec,
  isRegressionTransform,
  isSortTransform,
  isUnitSpec,
  type AxisSpec,
  type BaseSpec,
  type ChannelSpec,
  // Core types
  type ChartSpec,
  type ConfigSpec,
  type DataRow,
  type DataSource,
  type EncodingSpec,
  type FieldType,
  type LayerSpec,
  type Layout,
  type LegendSpec,
  type MarkSpec,
  type MarkType,
  type PathOrder,
  type ScaleSpec,
  type StockGlyphBodyVisualSpec,
  type StockGlyphPriceGlyphMode,
  type StockGlyphStrokeVisualSpec,
  type StockGlyphSourceRoleLayerMode,
  type StockGlyphSourceRoleVisualSpec,
  type StockGlyphSubType,
  type StockGlyphVisualRole,
  type StockGlyphVisualSource,
  type StockGlyphVisualSpec,
  type StockGlyphVisualStatus,
  type StockGlyphVolumeVisualSpec,
  type Transform,
  type TransformType,
  type UnitSpec,
} from './grammar/spec';

// Grammar compiler - converts spec + data to renderable marks
export {
  compile,
  type BarGeometryCoordinateSystem,
  type BarGeometryGroupTrace,
  type BarGeometryLayerTrace,
  type BarGeometryTrace,
  type BarGeometryTraceStatus,
  type BarRectangleTrace,
  type CartesianAxisCrossingTrace,
  type CartesianGeometryCoordinateSystem,
  type CartesianGeometryLayerTrace,
  type CartesianGeometryLayerRole,
  type CartesianGeometryPointTrace,
  type CartesianPathAxisLayoutTrace,
  type CartesianGeometryScaleTrace,
  type CartesianGeometrySizeAuthority,
  type CartesianGeometryTrace,
  type CompileOptions,
  type CompileResult,
  type LegendFlowEntryBoundsTrace,
  type LegendFlowTrace,
  type LegendFlowTraceOrient,
  type LegendFlowTraceOverflowPolicy,
  type LegendTrace,
  type PieDoughnutLabelLayoutTrace,
  type PieDoughnutLabelLayoutTraceEntry,
  type ProjectionBoundsTrace,
  type ProjectionOccupancyTrace,
  type ProjectionOccupancyTraceSource,
  type ProjectionTraceCoordinateSpace,
  type TextMeasurementAuthority,
  type TextMeasurementContext,
  type SurfaceApproximationBandAuthority,
  type SurfaceApproximationBandTrace,
  type SurfaceApproximationBandsTrace,
  type SurfaceApproximationContractKind,
  type SurfaceApproximationDensityTrace,
  type SurfaceApproximationGeometryStatus,
  type SurfaceApproximationGridSource,
  type SurfaceApproximationGridTrace,
  type SurfaceApproximationLayerTrace,
  type SurfaceApproximationMarkCountsTrace,
  type SurfaceApproximationMode,
  type SurfaceApproximationPlotAreaPolicy,
  type SurfaceApproximationProjectionTrace,
  type SurfaceApproximationRenderer,
  type SurfaceApproximationTrace,
  type SurfaceApproximationValueDomainTrace,
  type StockGlyphBodyRectTrace,
  type StockGlyphCoordinateSystem,
  type StockGlyphDirection,
  type StockGlyphLayerTrace,
  type StockGlyphPointTrace,
  type StockGlyphScaleTrace,
  type StockGlyphSegmentRole,
  type StockGlyphSegmentTrace,
  type StockGlyphSurfaceTrace,
  type StockGlyphTrace,
  type StockGlyphVolumeRectTrace,
  type StockGlyphXMode,
  type ThreeDApproximationBarShapesTrace,
  type ThreeDApproximationDepthClampStatus,
  type ThreeDApproximationDepthSource,
  type ThreeDApproximationFaceCountsTrace,
  type ThreeDApproximationFaceRole,
  type ThreeDApproximationGeometryStatus,
  type ThreeDApproximationLayerTrace,
  type ThreeDApproximationMarkType,
  type ThreeDApproximationProjectionTrace,
  type ThreeDApproximationRenderer,
  type ThreeDApproximationTrace,
  type ThreeDBarShape,
} from './grammar/compiler';

// Components - Fluent API chart builders
export {
  // Area Chart
  AreaChart,
  AreaChartBuilder,
  // Bar Chart
  BarChart,
  BarChartBuilder,
  BarLineCombo,
  // Base
  BaseChartBuilder,
  BubbleChart,
  ColumnChart,
  // Combo Chart
  ComboChart,
  ComboChartBuilder,
  DonutChart,
  DoughnutChart,
  HorizontalBarChart,
  // Line Chart
  LineChart,
  LineChartBuilder,
  // Pie Chart
  PieChart,
  PieChartBuilder,
  // Scatter Chart
  ScatterChart,
  ScatterChartBuilder,
  ScatterWithTrendline,
  SmoothLineChart,
  StackedAreaChart,
  StepChart,
  StreamGraph,
  flattenAxisMarks,
  flattenLegendMarks,
  // Axis/Legend
  generateAxis,
  generateLegend,
  type ChartBuilder,
} from './components';
