export const FUNCTION_CATEGORIES = {
  financial: {
    label: 'Financial',
    functions: [
      // Time Value of Money (6)
      'PMT',
      'FV',
      'PV',
      'NPER',
      'RATE',
      'FVSCHEDULE',
      // Investment Analysis (5)
      'NPV',
      'IRR',
      'XNPV',
      'XIRR',
      'MIRR',
      // Payment Breakdown (5)
      'IPMT',
      'PPMT',
      'CUMIPMT',
      'CUMPRINC',
      'ISPMT',
      // Depreciation (7)
      'SLN',
      'SYD',
      'DB',
      'DDB',
      'VDB',
      'AMORLINC',
      'AMORDEGRC',
      // Securities & Bonds (12)
      'PRICE',
      'YIELD',
      'DURATION',
      'MDURATION',
      'ACCRINT',
      'ACCRINTM',
      'COUPDAYS',
      'COUPDAYBS',
      'COUPDAYSNC',
      'COUPNUM',
      'COUPPCD',
      'COUPNCD',
      // Treasury Bills (3)
      'TBILLPRICE',
      'TBILLYIELD',
      'TBILLEQ',
      // Discount Securities (7)
      'DISC',
      'INTRATE',
      'RECEIVED',
      'PRICEDISC',
      'PRICEMAT',
      'YIELDDISC',
      'YIELDMAT',
      // Conversion (7)
      'EFFECT',
      'NOMINAL',
      'RRI',
      'PDURATION',
      'DOLLARDE',
      'DOLLARFR',
      'EUROCONVERT',
    ],
  },
  logical: {
    label: 'Logical',
    functions: [
      'IF',
      'IFS',
      'SWITCH',
      'AND',
      'OR',
      'NOT',
      'XOR',
      'IFERROR',
      'IFNA',
      'TRUE',
      'FALSE',
    ],
  },
  text: {
    label: 'Text',
    functions: [
      // Core (10)
      'CONCAT',
      'CONCATENATE',
      'TEXTJOIN',
      'LEFT',
      'RIGHT',
      'MID',
      'LEN',
      'TRIM',
      'CLEAN',
      'T',
      // Case (3)
      'UPPER',
      'LOWER',
      'PROPER',
      // Search & Replace (4)
      'FIND',
      'SEARCH',
      'SUBSTITUTE',
      'REPLACE',
      // Conversion (8)
      'TEXT',
      'VALUE',
      'CHAR',
      'CODE',
      'UNICHAR',
      'UNICODE',
      'DOLLAR',
      'FIXED',
      // Joining (2)
      'REPT',
      'EXACT',
      // Modern Excel 365 (5)
      'TEXTBEFORE',
      'TEXTAFTER',
      'TEXTSPLIT',
      'ARRAYTOTEXT',
      'VALUETOTEXT',
      // Byte Operations (7)
      'LEFTB',
      'RIGHTB',
      'MIDB',
      'LENB',
      'FINDB',
      'SEARCHB',
      'REPLACEB',
      // CJK (4)
      'ASC',
      'DBCS',
      'JIS',
      'PHONETIC',
      // Other (2)
      'NUMBERVALUE',
      'TRIMRANGE',
    ],
  },
  dateTime: {
    label: 'Date & Time',
    functions: [
      // Core (11)
      'TODAY',
      'NOW',
      'DATE',
      'TIME',
      'YEAR',
      'MONTH',
      'DAY',
      'HOUR',
      'MINUTE',
      'SECOND',
      'WEEKDAY',
      // Date Math (2)
      'EDATE',
      'EOMONTH',
      // Parsing (2)
      'DATEVALUE',
      'TIMEVALUE',
      // Calculation (3)
      'DATEDIF',
      'DAYS',
      'DAYS360',
      // Week Info (2)
      'WEEKNUM',
      'ISOWEEKNUM',
      // Workday Functions (4)
      'WORKDAY',
      'WORKDAY.INTL',
      'NETWORKDAYS',
      'NETWORKDAYS.INTL',
      // Financial (1)
      'YEARFRAC',
    ],
  },
  lookup: {
    label: 'Lookup & Reference',
    functions: [
      // Classic Lookup (3)
      'VLOOKUP',
      'HLOOKUP',
      'LOOKUP',
      // Modern Lookup (2)
      'XLOOKUP',
      'XMATCH',
      // Index/Match (3)
      'INDEX',
      'MATCH',
      'CHOOSE',
      // Reference (8)
      'ROW',
      'COLUMN',
      'ROWS',
      'COLUMNS',
      'ADDRESS',
      'INDIRECT',
      'OFFSET',
      'AREAS',
      // Dynamic Arrays (5)
      'FILTER',
      'SORT',
      'SORTBY',
      'UNIQUE',
      'SEQUENCE',
      // Array Manipulation (6)
      'TRANSPOSE',
      'TAKE',
      'DROP',
      'CHOOSEROWS',
      'CHOOSECOLS',
      'EXPAND',
      // Array Stacking (6)
      'HSTACK',
      'VSTACK',
      'WRAPCOLS',
      'WRAPROWS',
      'TOCOL',
      'TOROW',
      // Miscellaneous (3)
      'HYPERLINK',
      'FORMULATEXT',
      'GETPIVOTDATA',
    ],
  },
  mathTrig: {
    label: 'Math & Trig',
    functions: [
      // Basic Aggregation (10)
      'SUM',
      'AVERAGE',
      'COUNT',
      'COUNTA',
      'COUNTBLANK',
      'MAX',
      'MIN',
      'PRODUCT',
      'SUBTOTAL',
      'AGGREGATE',
      // Conditional Aggregation (7)
      'SUMIF',
      'SUMIFS',
      'COUNTIF',
      'COUNTIFS',
      'AVERAGEIF',
      'AVERAGEIFS',
      'SUMPRODUCT',
      // Basic Math (8)
      'ABS',
      'SIGN',
      'MOD',
      'POWER',
      'SQRT',
      'SQRTPI',
      'PI',
      'QUOTIENT',
      // Rounding (15)
      'ROUND',
      'ROUNDUP',
      'ROUNDDOWN',
      'INT',
      'TRUNC',
      'MROUND',
      'EVEN',
      'ODD',
      'CEILING',
      'CEILING.MATH',
      'CEILING.PRECISE',
      'ISO.CEILING',
      'FLOOR',
      'FLOOR.MATH',
      'FLOOR.PRECISE',
      // Trigonometric (13)
      'SIN',
      'COS',
      'TAN',
      'ASIN',
      'ACOS',
      'ATAN',
      'ATAN2',
      'COT',
      'ACOT',
      'SEC',
      'CSC',
      'DEGREES',
      'RADIANS',
      // Hyperbolic (10)
      'SINH',
      'COSH',
      'TANH',
      'ASINH',
      'ACOSH',
      'ATANH',
      'COTH',
      'ACOTH',
      'SECH',
      'CSCH',
      // Logarithmic (4)
      'EXP',
      'LN',
      'LOG',
      'LOG10',
      // Random (3)
      'RAND',
      'RANDBETWEEN',
      'RANDARRAY',
      // Combinatorics (9)
      'FACT',
      'FACTDOUBLE',
      'COMBIN',
      'COMBINA',
      'PERMUT',
      'PERMUTATIONA',
      'GCD',
      'LCM',
      'MULTINOMIAL',
      // Matrix (4)
      'MMULT',
      'MDETERM',
      'MINVERSE',
      'MUNIT',
      // Sum of Squares (4)
      'SUMSQ',
      'SUMX2MY2',
      'SUMX2PY2',
      'SUMXMY2',
      // Conversion (4)
      'BASE',
      'DECIMAL',
      'ROMAN',
      'ARABIC',
    ],
  },
  more: {
    statistical: [
      // Central Tendency
      'AVERAGE',
      'MEDIAN',
      'MODE',
      'MODE.SNGL',
      'MODE.MULT',
      'GEOMEAN',
      'HARMEAN',
      'TRIMMEAN',
      'AVERAGEA',
      // Dispersion
      'STDEV',
      'STDEV.S',
      'STDEV.P',
      'STDEVP',
      'STDEVA',
      'STDEVPA',
      'VAR',
      'VAR.S',
      'VAR.P',
      'VARP',
      'VARA',
      'VARPA',
      'AVEDEV',
      'DEVSQ',
      // Percentile/Quartile
      'PERCENTILE',
      'PERCENTILE.INC',
      'PERCENTILE.EXC',
      'QUARTILE',
      'QUARTILE.INC',
      'QUARTILE.EXC',
      'PERCENTRANK',
      'PERCENTRANK.INC',
      'PERCENTRANK.EXC',
      // Ranking
      'RANK',
      'RANK.EQ',
      'RANK.AVG',
      'LARGE',
      'SMALL',
      // Extremes
      'MAXA',
      'MINA',
      'MAXIFS',
      'MINIFS',
      // Correlation
      'CORREL',
      'PEARSON',
      'COVAR',
      'COVARIANCE.P',
      'COVARIANCE.S',
      'FISHER',
      'FISHERINV',
      // Regression
      'SLOPE',
      'INTERCEPT',
      'RSQ',
      'STEYX',
      'LINEST',
      'LOGEST',
      'TREND',
      'GROWTH',
      'FORECAST',
      'FORECAST.LINEAR',
      'FORECAST.ETS',
      'FORECAST.ETS.CONFINT',
      'FORECAST.ETS.SEASONALITY',
      'FORECAST.ETS.STAT',
      // Shape
      'KURT',
      'SKEW',
      'SKEW.P',
      'FREQUENCY',
      'PROB',
      // Distributions
      'NORM.DIST',
      'NORM.INV',
      'NORM.S.DIST',
      'NORM.S.INV',
      'NORMDIST',
      'NORMINV',
      'NORMSDIST',
      'NORMSINV',
      'STANDARDIZE',
      'BINOM.DIST',
      'BINOM.INV',
      'BINOMDIST',
      'CRITBINOM',
      'BINOM.DIST.RANGE',
      'POISSON',
      'POISSON.DIST',
      'EXPON.DIST',
      'EXPONDIST',
      'LOGNORM.DIST',
      'LOGNORM.INV',
      'LOGNORMDIST',
      'LOGINV',
      'NEGBINOM.DIST',
      'NEGBINOMDIST',
      // Hypothesis Testing
      'Z.TEST',
      'ZTEST',
      'T.TEST',
      'TTEST',
      'T.DIST',
      'T.DIST.2T',
      'T.DIST.RT',
      'T.INV',
      'T.INV.2T',
      'F.TEST',
      'FTEST',
      'F.DIST',
      'F.DIST.RT',
      'F.INV',
      'F.INV.RT',
      'CHISQ.TEST',
      'CHITEST',
      'CHISQ.DIST',
      'CHISQ.DIST.RT',
      'CHISQ.INV',
      'CHISQ.INV.RT',
      'CHIDIST',
      'CHIINV',
    ],
    engineering: [
      // Number System Conversion (12)
      'BIN2DEC',
      'BIN2HEX',
      'BIN2OCT',
      'DEC2BIN',
      'DEC2HEX',
      'DEC2OCT',
      'HEX2BIN',
      'HEX2DEC',
      'HEX2OCT',
      'OCT2BIN',
      'OCT2DEC',
      'OCT2HEX',
      // Bitwise (5)
      'BITAND',
      'BITOR',
      'BITXOR',
      'BITLSHIFT',
      'BITRSHIFT',
      // Complex Numbers (20)
      'COMPLEX',
      'IMABS',
      'IMAGINARY',
      'IMARGUMENT',
      'IMCONJUGATE',
      'IMCOS',
      'IMCOSH',
      'IMCOT',
      'IMCSC',
      'IMCSCH',
      'IMDIV',
      'IMEXP',
      'IMLN',
      'IMLOG10',
      'IMLOG2',
      'IMPOWER',
      'IMPRODUCT',
      'IMREAL',
      'IMSEC',
      'IMSECH',
      'IMSIN',
      'IMSINH',
      'IMSQRT',
      'IMSUB',
      'IMSUM',
      'IMTAN',
      // Bessel (4)
      'BESSELI',
      'BESSELJ',
      'BESSELK',
      'BESSELY',
      // Error Functions (4)
      'ERF',
      'ERF.PRECISE',
      'ERFC',
      'ERFC.PRECISE',
      // Other (2)
      'CONVERT',
      'DELTA',
      'GESTEP',
    ],
    information: [
      'ISBLANK',
      'ISERROR',
      'ISERR',
      'ISNA',
      'ISNUMBER',
      'ISTEXT',
      'ISLOGICAL',
      'ISNONTEXT',
      'ISREF',
      'ISEVEN',
      'ISODD',
      'ISFORMULA',
      'TYPE',
      'ERROR.TYPE',
      'N',
      'NA',
      'CELL',
      'INFO',
      'SHEET',
      'SHEETS',
    ],
    database: [
      'DSUM',
      'DAVERAGE',
      'DCOUNT',
      'DCOUNTA',
      'DMAX',
      'DMIN',
      'DGET',
      'DPRODUCT',
      'DSTDEV',
      'DSTDEVP',
      'DVAR',
      'DVARP',
    ],
  },
};
