/**
 * Built-in Function Catalog — static metadata for all Excel-compatible functions.
 *
 * This module defines metadata (name, category, description, min/max args) for
 * every function supported by the Rust compute-core engine. It populates the
 * globalRegistry so that getFunctionCatalog() and formula autocomplete work
 * in both browser and headless modes.
 *
 * The catalog is auto-populated on first access via ensureFunctionCatalog().
 *
 * Source of truth for function names: compute-core/crates/compute-functions/src/
 * Source of truth for inline-dispatched functions: compute-core/src/eval/engine/eval_primitives.rs
 */

import { FunctionCategory } from '@mog-sdk/contracts/utils/function-registry';
import type { FunctionMetadata } from '@mog-sdk/contracts/utils/function-registry';
import { globalRegistry } from './function-registry';

// =============================================================================
// Compact definition format: [name, category, description, minArgs, maxArgs, arguments?]
// maxArgs = -1 means Infinity (variadic)
// =============================================================================

type FnDef = [
  string,
  FunctionCategory,
  string,
  number,
  number,
  FunctionMetadata['arguments']?,
];

const C = FunctionCategory;

// ---------------------------------------------------------------------------
// Inline-dispatched functions (eval_primitives.rs)
// ---------------------------------------------------------------------------

const INLINE_FUNCTIONS: FnDef[] = [
  // Aggregates
  [
    'SUM',
    C.MATH,
    'Adds all numbers in a range of cells',
    1,
    -1,
    [
      {
        name: 'number1',
        description: 'The first number, cell reference, or range to add',
        type: 'number',
        optional: false,
      },
      {
        name: 'number2',
        description: 'Additional numbers, cell references, or ranges to add',
        type: 'number',
        optional: true,
        repeating: true,
      },
    ],
  ],
  ['AVERAGE', C.STATISTICAL, 'Returns the average of its arguments', 1, -1],
  ['COUNT', C.STATISTICAL, 'Counts the number of cells that contain numbers', 0, -1],
  ['COUNTA', C.STATISTICAL, 'Counts the number of non-empty cells', 0, -1],
  ['COUNTBLANK', C.STATISTICAL, 'Counts empty cells in a range', 1, 1],
  ['MIN', C.STATISTICAL, 'Returns the minimum value in a set of values', 1, -1],
  ['MAX', C.STATISTICAL, 'Returns the maximum value in a set of values', 1, -1],

  // Logical
  ['IF', C.LOGICAL, 'Returns one value if a condition is true and another if false', 1, 3],
  ['AND', C.LOGICAL, 'Returns TRUE if all arguments are TRUE', 1, -1],
  ['OR', C.LOGICAL, 'Returns TRUE if any argument is TRUE', 1, -1],
  ['NOT', C.LOGICAL, 'Reverses the logic of its argument', 1, 1],
  ['IFERROR', C.LOGICAL, 'Returns a value you specify if a formula evaluates to an error', 2, 2],
  ['IFNA', C.LOGICAL, 'Returns a value you specify if a formula evaluates to #N/A', 2, 2],
  ['IFS', C.LOGICAL, 'Checks multiple conditions and returns the first TRUE result', 2, -1],

  // Lookup (inline dispatched)
  ['INDEX', C.LOOKUP, 'Returns the value at a given position in a range', 2, 4],
  ['MATCH', C.LOOKUP, 'Searches for a value in a range and returns its position', 2, 3],
  ['VLOOKUP', C.LOOKUP, 'Looks up a value in the first column of a range', 3, 4],
  ['HLOOKUP', C.LOOKUP, 'Looks up a value in the first row of a range', 3, 4],
  ['XLOOKUP', C.LOOKUP, 'Searches a range and returns a corresponding item', 3, 6],
  ['XMATCH', C.LOOKUP, 'Returns the position of a value in a range', 2, 4],
  ['OFFSET', C.LOOKUP, 'Returns a reference offset from a given reference', 3, 5],
  ['INDIRECT', C.LOOKUP, 'Returns the reference specified by a text string', 1, 2],
  ['ROW', C.LOOKUP, 'Returns the row number of a reference', 0, 1],
  ['COLUMN', C.LOOKUP, 'Returns the column number of a reference', 0, 1],
  ['ROWS', C.LOOKUP, 'Returns the number of rows in a reference', 1, 1],
  ['COLUMNS', C.LOOKUP, 'Returns the number of columns in a reference', 1, 1],

  // Date/Time (inline)
  ['NOW', C.DATE_TIME, 'Returns the current date and time', 0, 0],
  ['TODAY', C.DATE_TIME, 'Returns the current date', 0, 0],

  // Special
  ['LET', C.LOGICAL, 'Assigns names to calculation results', 3, -1],
  ['LAMBDA', C.LOGICAL, 'Creates a custom reusable function', 1, -1],
  ['MAP', C.LOGICAL, 'Returns an array by applying a LAMBDA to each value', 2, -1],
  ['REDUCE', C.LOGICAL, 'Reduces an array to an accumulated value', 3, 3],
  ['SCAN', C.LOGICAL, 'Scans an array by applying a LAMBDA to each value', 3, 3],
  ['MAKEARRAY', C.LOGICAL, 'Returns an array by applying a LAMBDA', 3, 3],
  ['BYROW', C.LOGICAL, 'Applies a LAMBDA to each row and returns an array', 2, 2],
  ['BYCOL', C.LOGICAL, 'Applies a LAMBDA to each column and returns an array', 2, 2],
  ['ISOMITTED', C.INFORMATION, 'Checks whether a LAMBDA argument is omitted', 1, 1],
  ['ISFORMULA', C.INFORMATION, 'Returns TRUE if a cell contains a formula', 1, 1],
  ['SUBTOTAL', C.MATH, 'Returns a subtotal in a list or database', 2, -1],
  ['AGGREGATE', C.MATH, 'Returns an aggregate in a list or database', 3, -1],
  ['SUMPRODUCT', C.MATH, 'Returns the sum of products of corresponding ranges', 1, -1],
  ['GETPIVOTDATA', C.LOOKUP, 'Extracts data from a PivotTable', 2, -1],
  ['MEDIAN', C.STATISTICAL, 'Returns the median of the given numbers', 1, -1],
  ['SMALL', C.STATISTICAL, 'Returns the k-th smallest value in a data set', 2, 2],
  ['LARGE', C.STATISTICAL, 'Returns the k-th largest value in a data set', 2, 2],
  ['MODE.SNGL', C.STATISTICAL, 'Returns the most common value in a data set', 1, -1],

  // Operator function aliases (inline evaluator dispatch over operator semantics)
  ['ADD', C.MATH, 'Returns the sum of two values using the + operator', 2, 2],
  ['MINUS', C.MATH, 'Returns the difference of two values using the - operator', 2, 2],
  ['MULTIPLY', C.MATH, 'Returns the product of two values using the * operator', 2, 2],
  ['DIVIDE', C.MATH, 'Returns the quotient of two values using the / operator', 2, 2],
  ['POW', C.MATH, 'Returns a value raised to a power using the ^ operator', 2, 2],
  ['UMINUS', C.MATH, 'Negates a value using the unary - operator', 1, 1],
  ['UPLUS', C.MATH, 'Applies unary plus using operator coercion semantics', 1, 1],
  ['UNARY_PERCENT', C.MATH, 'Converts a value to a percentage using the % operator', 1, 1],
  ['EQ', C.LOGICAL, 'Compares two values using the = operator', 2, 2],
  ['NE', C.LOGICAL, 'Compares two values using the <> operator', 2, 2],
  ['GT', C.LOGICAL, 'Compares two values using the > operator', 2, 2],
  ['GTE', C.LOGICAL, 'Compares two values using the >= operator', 2, 2],
  ['LT', C.LOGICAL, 'Compares two values using the < operator', 2, 2],
  ['LTE', C.LOGICAL, 'Compares two values using the <= operator', 2, 2],
  ['SINGLE', C.LOOKUP, 'Returns the implicit intersection of a reference', 1, 1],
  ['ANCHORARRAY', C.LOOKUP, 'Returns the spill range anchored at a cell reference', 1, 1],

  // Multi-criteria (inline)
  ['COUNTIF', C.STATISTICAL, 'Counts cells that meet a single criterion', 2, 2],
  ['COUNTIFS', C.STATISTICAL, 'Counts cells that meet multiple criteria', 2, -1],
  ['SUMIF', C.MATH, 'Sums cells that meet a single criterion', 2, 3],
  ['SUMIFS', C.MATH, 'Sums cells that meet multiple criteria', 3, -1],
  ['AVERAGEIF', C.STATISTICAL, 'Averages cells that meet a single criterion', 2, 3],
  ['AVERAGEIFS', C.STATISTICAL, 'Averages cells that meet multiple criteria', 3, -1],
  ['MAXIFS', C.STATISTICAL, 'Returns the maximum value among cells specified by criteria', 3, -1],
  ['MINIFS', C.STATISTICAL, 'Returns the minimum value among cells specified by criteria', 3, -1],
];

// ---------------------------------------------------------------------------
// Pure functions registered in compute-functions crate
// ---------------------------------------------------------------------------

const MATH_FUNCTIONS: FnDef[] = [
  ['ABS', C.MATH, 'Returns the absolute value of a number', 1, 1],
  ['ACOS', C.MATH, 'Returns the arccosine of a number', 1, 1],
  ['ACOSH', C.MATH, 'Returns the inverse hyperbolic cosine', 1, 1],
  ['ACOT', C.MATH, 'Returns the arccotangent of a number', 1, 1],
  ['ACOTH', C.MATH, 'Returns the inverse hyperbolic cotangent', 1, 1],
  ['ARABIC', C.MATH, 'Converts a Roman numeral to Arabic', 1, 1],
  ['ASIN', C.MATH, 'Returns the arcsine of a number', 1, 1],
  ['ATAN2', C.MATH, 'Returns the arctangent from x- and y-coordinates', 2, 2],
  ['ATANH', C.MATH, 'Returns the inverse hyperbolic tangent', 1, 1],
  ['BASE', C.MATH, 'Converts a number to a text representation with the given radix', 2, 3],
  ['CEILING', C.MATH, 'Rounds a number up to the nearest multiple', 1, 2],
  ['CEILING.MATH', C.MATH, 'Rounds a number up to the nearest integer or multiple', 1, 3],
  ['CEILING.PRECISE', C.MATH, 'Rounds a number up to the nearest integer or multiple', 1, 2],
  ['COMBIN', C.MATH, 'Returns the number of combinations', 2, 2],
  ['COMBINA', C.MATH, 'Returns the number of combinations with repetitions', 2, 2],
  ['COT', C.MATH, 'Returns the cotangent of an angle', 1, 1],
  ['COTH', C.MATH, 'Returns the hyperbolic cotangent', 1, 1],
  ['CSC', C.MATH, 'Returns the cosecant of an angle', 1, 1],
  ['CSCH', C.MATH, 'Returns the hyperbolic cosecant', 1, 1],
  ['DECIMAL', C.MATH, 'Converts a text representation of a number to decimal', 2, 2],
  ['EVEN', C.MATH, 'Rounds a number up to the nearest even integer', 1, 1],
  ['EXP', C.MATH, 'Returns e raised to the power of a given number', 1, 1],
  ['FACT', C.MATH, 'Returns the factorial of a number', 1, 1],
  ['FACTDOUBLE', C.MATH, 'Returns the double factorial of a number', 1, 1],
  ['FLOOR', C.MATH, 'Rounds a number down to the nearest multiple', 1, 2],
  ['FLOOR.MATH', C.MATH, 'Rounds a number down to the nearest integer or multiple', 1, 3],
  ['FLOOR.PRECISE', C.MATH, 'Rounds a number down to the nearest integer or multiple', 1, 2],
  ['GCD', C.MATH, 'Returns the greatest common divisor', 1, -1],
  ['INT', C.MATH, 'Rounds a number down to the nearest integer', 1, 1],
  ['ISO.CEILING', C.MATH, 'Rounds up to the nearest integer or multiple (ISO)', 1, 2],
  ['LCM', C.MATH, 'Returns the least common multiple', 1, -1],
  ['LN', C.MATH, 'Returns the natural logarithm of a number', 1, 1],
  ['LOG', C.MATH, 'Returns the logarithm of a number to a specified base', 1, 2],
  ['LOG10', C.MATH, 'Returns the base-10 logarithm', 1, 1],
  ['MDETERM', C.MATH, 'Returns the matrix determinant of an array', 1, 1],
  ['MINVERSE', C.MATH, 'Returns the matrix inverse of an array', 1, 1],
  ['MMULT', C.MATH, 'Returns the matrix product of two arrays', 2, 2],
  ['MOD', C.MATH, 'Returns the remainder from division', 2, 2],
  ['MROUND', C.MATH, 'Rounds to the nearest multiple', 2, 2],
  ['MULTINOMIAL', C.MATH, 'Returns the multinomial of a set of numbers', 1, -1],
  ['MUNIT', C.MATH, 'Returns the unit matrix of the specified dimension', 1, 1],
  ['ODD', C.MATH, 'Rounds a number up to the nearest odd integer', 1, 1],
  ['PERMUT', C.MATH, 'Returns the number of permutations', 2, 2],
  ['PERMUTATIONA', C.MATH, 'Returns the number of permutations with repetitions', 2, 2],
  ['PI', C.MATH, 'Returns the value of pi', 0, 0],
  ['POWER', C.MATH, 'Returns the result of a number raised to a power', 2, 2],
  ['PRODUCT', C.MATH, 'Multiplies all the numbers', 1, -1],
  ['QUOTIENT', C.MATH, 'Returns the integer portion of a division', 2, 2],
  ['RAND', C.MATH, 'Returns a random number between 0 and 1', 0, 0],
  ['RANDARRAY', C.MATH, 'Returns an array of random numbers', 0, 5],
  ['RANDBETWEEN', C.MATH, 'Returns a random integer between two values', 2, 2],
  ['ROMAN', C.MATH, 'Converts an Arabic numeral to Roman', 1, 2],
  ['ROUND', C.MATH, 'Rounds a number to a specified number of digits', 2, 2],
  ['ROUNDDOWN', C.MATH, 'Rounds a number down toward zero', 2, 2],
  ['ROUNDUP', C.MATH, 'Rounds a number up away from zero', 2, 2],
  ['SEC', C.MATH, 'Returns the secant of an angle', 1, 1],
  ['SECH', C.MATH, 'Returns the hyperbolic secant', 1, 1],
  ['SERIESSUM', C.MATH, 'Returns the sum of a power series', 4, 4],
  ['SIGN', C.MATH, 'Returns the sign of a number', 1, 1],
  ['SQRT', C.MATH, 'Returns a positive square root', 1, 1],
  ['SQRTPI', C.MATH, 'Returns the square root of (number * pi)', 1, 1],
  ['SUMSQ', C.MATH, 'Returns the sum of the squares of the arguments', 1, -1],
  ['SUMX2MY2', C.MATH, 'Returns the sum of the difference of squares', 2, 2],
  ['SUMX2PY2', C.MATH, 'Returns the sum of the sum of squares', 2, 2],
  ['SUMXMY2', C.MATH, 'Returns the sum of squares of differences', 2, 2],
  ['TAN', C.MATH, 'Returns the tangent of a number', 1, 1],
  ['TRUNC', C.MATH, 'Truncates a number to an integer', 1, 2],
  ['SIN', C.MATH, 'Returns the sine of a number', 1, 1],
  ['COS', C.MATH, 'Returns the cosine of a number', 1, 1],
  ['SINH', C.MATH, 'Returns the hyperbolic sine', 1, 1],
  ['COSH', C.MATH, 'Returns the hyperbolic cosine', 1, 1],
  ['TANH', C.MATH, 'Returns the hyperbolic tangent', 1, 1],
  ['ATAN', C.MATH, 'Returns the arctangent of a number', 1, 1],
  ['DEGREES', C.MATH, 'Converts radians to degrees', 1, 1],
  ['RADIANS', C.MATH, 'Converts degrees to radians', 1, 1],
];

const TEXT_FUNCTIONS: FnDef[] = [
  ['ARRAYTOTEXT', C.TEXT, 'Returns an array of text values from any range', 1, 2],
  ['ASC', C.TEXT, 'Changes full-width characters to half-width', 1, 1],
  ['BAHTTEXT', C.TEXT, 'Converts a number to Thai baht text', 1, 1],
  ['CHAR', C.TEXT, 'Returns the character specified by the code number', 1, 1],
  ['CLEAN', C.TEXT, 'Removes non-printable characters from text', 1, 1],
  ['CODE', C.TEXT, 'Returns a numeric code for the first character', 1, 1],
  ['CONCAT', C.TEXT, 'Combines text from multiple ranges', 1, -1],
  ['CONCATENATE', C.TEXT, 'Joins several text items into one', 1, -1],
  ['DBCS', C.TEXT, 'Changes half-width characters to full-width', 1, 1],
  ['DOLLAR', C.TEXT, 'Converts a number to text using currency format', 1, 2],
  ['ENCODEURL', C.TEXT, 'Encodes text for use in a URL', 1, 1],
  ['EXACT', C.TEXT, 'Checks whether two text values are identical', 2, 2],
  ['FIND', C.TEXT, 'Finds one text value within another (case-sensitive)', 2, 3],
  ['FINDB', C.TEXT, 'Finds one text value within another (byte-based)', 2, 3],
  ['FIXED', C.TEXT, 'Formats a number as text with a fixed number of decimals', 1, 3],
  ['JIS', C.TEXT, 'Changes half-width characters to full-width', 1, 1],
  ['JOIN', C.TEXT, 'Joins values using a delimiter', 2, -1],
  ['LEFT', C.TEXT, 'Returns the leftmost characters from a text value', 1, 2],
  ['LEFTB', C.TEXT, 'Returns the leftmost bytes from a text value', 1, 2],
  ['LEN', C.TEXT, 'Returns the number of characters in a text string', 1, 1],
  ['LENB', C.TEXT, 'Returns the number of bytes in a text string', 1, 1],
  ['LOWER', C.TEXT, 'Converts text to lowercase', 1, 1],
  ['MID', C.TEXT, 'Returns characters from the middle of a text string', 3, 3],
  ['MIDB', C.TEXT, 'Returns bytes from the middle of a text string', 3, 3],
  ['NUMBERVALUE', C.TEXT, 'Converts text to number in a locale-independent way', 1, 3],
  ['PHONETIC', C.TEXT, 'Extracts phonetic characters from a text string', 1, 1],
  ['PROPER', C.TEXT, 'Capitalizes the first letter of each word', 1, 1],
  ['REPLACE', C.TEXT, 'Replaces characters within text', 4, 4],
  ['REPLACEB', C.TEXT, 'Replaces bytes within text', 4, 4],
  ['REPT', C.TEXT, 'Repeats text a given number of times', 2, 2],
  ['RIGHT', C.TEXT, 'Returns the rightmost characters from a text value', 1, 2],
  ['RIGHTB', C.TEXT, 'Returns the rightmost bytes from a text value', 1, 2],
  ['SEARCH', C.TEXT, 'Finds one text value within another (not case-sensitive)', 2, 3],
  ['SEARCHB', C.TEXT, 'Finds one text value within another (byte-based, not case-sensitive)', 2, 3],
  ['SPLIT', C.TEXT, 'Splits text around a delimiter into a row array', 2, 4],
  ['SUBSTITUTE', C.TEXT, 'Substitutes new text for old text in a string', 3, 4],
  ['T', C.TEXT, 'Converts its arguments to text', 1, 1],
  ['TEXT', C.TEXT, 'Formats a number and converts it to text', 2, 2],
  ['TEXTAFTER', C.TEXT, 'Returns text after a given delimiter', 2, 6],
  ['TEXTBEFORE', C.TEXT, 'Returns text before a given delimiter', 2, 6],
  ['TEXTJOIN', C.TEXT, 'Combines text with a delimiter', 3, -1],
  ['TEXTSPLIT', C.TEXT, 'Splits text by delimiter into an array', 2, 6],
  ['TO_DATE', C.TEXT, 'Converts a number to a date value', 1, 1],
  ['TO_DOLLARS', C.TEXT, 'Converts a number to a dollar value', 1, 1],
  ['TO_PERCENT', C.TEXT, 'Converts a number to a percentage value', 1, 1],
  ['TO_PURE_NUMBER', C.TEXT, 'Removes numeric formatting interpretation from a value', 1, 1],
  ['TO_TEXT', C.TEXT, 'Converts a numeric value to text', 1, 1],
  ['TRIM', C.TEXT, 'Removes spaces from text', 1, 1],
  ['UNICHAR', C.TEXT, 'Returns the Unicode character for a given number', 1, 1],
  ['UNICODE', C.TEXT, 'Returns the number corresponding to the first character', 1, 1],
  ['UPPER', C.TEXT, 'Converts text to uppercase', 1, 1],
  ['VALUE', C.TEXT, 'Converts a text argument to a number', 1, 1],
  ['VALUETOTEXT', C.TEXT, 'Returns text from any value', 1, 2],
];

const LOGICAL_FUNCTIONS: FnDef[] = [
  ['FALSE', C.LOGICAL, 'Returns the logical value FALSE', 0, 0],
  ['TRUE', C.LOGICAL, 'Returns the logical value TRUE', 0, 0],
  ['SWITCH', C.LOGICAL, 'Evaluates an expression against a list of values', 3, -1],
  ['XOR', C.LOGICAL, 'Returns a logical Exclusive OR of all arguments', 1, -1],
];

const LOOKUP_FUNCTIONS: FnDef[] = [
  ['ADDRESS', C.LOOKUP, 'Returns a cell address as text', 2, 5],
  ['AREAS', C.LOOKUP, 'Returns the number of areas in a reference', 1, 1],
  ['CHOOSE', C.LOOKUP, 'Chooses a value from a list of values', 2, -1],
  ['CHOOSECOLS', C.LOOKUP, 'Returns the specified columns from an array', 2, -1],
  ['CHOOSEROWS', C.LOOKUP, 'Returns the specified rows from an array', 2, -1],
  ['DROP', C.LOOKUP, 'Excludes rows or columns from an array', 2, 3],
  ['EXPAND', C.LOOKUP, 'Expands or pads an array', 2, 4],
  ['FILTER', C.LOOKUP, 'Filters a range based on criteria', 2, 3],
  ['FORMULATEXT', C.LOOKUP, 'Returns the formula at the given reference as text', 1, 1],
  ['HSTACK', C.LOOKUP, 'Appends arrays horizontally', 1, -1],
  ['HYPERLINK', C.LOOKUP, 'Creates a shortcut to a document', 1, 2],
  ['LOOKUP', C.LOOKUP, 'Looks up values in a vector or array', 2, 3],
  ['SEQUENCE', C.LOOKUP, 'Generates a list of sequential numbers', 1, 4],
  ['SORT', C.LOOKUP, 'Sorts the contents of a range or array', 1, 4],
  ['SORTBY', C.LOOKUP, 'Sorts a range or array based on another range', 2, -1],
  ['TAKE', C.LOOKUP, 'Returns rows or columns from an array', 2, 3],
  ['TOCOL', C.LOOKUP, 'Converts an array to a single column', 1, 3],
  ['TOROW', C.LOOKUP, 'Converts an array to a single row', 1, 3],
  ['TRANSPOSE', C.LOOKUP, 'Returns the transpose of an array', 1, 1],
  ['UNIQUE', C.LOOKUP, 'Returns unique values from a range', 1, 3],
  ['VSTACK', C.LOOKUP, 'Appends arrays vertically', 1, -1],
  ['WRAPCOLS', C.LOOKUP, 'Wraps a row of values into columns', 2, 3],
  ['WRAPROWS', C.LOOKUP, 'Wraps a row of values into rows', 2, 3],
];

const STATISTICAL_FUNCTIONS: FnDef[] = [
  ['AVEDEV', C.STATISTICAL, 'Returns the average of the absolute deviations', 1, -1],
  ['AVERAGEA', C.STATISTICAL, 'Returns the average including text and logical values', 1, -1],
  ['BETA.DIST', C.STATISTICAL, 'Returns the beta cumulative distribution function', 4, 6],
  ['BETA.INV', C.STATISTICAL, 'Returns the inverse of the beta distribution', 3, 5],
  ['BETADIST', C.STATISTICAL, 'Returns the beta cumulative distribution (compatibility)', 3, 5],
  ['BETAINV', C.STATISTICAL, 'Returns the inverse of the beta distribution (compatibility)', 3, 5],
  ['BINOM.DIST', C.STATISTICAL, 'Returns the binomial distribution probability', 4, 4],
  ['BINOM.DIST.RANGE', C.STATISTICAL, 'Returns the binomial distribution probability range', 3, 4],
  [
    'BINOM.INV',
    C.STATISTICAL,
    'Returns the smallest value for which the binomial CDF is >= criterion',
    3,
    3,
  ],
  ['BINOMDIST', C.STATISTICAL, 'Returns the binomial distribution (compatibility)', 4, 4],
  ['CHIDIST', C.STATISTICAL, 'Returns the chi-squared distribution (compatibility)', 2, 2],
  [
    'CHIINV',
    C.STATISTICAL,
    'Returns the inverse of the chi-squared distribution (compatibility)',
    2,
    2,
  ],
  ['CHISQ.DIST', C.STATISTICAL, 'Returns the chi-squared distribution', 3, 3],
  ['CHISQ.DIST.RT', C.STATISTICAL, 'Returns the right-tailed chi-squared distribution', 2, 2],
  ['CHISQ.INV', C.STATISTICAL, 'Returns the inverse of the chi-squared distribution', 2, 2],
  [
    'CHISQ.INV.RT',
    C.STATISTICAL,
    'Returns the inverse of the right-tailed chi-squared distribution',
    2,
    2,
  ],
  ['CHISQ.TEST', C.STATISTICAL, 'Returns the chi-squared test statistic', 2, 2],
  ['CHITEST', C.STATISTICAL, 'Returns the chi-squared test (compatibility)', 2, 2],
  ['CONFIDENCE', C.STATISTICAL, 'Returns the confidence interval (compatibility)', 3, 3],
  [
    'CONFIDENCE.NORM',
    C.STATISTICAL,
    'Returns the confidence interval using a normal distribution',
    3,
    3,
  ],
  ['CONFIDENCE.T', C.STATISTICAL, 'Returns the confidence interval using a t-distribution', 3, 3],
  ['CORREL', C.STATISTICAL, 'Returns the correlation coefficient between two data sets', 2, 2],
  ['COVAR', C.STATISTICAL, 'Returns covariance (compatibility)', 2, 2],
  ['COVARIANCE.P', C.STATISTICAL, 'Returns the population covariance', 2, 2],
  ['COVARIANCE.S', C.STATISTICAL, 'Returns the sample covariance', 2, 2],
  ['CRITBINOM', C.STATISTICAL, 'Returns the critical binomial value (compatibility)', 3, 3],
  ['DEVSQ', C.STATISTICAL, 'Returns the sum of squares of deviations', 1, -1],
  ['EXPON.DIST', C.STATISTICAL, 'Returns the exponential distribution', 3, 3],
  ['EXPONDIST', C.STATISTICAL, 'Returns the exponential distribution (compatibility)', 3, 3],
  ['F.DIST', C.STATISTICAL, 'Returns the F probability distribution', 4, 4],
  ['F.DIST.RT', C.STATISTICAL, 'Returns the right-tailed F distribution', 3, 3],
  ['F.INV', C.STATISTICAL, 'Returns the inverse of the F distribution', 3, 3],
  ['F.INV.RT', C.STATISTICAL, 'Returns the inverse of the right-tailed F distribution', 3, 3],
  ['F.TEST', C.STATISTICAL, 'Returns the F-test statistic', 2, 2],
  ['FDIST', C.STATISTICAL, 'Returns the F distribution (compatibility)', 3, 3],
  ['FINV', C.STATISTICAL, 'Returns the inverse of the F distribution (compatibility)', 3, 3],
  ['FISHER', C.STATISTICAL, 'Returns the Fisher transformation', 1, 1],
  ['FISHERINV', C.STATISTICAL, 'Returns the inverse of the Fisher transformation', 1, 1],
  ['FORECAST', C.STATISTICAL, 'Returns a value along a linear trend (compatibility)', 3, 3],
  ['FORECAST.ETS', C.STATISTICAL, 'Returns a forecasted value using exponential smoothing', 3, 7],
  ['FORECAST.ETS.CONFINT', C.STATISTICAL, 'Returns a confidence interval for a forecast', 3, 7],
  ['FORECAST.ETS.SEASONALITY', C.STATISTICAL, 'Returns the seasonal pattern length', 2, 4],
  [
    'FORECAST.ETS.STAT',
    C.STATISTICAL,
    'Returns a statistical value for a time series forecast',
    3,
    7,
  ],
  ['FORECAST.LINEAR', C.STATISTICAL, 'Returns a value along a linear trend', 3, 3],
  ['FREQUENCY', C.STATISTICAL, 'Returns a frequency distribution as a vertical array', 2, 2],
  ['FTEST', C.STATISTICAL, 'Returns the F-test (compatibility)', 2, 2],
  ['GAMMA', C.STATISTICAL, 'Returns the Gamma function value', 1, 1],
  ['GAMMA.DIST', C.STATISTICAL, 'Returns the gamma distribution', 4, 4],
  ['GAMMA.INV', C.STATISTICAL, 'Returns the inverse of the gamma distribution', 3, 3],
  ['GAMMADIST', C.STATISTICAL, 'Returns the gamma distribution (compatibility)', 4, 4],
  [
    'GAMMAINV',
    C.STATISTICAL,
    'Returns the inverse of the gamma distribution (compatibility)',
    3,
    3,
  ],
  ['GAMMALN', C.STATISTICAL, 'Returns the natural logarithm of the gamma function', 1, 1],
  ['GAMMALN.PRECISE', C.STATISTICAL, 'Returns the natural logarithm of the gamma function', 1, 1],
  [
    'GAUSS',
    C.STATISTICAL,
    'Returns 0.5 less than the standard normal cumulative distribution',
    1,
    1,
  ],
  ['GEOMEAN', C.STATISTICAL, 'Returns the geometric mean', 1, -1],
  ['GROWTH', C.STATISTICAL, 'Returns values along an exponential trend', 1, 4],
  ['HARMEAN', C.STATISTICAL, 'Returns the harmonic mean', 1, -1],
  ['HYPGEOM.DIST', C.STATISTICAL, 'Returns the hypergeometric distribution', 5, 5],
  ['HYPGEOMDIST', C.STATISTICAL, 'Returns the hypergeometric distribution (compatibility)', 4, 4],
  ['INTERCEPT', C.STATISTICAL, 'Returns the intercept of a linear regression line', 2, 2],
  ['KURT', C.STATISTICAL, 'Returns the kurtosis of a data set', 1, -1],
  ['LINEST', C.STATISTICAL, 'Returns the parameters of a linear trend', 1, 4],
  ['LOGEST', C.STATISTICAL, 'Returns the parameters of an exponential trend', 1, 4],
  [
    'LOGINV',
    C.STATISTICAL,
    'Returns the inverse of the lognormal distribution (compatibility)',
    3,
    3,
  ],
  ['LOGNORM.DIST', C.STATISTICAL, 'Returns the lognormal distribution', 4, 4],
  ['LOGNORM.INV', C.STATISTICAL, 'Returns the inverse of the lognormal distribution', 3, 3],
  ['LOGNORMDIST', C.STATISTICAL, 'Returns the lognormal distribution (compatibility)', 3, 3],
  ['MAXA', C.STATISTICAL, 'Returns the maximum value including text and logical values', 1, -1],
  ['MINA', C.STATISTICAL, 'Returns the minimum value including text and logical values', 1, -1],
  ['MODE', C.STATISTICAL, 'Returns the most common value (compatibility)', 1, -1],
  [
    'MODE.MULT',
    C.STATISTICAL,
    'Returns a vertical array of the most frequently occurring values',
    1,
    -1,
  ],
  ['NEGBINOM.DIST', C.STATISTICAL, 'Returns the negative binomial distribution', 4, 4],
  [
    'NEGBINOMDIST',
    C.STATISTICAL,
    'Returns the negative binomial distribution (compatibility)',
    3,
    3,
  ],
  ['NORM.DIST', C.STATISTICAL, 'Returns the normal distribution', 4, 4],
  ['NORM.INV', C.STATISTICAL, 'Returns the inverse of the normal distribution', 3, 3],
  ['NORM.S.DIST', C.STATISTICAL, 'Returns the standard normal distribution', 2, 2],
  ['NORM.S.INV', C.STATISTICAL, 'Returns the inverse of the standard normal distribution', 1, 1],
  ['NORMDIST', C.STATISTICAL, 'Returns the normal distribution (compatibility)', 4, 4],
  [
    'NORMINV',
    C.STATISTICAL,
    'Returns the inverse of the normal distribution (compatibility)',
    3,
    3,
  ],
  ['NORMSDIST', C.STATISTICAL, 'Returns the standard normal distribution (compatibility)', 1, 1],
  [
    'NORMSINV',
    C.STATISTICAL,
    'Returns the inverse of the standard normal distribution (compatibility)',
    1,
    1,
  ],
  ['PEARSON', C.STATISTICAL, 'Returns the Pearson product moment correlation coefficient', 2, 2],
  ['PERCENTILE', C.STATISTICAL, 'Returns the k-th percentile of values (compatibility)', 2, 2],
  ['PERCENTILE.EXC', C.STATISTICAL, 'Returns the k-th percentile (exclusive)', 2, 2],
  ['PERCENTILE.INC', C.STATISTICAL, 'Returns the k-th percentile (inclusive)', 2, 2],
  ['PERCENTRANK', C.STATISTICAL, 'Returns the percentage rank (compatibility)', 2, 3],
  ['PERCENTRANK.EXC', C.STATISTICAL, 'Returns the percentage rank (exclusive)', 2, 3],
  ['PERCENTRANK.INC', C.STATISTICAL, 'Returns the percentage rank (inclusive)', 2, 3],
  [
    'PHI',
    C.STATISTICAL,
    'Returns the value of the density function for a standard normal distribution',
    1,
    1,
  ],
  ['POISSON', C.STATISTICAL, 'Returns the Poisson distribution (compatibility)', 3, 3],
  ['POISSON.DIST', C.STATISTICAL, 'Returns the Poisson distribution', 3, 3],
  ['PROB', C.STATISTICAL, 'Returns the probability of values in a range', 3, 4],
  ['QUARTILE', C.STATISTICAL, 'Returns the quartile of a data set (compatibility)', 2, 2],
  ['QUARTILE.EXC', C.STATISTICAL, 'Returns the quartile (exclusive)', 2, 2],
  ['QUARTILE.INC', C.STATISTICAL, 'Returns the quartile (inclusive)', 2, 2],
  ['RANK', C.STATISTICAL, 'Returns the rank of a number in a list (compatibility)', 2, 3],
  ['RANK.AVG', C.STATISTICAL, 'Returns the rank (average ranking for ties)', 2, 3],
  ['RANK.EQ', C.STATISTICAL, 'Returns the rank (top ranking for ties)', 2, 3],
  ['RSQ', C.STATISTICAL, 'Returns the R-squared value of a linear regression', 2, 2],
  ['SKEW', C.STATISTICAL, 'Returns the skewness of a distribution', 1, -1],
  ['SKEW.P', C.STATISTICAL, 'Returns the population skewness', 1, -1],
  ['SLOPE', C.STATISTICAL, 'Returns the slope of a linear regression line', 2, 2],
  ['STANDARDIZE', C.STATISTICAL, 'Returns a normalized value', 3, 3],
  ['STDEV', C.STATISTICAL, 'Estimates standard deviation based on a sample (compatibility)', 1, -1],
  ['STDEV.P', C.STATISTICAL, 'Calculates standard deviation based on the entire population', 1, -1],
  ['STDEV.S', C.STATISTICAL, 'Estimates standard deviation based on a sample', 1, -1],
  [
    'STDEVA',
    C.STATISTICAL,
    'Estimates standard deviation including text and logical values',
    1,
    -1,
  ],
  [
    'STDEVP',
    C.STATISTICAL,
    'Calculates standard deviation based on the entire population (compatibility)',
    1,
    -1,
  ],
  [
    'STDEVPA',
    C.STATISTICAL,
    'Calculates standard deviation of a population including text and logical values',
    1,
    -1,
  ],
  ['STEYX', C.STATISTICAL, 'Returns the standard error of the predicted y-value', 2, 2],
  ['T.DIST', C.STATISTICAL, 'Returns the Student t-distribution', 3, 3],
  ['T.DIST.2T', C.STATISTICAL, 'Returns the two-tailed Student t-distribution', 2, 2],
  ['T.DIST.RT', C.STATISTICAL, 'Returns the right-tailed Student t-distribution', 2, 2],
  ['T.INV', C.STATISTICAL, 'Returns the inverse of the Student t-distribution', 2, 2],
  ['T.INV.2T', C.STATISTICAL, 'Returns the inverse of the two-tailed Student t-distribution', 2, 2],
  ['T.TEST', C.STATISTICAL, 'Returns the t-test statistic', 4, 4],
  ['TDIST', C.STATISTICAL, 'Returns the Student t-distribution (compatibility)', 3, 3],
  [
    'TINV',
    C.STATISTICAL,
    'Returns the inverse of the Student t-distribution (compatibility)',
    2,
    2,
  ],
  ['TREND', C.STATISTICAL, 'Returns values along a linear trend', 1, 4],
  ['TRIMMEAN', C.STATISTICAL, 'Returns the mean of the interior of a data set', 2, 2],
  ['TTEST', C.STATISTICAL, 'Returns the t-test (compatibility)', 4, 4],
  ['VAR', C.STATISTICAL, 'Estimates variance based on a sample (compatibility)', 1, -1],
  ['VAR.P', C.STATISTICAL, 'Calculates variance based on the entire population', 1, -1],
  ['VAR.S', C.STATISTICAL, 'Estimates variance based on a sample', 1, -1],
  ['VARA', C.STATISTICAL, 'Estimates variance including text and logical values', 1, -1],
  [
    'VARP',
    C.STATISTICAL,
    'Calculates variance based on the entire population (compatibility)',
    1,
    -1,
  ],
  [
    'VARPA',
    C.STATISTICAL,
    'Calculates variance of a population including text and logical values',
    1,
    -1,
  ],
  ['WEIBULL', C.STATISTICAL, 'Returns the Weibull distribution (compatibility)', 4, 4],
  ['WEIBULL.DIST', C.STATISTICAL, 'Returns the Weibull distribution', 4, 4],
  ['Z.TEST', C.STATISTICAL, 'Returns the one-tailed P-value of a z-test', 2, 3],
  ['ZTEST', C.STATISTICAL, 'Returns the one-tailed P-value of a z-test (compatibility)', 2, 3],
];

const DATETIME_FUNCTIONS: FnDef[] = [
  ['DATE', C.DATE_TIME, 'Returns the serial number of a particular date', 3, 3],
  [
    'DATEDIF',
    C.DATE_TIME,
    'Calculates the number of days, months, or years between two dates',
    3,
    3,
  ],
  ['DATEVALUE', C.DATE_TIME, 'Converts a date in text format to a serial number', 1, 1],
  ['DAY', C.DATE_TIME, 'Converts a serial number to a day of the month', 1, 1],
  ['DAYS', C.DATE_TIME, 'Returns the number of days between two dates', 2, 2],
  [
    'DAYS360',
    C.DATE_TIME,
    'Calculates the number of days between two dates on a 360-day year',
    2,
    3,
  ],
  [
    'EDATE',
    C.DATE_TIME,
    'Returns the serial number of a date that is a given number of months before or after the start date',
    2,
    2,
  ],
  ['EOMONTH', C.DATE_TIME, 'Returns the serial number of the last day of the month', 2, 2],
  ['EPOCHTODATE', C.DATE_TIME, 'Converts a Unix epoch timestamp to a UTC date-time serial', 1, 2],
  ['HOUR', C.DATE_TIME, 'Converts a serial number to an hour', 1, 1],
  ['ISOWEEKNUM', C.DATE_TIME, 'Returns the ISO week number of the year', 1, 1],
  ['MINUTE', C.DATE_TIME, 'Converts a serial number to a minute', 1, 1],
  ['MONTH', C.DATE_TIME, 'Converts a serial number to a month', 1, 1],
  ['NETWORKDAYS', C.DATE_TIME, 'Returns the number of whole workdays between two dates', 2, 3],
  [
    'NETWORKDAYS.INTL',
    C.DATE_TIME,
    'Returns the number of whole workdays between two dates (custom weekends)',
    2,
    4,
  ],
  ['SECOND', C.DATE_TIME, 'Converts a serial number to a second', 1, 1],
  ['TIME', C.DATE_TIME, 'Returns the serial number of a particular time', 3, 3],
  ['TIMEVALUE', C.DATE_TIME, 'Converts a time in text format to a serial number', 1, 1],
  ['WEEKDAY', C.DATE_TIME, 'Converts a serial number to a day of the week', 1, 2],
  ['WEEKNUM', C.DATE_TIME, 'Returns the week number of the year', 1, 2],
  [
    'WORKDAY',
    C.DATE_TIME,
    'Returns a date that is a given number of workdays before or after',
    2,
    3,
  ],
  [
    'WORKDAY.INTL',
    C.DATE_TIME,
    'Returns a date that is a given number of workdays before or after (custom weekends)',
    2,
    4,
  ],
  ['YEAR', C.DATE_TIME, 'Converts a serial number to a year', 1, 1],
  [
    'YEARFRAC',
    C.DATE_TIME,
    'Returns the year fraction representing the number of whole days',
    2,
    3,
  ],
];

const FINANCIAL_FUNCTIONS: FnDef[] = [
  ['ACCRINT', C.FINANCIAL, 'Returns the accrued interest for a security', 6, 8],
  [
    'ACCRINTM',
    C.FINANCIAL,
    'Returns the accrued interest for a security that pays at maturity',
    3,
    5,
  ],
  ['AMORDEGRC', C.FINANCIAL, 'Returns the depreciation for each accounting period (French)', 6, 7],
  [
    'AMORLINC',
    C.FINANCIAL,
    'Returns the depreciation for each accounting period (French, linear)',
    6,
    7,
  ],
  [
    'COUPDAYBS',
    C.FINANCIAL,
    'Returns the number of days from the beginning of the coupon period',
    3,
    4,
  ],
  ['COUPDAYS', C.FINANCIAL, 'Returns the number of days in the coupon period', 3, 4],
  [
    'COUPDAYSNC',
    C.FINANCIAL,
    'Returns the number of days from the settlement date to the next coupon',
    3,
    4,
  ],
  ['COUPNCD', C.FINANCIAL, 'Returns the next coupon date after the settlement date', 3, 4],
  ['COUPNUM', C.FINANCIAL, 'Returns the number of coupons payable', 3, 4],
  ['COUPPCD', C.FINANCIAL, 'Returns the previous coupon date before the settlement date', 3, 4],
  ['CUMIPMT', C.FINANCIAL, 'Returns the cumulative interest paid between two periods', 6, 6],
  ['CUMPRINC', C.FINANCIAL, 'Returns the cumulative principal paid between two periods', 6, 6],
  ['DB', C.FINANCIAL, 'Returns the depreciation using the fixed-declining balance method', 4, 5],
  ['DDB', C.FINANCIAL, 'Returns the depreciation using the double-declining balance method', 4, 5],
  ['DISC', C.FINANCIAL, 'Returns the discount rate for a security', 4, 5],
  ['DOLLARDE', C.FINANCIAL, 'Converts a dollar price expressed as a fraction to decimal', 2, 2],
  ['DOLLARFR', C.FINANCIAL, 'Converts a dollar price expressed as decimal to fraction', 2, 2],
  ['DURATION', C.FINANCIAL, 'Returns the Macauley duration', 5, 6],
  ['EFFECT', C.FINANCIAL, 'Returns the effective annual interest rate', 2, 2],
  ['EUROCONVERT', C.FINANCIAL, 'Converts a number to euros', 3, 5],
  ['FV', C.FINANCIAL, 'Returns the future value of an investment', 3, 5],
  ['FVSCHEDULE', C.FINANCIAL, 'Returns the future value with variable interest rates', 2, 2],
  ['INTRATE', C.FINANCIAL, 'Returns the interest rate for a fully invested security', 4, 5],
  ['IPMT', C.FINANCIAL, 'Returns the interest payment for an investment', 4, 6],
  ['IRR', C.FINANCIAL, 'Returns the internal rate of return', 1, 2],
  ['ISPMT', C.FINANCIAL, 'Returns the interest paid during a specific period', 4, 4],
  ['MDURATION', C.FINANCIAL, 'Returns the modified Macauley duration', 5, 6],
  ['MIRR', C.FINANCIAL, 'Returns the modified internal rate of return', 3, 3],
  ['NOMINAL', C.FINANCIAL, 'Returns the annual nominal interest rate', 2, 2],
  ['NPER', C.FINANCIAL, 'Returns the number of periods for an investment', 3, 5],
  ['NPV', C.FINANCIAL, 'Returns the net present value of an investment', 2, -1],
  [
    'PDURATION',
    C.FINANCIAL,
    'Returns the number of periods for an investment to reach a value',
    3,
    3,
  ],
  ['PMT', C.FINANCIAL, 'Returns the periodic payment for an annuity', 3, 5],
  ['PPMT', C.FINANCIAL, 'Returns the payment on the principal', 4, 6],
  ['PRICE', C.FINANCIAL, 'Returns the price per $100 face value of a security', 6, 7],
  [
    'PRICEDISC',
    C.FINANCIAL,
    'Returns the price per $100 face value of a discounted security',
    4,
    5,
  ],
  [
    'PRICEMAT',
    C.FINANCIAL,
    'Returns the price per $100 face value of a security that pays at maturity',
    5,
    6,
  ],
  ['PV', C.FINANCIAL, 'Returns the present value of an investment', 3, 5],
  ['RATE', C.FINANCIAL, 'Returns the interest rate per period', 3, 6],
  [
    'RECEIVED',
    C.FINANCIAL,
    'Returns the amount received at maturity for a fully invested security',
    4,
    5,
  ],
  ['RRI', C.FINANCIAL, 'Returns an equivalent interest rate for growth', 3, 3],
  ['SLN', C.FINANCIAL, 'Returns the straight-line depreciation', 3, 3],
  ['SYD', C.FINANCIAL, 'Returns the sum-of-years digits depreciation', 4, 4],
  ['TBILLEQ', C.FINANCIAL, 'Returns the bond-equivalent yield for a Treasury bill', 3, 3],
  ['TBILLPRICE', C.FINANCIAL, 'Returns the price per $100 face value for a Treasury bill', 3, 3],
  ['TBILLYIELD', C.FINANCIAL, 'Returns the yield for a Treasury bill', 3, 3],
  ['VDB', C.FINANCIAL, 'Returns the depreciation using a variable declining balance method', 5, 7],
  ['XIRR', C.FINANCIAL, 'Returns the internal rate of return for a schedule of cash flows', 2, 3],
  ['XNPV', C.FINANCIAL, 'Returns the net present value for a schedule of cash flows', 3, 3],
  ['YIELD', C.FINANCIAL, 'Returns the yield on a security', 6, 7],
  ['YIELDDISC', C.FINANCIAL, 'Returns the annual yield for a discounted security', 4, 5],
  ['YIELDMAT', C.FINANCIAL, 'Returns the annual yield of a security that pays at maturity', 5, 6],
];

const ENGINEERING_FUNCTIONS: FnDef[] = [
  ['BESSELI', C.ENGINEERING, 'Returns the modified Bessel function In(x)', 2, 2],
  ['BESSELJ', C.ENGINEERING, 'Returns the Bessel function Jn(x)', 2, 2],
  ['BESSELK', C.ENGINEERING, 'Returns the modified Bessel function Kn(x)', 2, 2],
  ['BESSELY', C.ENGINEERING, 'Returns the Bessel function Yn(x)', 2, 2],
  ['BIN2DEC', C.ENGINEERING, 'Converts a binary number to decimal', 1, 1],
  ['BIN2HEX', C.ENGINEERING, 'Converts a binary number to hexadecimal', 1, 2],
  ['BIN2OCT', C.ENGINEERING, 'Converts a binary number to octal', 1, 2],
  ['BITAND', C.ENGINEERING, 'Returns a bitwise AND of two numbers', 2, 2],
  ['BITLSHIFT', C.ENGINEERING, 'Returns a number shifted left by a specified number of bits', 2, 2],
  ['BITOR', C.ENGINEERING, 'Returns a bitwise OR of two numbers', 2, 2],
  [
    'BITRSHIFT',
    C.ENGINEERING,
    'Returns a number shifted right by a specified number of bits',
    2,
    2,
  ],
  ['BITXOR', C.ENGINEERING, 'Returns a bitwise XOR of two numbers', 2, 2],
  [
    'COMPLEX',
    C.ENGINEERING,
    'Converts real and imaginary coefficients into a complex number',
    2,
    3,
  ],
  ['CONVERT', C.ENGINEERING, 'Converts a number from one measurement system to another', 3, 3],
  ['DEC2BIN', C.ENGINEERING, 'Converts a decimal number to binary', 1, 2],
  ['DEC2HEX', C.ENGINEERING, 'Converts a decimal number to hexadecimal', 1, 2],
  ['DEC2OCT', C.ENGINEERING, 'Converts a decimal number to octal', 1, 2],
  ['DELTA', C.ENGINEERING, 'Tests whether two values are equal', 1, 2],
  ['ERF', C.ENGINEERING, 'Returns the error function', 1, 2],
  ['ERF.PRECISE', C.ENGINEERING, 'Returns the error function', 1, 1],
  ['ERFC', C.ENGINEERING, 'Returns the complementary error function', 1, 1],
  ['ERFC.PRECISE', C.ENGINEERING, 'Returns the complementary error function', 1, 1],
  ['GESTEP', C.ENGINEERING, 'Tests whether a number is greater than a threshold', 1, 2],
  ['HEX2BIN', C.ENGINEERING, 'Converts a hexadecimal number to binary', 1, 2],
  ['HEX2DEC', C.ENGINEERING, 'Converts a hexadecimal number to decimal', 1, 1],
  ['HEX2OCT', C.ENGINEERING, 'Converts a hexadecimal number to octal', 1, 2],
  ['IMARGUMENT', C.ENGINEERING, 'Returns the argument (angle) of a complex number', 1, 1],
  ['IMDIV', C.ENGINEERING, 'Returns the quotient of two complex numbers', 2, 2],
  ['IMPOWER', C.ENGINEERING, 'Returns a complex number raised to a power', 2, 2],
  ['IMPRODUCT', C.ENGINEERING, 'Returns the product of complex numbers', 1, -1],
  ['IMSUB', C.ENGINEERING, 'Returns the difference of two complex numbers', 2, 2],
  ['IMSUM', C.ENGINEERING, 'Returns the sum of complex numbers', 1, -1],
  ['OCT2BIN', C.ENGINEERING, 'Converts an octal number to binary', 1, 2],
  ['OCT2DEC', C.ENGINEERING, 'Converts an octal number to decimal', 1, 1],
  ['OCT2HEX', C.ENGINEERING, 'Converts an octal number to hexadecimal', 1, 2],
];

const DATABASE_FUNCTIONS: FnDef[] = [
  ['DAVERAGE', C.DATABASE, 'Returns the average of matching database entries', 3, 3],
  ['DCOUNT', C.DATABASE, 'Counts cells with numbers in a database', 3, 3],
  ['DCOUNTA', C.DATABASE, 'Counts non-blank cells in a database', 3, 3],
  ['DGET', C.DATABASE, 'Extracts a single value from a database', 3, 3],
  ['DMAX', C.DATABASE, 'Returns the maximum value from matching database entries', 3, 3],
  ['DMIN', C.DATABASE, 'Returns the minimum value from matching database entries', 3, 3],
  ['DPRODUCT', C.DATABASE, 'Multiplies the values of matching database entries', 3, 3],
  ['DSTDEV', C.DATABASE, 'Estimates the standard deviation based on a sample', 3, 3],
  ['DSTDEVP', C.DATABASE, 'Calculates the standard deviation based on the entire population', 3, 3],
  ['DSUM', C.DATABASE, 'Adds the numbers in matching database entries', 3, 3],
  ['DVAR', C.DATABASE, 'Estimates variance based on a sample', 3, 3],
  ['DVARP', C.DATABASE, 'Calculates variance based on the entire population', 3, 3],
];

const INFORMATION_FUNCTIONS: FnDef[] = [
  ['CELL', C.INFORMATION, 'Returns information about a cell', 1, 2],
  ['ERROR.TYPE', C.INFORMATION, 'Returns a number corresponding to an error type', 1, 1],
  ['INFO', C.INFORMATION, 'Returns information about the current operating environment', 1, 1],
  ['ISBLANK', C.INFORMATION, 'Returns TRUE if the value is blank', 1, 1],
  ['ISERR', C.INFORMATION, 'Returns TRUE if the value is any error except #N/A', 1, 1],
  ['ISERROR', C.INFORMATION, 'Returns TRUE if the value is any error value', 1, 1],
  ['ISEVEN', C.INFORMATION, 'Returns TRUE if the number is even', 1, 1],
  ['ISLOGICAL', C.INFORMATION, 'Returns TRUE if the value is a logical value', 1, 1],
  ['ISNA', C.INFORMATION, 'Returns TRUE if the value is #N/A', 1, 1],
  ['ISNONTEXT', C.INFORMATION, 'Returns TRUE if the value is not text', 1, 1],
  ['ISNUMBER', C.INFORMATION, 'Returns TRUE if the value is a number', 1, 1],
  ['ISODD', C.INFORMATION, 'Returns TRUE if the number is odd', 1, 1],
  ['ISREF', C.INFORMATION, 'Returns TRUE if the value is a reference', 1, 1],
  ['ISTEXT', C.INFORMATION, 'Returns TRUE if the value is text', 1, 1],
  ['N', C.INFORMATION, 'Returns a value converted to a number', 1, 1],
  ['NA', C.INFORMATION, 'Returns the error value #N/A', 0, 0],
  ['SHEET', C.INFORMATION, 'Returns the sheet number of the referenced sheet', 0, 1],
  ['SHEETS', C.INFORMATION, 'Returns the number of sheets in a reference', 0, 1],
  ['TYPE', C.INFORMATION, 'Returns a number indicating the data type of a value', 1, 1],
];

// =============================================================================
// All function definitions
// =============================================================================

const ALL_DEFINITIONS: FnDef[] = [
  ...INLINE_FUNCTIONS,
  ...MATH_FUNCTIONS,
  ...TEXT_FUNCTIONS,
  ...LOGICAL_FUNCTIONS,
  ...LOOKUP_FUNCTIONS,
  ...STATISTICAL_FUNCTIONS,
  ...DATETIME_FUNCTIONS,
  ...FINANCIAL_FUNCTIONS,
  ...ENGINEERING_FUNCTIONS,
  ...DATABASE_FUNCTIONS,
  ...INFORMATION_FUNCTIONS,
];

// =============================================================================
// Registry Population
// =============================================================================

let populated = false;

/**
 * Ensure the global function registry is populated with built-in function metadata.
 *
 * Safe to call multiple times (idempotent). Called automatically by
 * getFunctionCatalog() and getFunctionInfo() in the introspection module.
 */
export function ensureFunctionCatalog(): void {
  if (populated) return;
  populated = true;

  const entries: FunctionMetadata[] = ALL_DEFINITIONS.map(
    ([name, category, description, minArgs, maxArgs, args]) => ({
      name,
      category,
      description,
      minArgs,
      maxArgs: maxArgs === -1 ? Infinity : maxArgs,
      arguments: args,
    }),
  );

  globalRegistry.registerMany(entries);
}
