// Auto-generated from Rust compute-formats CultureInfo data.
// Do not edit manually. Regenerate with:
//   cargo test -p bridge-ts --test generate_culture_data -- generate --nocapture
//
// Source: compute-core/crates/compute-formats/src/locale.rs

import type { CultureInfo } from '@mog-sdk/contracts/culture';

export const EN_US: CultureInfo = {
  abbreviatedDayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  abbreviatedMonthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  amDesignator: 'AM',
  currencyCode: 'USD',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 0,
  currencyPositivePattern: 0,
  currencySymbol: '$',
  dateSeparator: '/',
  dayNames: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ],
  decimalSeparator: '.',
  displayName: 'English (United States)',
  falseString: 'FALSE',
  firstDayOfWeek: 0,
  listSeparator: ',',
  longDatePattern: 'dddd, MMMM d, yyyy',
  longTimePattern: 'h:mm:ss tt',
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  name: 'en-US',
  nativeName: 'English (United States)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: 'PM',
  positiveSign: '+',
  shortDatePattern: 'M/d/yyyy',
  shortTimePattern: 'h:mm tt',
  shortestDayNames: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  thousandsSeparator: ',',
  timeSeparator: ':',
  trueString: 'TRUE',
  twoLetterLanguageCode: 'en'
};

export const EN_GB: CultureInfo = {
  abbreviatedDayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  abbreviatedMonthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  amDesignator: 'AM',
  currencyCode: 'GBP',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 1,
  currencyPositivePattern: 0,
  currencySymbol: '£',
  dateSeparator: '/',
  dayNames: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ],
  decimalSeparator: '.',
  displayName: 'English (United Kingdom)',
  falseString: 'FALSE',
  firstDayOfWeek: 1,
  listSeparator: ',',
  longDatePattern: 'dddd, d MMMM yyyy',
  longTimePattern: 'HH:mm:ss',
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  name: 'en-GB',
  nativeName: 'English (United Kingdom)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: 'PM',
  positiveSign: '+',
  shortDatePattern: 'dd/MM/yyyy',
  shortTimePattern: 'HH:mm',
  shortestDayNames: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  thousandsSeparator: ',',
  timeSeparator: ':',
  trueString: 'TRUE',
  twoLetterLanguageCode: 'en'
};

export const DE_DE: CultureInfo = {
  abbreviatedDayNames: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  abbreviatedMonthNames: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
  amDesignator: '',
  currencyCode: 'EUR',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 8,
  currencyPositivePattern: 3,
  currencySymbol: '€',
  dateSeparator: '.',
  dayNames: [
    'Sonntag',
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag'
  ],
  decimalSeparator: ',',
  displayName: 'German (Germany)',
  falseString: 'FALSCH',
  firstDayOfWeek: 1,
  listSeparator: ';',
  longDatePattern: 'dddd, d. MMMM yyyy',
  longTimePattern: 'HH:mm:ss',
  monthNames: [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember'
  ],
  name: 'de-DE',
  nativeName: 'Deutsch (Deutschland)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 0,
  percentPositivePattern: 0,
  percentSymbol: '%',
  pmDesignator: '',
  positiveSign: '+',
  shortDatePattern: 'dd.MM.yyyy',
  shortTimePattern: 'HH:mm',
  shortestDayNames: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  thousandsSeparator: '.',
  timeSeparator: ':',
  trueString: 'WAHR',
  twoLetterLanguageCode: 'de'
};

export const FR_FR: CultureInfo = {
  abbreviatedDayNames: ['dim.', 'lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.'],
  abbreviatedMonthNames: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'],
  amDesignator: '',
  currencyCode: 'EUR',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 8,
  currencyPositivePattern: 3,
  currencySymbol: '€',
  dateSeparator: '/',
  dayNames: [
    'dimanche',
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi'
  ],
  decimalSeparator: ',',
  displayName: 'French (France)',
  falseString: 'FAUX',
  firstDayOfWeek: 1,
  listSeparator: ';',
  longDatePattern: 'dddd d MMMM yyyy',
  longTimePattern: 'HH:mm:ss',
  monthNames: [
    'janvier',
    'février',
    'mars',
    'avril',
    'mai',
    'juin',
    'juillet',
    'août',
    'septembre',
    'octobre',
    'novembre',
    'décembre'
  ],
  name: 'fr-FR',
  nativeName: 'français (France)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 0,
  percentPositivePattern: 0,
  percentSymbol: '%',
  pmDesignator: '',
  positiveSign: '+',
  shortDatePattern: 'dd/MM/yyyy',
  shortTimePattern: 'HH:mm',
  shortestDayNames: ['di', 'lu', 'ma', 'me', 'je', 've', 'sa'],
  thousandsSeparator: ' ',
  timeSeparator: ':',
  trueString: 'VRAI',
  twoLetterLanguageCode: 'fr'
};

export const ES_ES: CultureInfo = {
  abbreviatedDayNames: ['dom.', 'lun.', 'mar.', 'mié.', 'jue.', 'vie.', 'sáb.'],
  abbreviatedMonthNames: ['ene.', 'feb.', 'mar.', 'abr.', 'may.', 'jun.', 'jul.', 'ago.', 'sep.', 'oct.', 'nov.', 'dic.'],
  amDesignator: '',
  currencyCode: 'EUR',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 8,
  currencyPositivePattern: 3,
  currencySymbol: '€',
  dateSeparator: '/',
  dayNames: [
    'domingo',
    'lunes',
    'martes',
    'miércoles',
    'jueves',
    'viernes',
    'sábado'
  ],
  decimalSeparator: ',',
  displayName: 'Spanish (Spain)',
  falseString: 'FALSO',
  firstDayOfWeek: 1,
  listSeparator: ';',
  longDatePattern: 'dddd, d\' de \'MMMM\' de \'yyyy',
  longTimePattern: 'H:mm:ss',
  monthNames: [
    'enero',
    'febrero',
    'marzo',
    'abril',
    'mayo',
    'junio',
    'julio',
    'agosto',
    'septiembre',
    'octubre',
    'noviembre',
    'diciembre'
  ],
  name: 'es-ES',
  nativeName: 'español (España)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 0,
  percentPositivePattern: 0,
  percentSymbol: '%',
  pmDesignator: '',
  positiveSign: '+',
  shortDatePattern: 'd/M/yyyy',
  shortTimePattern: 'H:mm',
  shortestDayNames: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
  thousandsSeparator: '.',
  timeSeparator: ':',
  trueString: 'VERDADERO',
  twoLetterLanguageCode: 'es'
};

export const IT_IT: CultureInfo = {
  abbreviatedDayNames: ['dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
  abbreviatedMonthNames: ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'],
  amDesignator: '',
  currencyCode: 'EUR',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 8,
  currencyPositivePattern: 3,
  currencySymbol: '€',
  dateSeparator: '/',
  dayNames: [
    'domenica',
    'lunedì',
    'martedì',
    'mercoledì',
    'giovedì',
    'venerdì',
    'sabato'
  ],
  decimalSeparator: ',',
  displayName: 'Italian (Italy)',
  falseString: 'FALSO',
  firstDayOfWeek: 1,
  listSeparator: ';',
  longDatePattern: 'dddd d MMMM yyyy',
  longTimePattern: 'HH:mm:ss',
  monthNames: [
    'gennaio',
    'febbraio',
    'marzo',
    'aprile',
    'maggio',
    'giugno',
    'luglio',
    'agosto',
    'settembre',
    'ottobre',
    'novembre',
    'dicembre'
  ],
  name: 'it-IT',
  nativeName: 'italiano (Italia)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 0,
  percentPositivePattern: 0,
  percentSymbol: '%',
  pmDesignator: '',
  positiveSign: '+',
  shortDatePattern: 'dd/MM/yyyy',
  shortTimePattern: 'HH:mm',
  shortestDayNames: ['do', 'lu', 'ma', 'me', 'gi', 've', 'sa'],
  thousandsSeparator: '.',
  timeSeparator: ':',
  trueString: 'VERO',
  twoLetterLanguageCode: 'it'
};

export const PT_BR: CultureInfo = {
  abbreviatedDayNames: ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sáb'],
  abbreviatedMonthNames: ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'],
  amDesignator: '',
  currencyCode: 'BRL',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 9,
  currencyPositivePattern: 2,
  currencySymbol: 'R$',
  dateSeparator: '/',
  dayNames: [
    'domingo',
    'segunda-feira',
    'terça-feira',
    'quarta-feira',
    'quinta-feira',
    'sexta-feira',
    'sábado'
  ],
  decimalSeparator: ',',
  displayName: 'Portuguese (Brazil)',
  falseString: 'FALSO',
  firstDayOfWeek: 0,
  listSeparator: ';',
  longDatePattern: 'dddd, d\' de \'MMMM\' de \'yyyy',
  longTimePattern: 'HH:mm:ss',
  monthNames: [
    'janeiro',
    'fevereiro',
    'março',
    'abril',
    'maio',
    'junho',
    'julho',
    'agosto',
    'setembro',
    'outubro',
    'novembro',
    'dezembro'
  ],
  name: 'pt-BR',
  nativeName: 'português (Brasil)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: '',
  positiveSign: '+',
  shortDatePattern: 'dd/MM/yyyy',
  shortTimePattern: 'HH:mm',
  shortestDayNames: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  thousandsSeparator: '.',
  timeSeparator: ':',
  trueString: 'VERDADEIRO',
  twoLetterLanguageCode: 'pt'
};

export const JA_JP: CultureInfo = {
  abbreviatedDayNames: ['日', '月', '火', '水', '木', '金', '土'],
  abbreviatedMonthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  amDesignator: '午前',
  currencyCode: 'JPY',
  currencyDecimalDigits: 0,
  currencyNegativePattern: 1,
  currencyPositivePattern: 0,
  currencySymbol: '¥',
  dateSeparator: '/',
  dayNames: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
  decimalSeparator: '.',
  displayName: 'Japanese (Japan)',
  falseString: 'FALSE',
  firstDayOfWeek: 0,
  listSeparator: ',',
  longDatePattern: 'yyyy年M月d日',
  longTimePattern: 'H:mm:ss',
  monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  name: 'ja-JP',
  nativeName: '日本語 (日本)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: '午後',
  positiveSign: '+',
  shortDatePattern: 'yyyy/MM/dd',
  shortTimePattern: 'H:mm',
  shortestDayNames: ['日', '月', '火', '水', '木', '金', '土'],
  thousandsSeparator: ',',
  timeSeparator: ':',
  trueString: 'TRUE',
  twoLetterLanguageCode: 'ja'
};

export const ZH_CN: CultureInfo = {
  abbreviatedDayNames: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  abbreviatedMonthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  amDesignator: '上午',
  currencyCode: 'CNY',
  currencyDecimalDigits: 2,
  currencyNegativePattern: 2,
  currencyPositivePattern: 0,
  currencySymbol: '¥',
  dateSeparator: '/',
  dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  decimalSeparator: '.',
  displayName: 'Chinese (Simplified, China)',
  falseString: 'FALSE',
  firstDayOfWeek: 0,
  listSeparator: ',',
  longDatePattern: 'yyyy年M月d日',
  longTimePattern: 'H:mm:ss',
  monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  name: 'zh-CN',
  nativeName: '中文(中国)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: '下午',
  positiveSign: '+',
  shortDatePattern: 'yyyy/M/d',
  shortTimePattern: 'H:mm',
  shortestDayNames: ['日', '一', '二', '三', '四', '五', '六'],
  thousandsSeparator: ',',
  timeSeparator: ':',
  trueString: 'TRUE',
  twoLetterLanguageCode: 'zh'
};

export const KO_KR: CultureInfo = {
  abbreviatedDayNames: ['일', '월', '화', '수', '목', '금', '토'],
  abbreviatedMonthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  amDesignator: '오전',
  currencyCode: 'KRW',
  currencyDecimalDigits: 0,
  currencyNegativePattern: 1,
  currencyPositivePattern: 0,
  currencySymbol: '₩',
  dateSeparator: '-',
  dayNames: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
  decimalSeparator: '.',
  displayName: 'Korean (Korea)',
  falseString: 'FALSE',
  firstDayOfWeek: 0,
  listSeparator: ',',
  longDatePattern: 'yyyy년 M월 d일 dddd',
  longTimePattern: 'tt h:mm:ss',
  monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  name: 'ko-KR',
  nativeName: '한국어(대한민국)',
  negativeNumberPattern: 1,
  negativeSign: '-',
  numberGroupSize: 3,
  perMilleSymbol: '‰',
  percentNegativePattern: 1,
  percentPositivePattern: 1,
  percentSymbol: '%',
  pmDesignator: '오후',
  positiveSign: '+',
  shortDatePattern: 'yyyy-MM-dd',
  shortTimePattern: 'tt h:mm',
  shortestDayNames: ['일', '월', '화', '수', '목', '금', '토'],
  thousandsSeparator: ',',
  timeSeparator: ':',
  trueString: 'TRUE',
  twoLetterLanguageCode: 'ko'
};
