/// Preset color value (ECMA-376 ST_PresetColorVal).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum PresetColorVal {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DkBlue,
    DkCyan,
    DkGoldenrod,
    DkGray,
    DkGreen,
    DkKhaki,
    DkMagenta,
    DkOliveGreen,
    DkOrange,
    DkOrchid,
    DkRed,
    DkSalmon,
    DkSeaGreen,
    DkSlateBlue,
    DkSlateGray,
    DkTurquoise,
    DkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DodgerBlue,
    Firebrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    Goldenrod,
    Gray,
    Green,
    GreenYellow,
    Honeydew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LtBlue,
    LtCoral,
    LtCyan,
    LtGoldenrodYellow,
    LtGray,
    LtGreen,
    LtPink,
    LtSalmon,
    LtSeaGreen,
    LtSkyBlue,
    LtSlateGray,
    LtSteelBlue,
    LtYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MedAquamarine,
    MedBlue,
    MedOrchid,
    MedPurple,
    MedSeaGreen,
    MedSlateBlue,
    MedSpringGreen,
    MedTurquoise,
    MedVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenrod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

impl PresetColorVal {
    #[must_use]
    pub fn from_ooxml(s: &str) -> Self {
        match s {
            "aliceBlue" => Self::AliceBlue,
            "antiqueWhite" => Self::AntiqueWhite,
            "aqua" => Self::Aqua,
            "aquamarine" => Self::Aquamarine,
            "azure" => Self::Azure,
            "beige" => Self::Beige,
            "bisque" => Self::Bisque,
            "black" => Self::Black,
            "blanchedAlmond" => Self::BlanchedAlmond,
            "blue" => Self::Blue,
            "blueViolet" => Self::BlueViolet,
            "brown" => Self::Brown,
            "burlyWood" => Self::BurlyWood,
            "cadetBlue" => Self::CadetBlue,
            "chartreuse" => Self::Chartreuse,
            "chocolate" => Self::Chocolate,
            "coral" => Self::Coral,
            "cornflowerBlue" => Self::CornflowerBlue,
            "cornsilk" => Self::Cornsilk,
            "crimson" => Self::Crimson,
            "cyan" => Self::Cyan,
            "dkBlue" => Self::DkBlue,
            "dkCyan" => Self::DkCyan,
            "dkGoldenrod" => Self::DkGoldenrod,
            "dkGray" => Self::DkGray,
            "dkGreen" => Self::DkGreen,
            "dkKhaki" => Self::DkKhaki,
            "dkMagenta" => Self::DkMagenta,
            "dkOliveGreen" => Self::DkOliveGreen,
            "dkOrange" => Self::DkOrange,
            "dkOrchid" => Self::DkOrchid,
            "dkRed" => Self::DkRed,
            "dkSalmon" => Self::DkSalmon,
            "dkSeaGreen" => Self::DkSeaGreen,
            "dkSlateBlue" => Self::DkSlateBlue,
            "dkSlateGray" => Self::DkSlateGray,
            "dkTurquoise" => Self::DkTurquoise,
            "dkViolet" => Self::DkViolet,
            "deepPink" => Self::DeepPink,
            "deepSkyBlue" => Self::DeepSkyBlue,
            "dimGray" => Self::DimGray,
            "dodgerBlue" => Self::DodgerBlue,
            "firebrick" => Self::Firebrick,
            "floralWhite" => Self::FloralWhite,
            "forestGreen" => Self::ForestGreen,
            "fuchsia" => Self::Fuchsia,
            "gainsboro" => Self::Gainsboro,
            "ghostWhite" => Self::GhostWhite,
            "gold" => Self::Gold,
            "goldenrod" => Self::Goldenrod,
            "gray" => Self::Gray,
            "green" => Self::Green,
            "greenYellow" => Self::GreenYellow,
            "honeydew" => Self::Honeydew,
            "hotPink" => Self::HotPink,
            "indianRed" => Self::IndianRed,
            "indigo" => Self::Indigo,
            "ivory" => Self::Ivory,
            "khaki" => Self::Khaki,
            "lavender" => Self::Lavender,
            "lavenderBlush" => Self::LavenderBlush,
            "lawnGreen" => Self::LawnGreen,
            "lemonChiffon" => Self::LemonChiffon,
            "ltBlue" => Self::LtBlue,
            "ltCoral" => Self::LtCoral,
            "ltCyan" => Self::LtCyan,
            "ltGoldenrodYellow" => Self::LtGoldenrodYellow,
            "ltGray" => Self::LtGray,
            "ltGreen" => Self::LtGreen,
            "ltPink" => Self::LtPink,
            "ltSalmon" => Self::LtSalmon,
            "ltSeaGreen" => Self::LtSeaGreen,
            "ltSkyBlue" => Self::LtSkyBlue,
            "ltSlateGray" => Self::LtSlateGray,
            "ltSteelBlue" => Self::LtSteelBlue,
            "ltYellow" => Self::LtYellow,
            "lime" => Self::Lime,
            "limeGreen" => Self::LimeGreen,
            "linen" => Self::Linen,
            "magenta" => Self::Magenta,
            "maroon" => Self::Maroon,
            "medAquamarine" => Self::MedAquamarine,
            "medBlue" => Self::MedBlue,
            "medOrchid" => Self::MedOrchid,
            "medPurple" => Self::MedPurple,
            "medSeaGreen" => Self::MedSeaGreen,
            "medSlateBlue" => Self::MedSlateBlue,
            "medSpringGreen" => Self::MedSpringGreen,
            "medTurquoise" => Self::MedTurquoise,
            "medVioletRed" => Self::MedVioletRed,
            "midnightBlue" => Self::MidnightBlue,
            "mintCream" => Self::MintCream,
            "mistyRose" => Self::MistyRose,
            "moccasin" => Self::Moccasin,
            "navajoWhite" => Self::NavajoWhite,
            "navy" => Self::Navy,
            "oldLace" => Self::OldLace,
            "olive" => Self::Olive,
            "oliveDrab" => Self::OliveDrab,
            "orange" => Self::Orange,
            "orangeRed" => Self::OrangeRed,
            "orchid" => Self::Orchid,
            "paleGoldenrod" => Self::PaleGoldenrod,
            "paleGreen" => Self::PaleGreen,
            "paleTurquoise" => Self::PaleTurquoise,
            "paleVioletRed" => Self::PaleVioletRed,
            "papayaWhip" => Self::PapayaWhip,
            "peachPuff" => Self::PeachPuff,
            "peru" => Self::Peru,
            "pink" => Self::Pink,
            "plum" => Self::Plum,
            "powderBlue" => Self::PowderBlue,
            "purple" => Self::Purple,
            "red" => Self::Red,
            "rosyBrown" => Self::RosyBrown,
            "royalBlue" => Self::RoyalBlue,
            "saddleBrown" => Self::SaddleBrown,
            "salmon" => Self::Salmon,
            "sandyBrown" => Self::SandyBrown,
            "seaGreen" => Self::SeaGreen,
            "seaShell" => Self::SeaShell,
            "sienna" => Self::Sienna,
            "silver" => Self::Silver,
            "skyBlue" => Self::SkyBlue,
            "slateBlue" => Self::SlateBlue,
            "slateGray" => Self::SlateGray,
            "snow" => Self::Snow,
            "springGreen" => Self::SpringGreen,
            "steelBlue" => Self::SteelBlue,
            "tan" => Self::Tan,
            "teal" => Self::Teal,
            "thistle" => Self::Thistle,
            "tomato" => Self::Tomato,
            "turquoise" => Self::Turquoise,
            "violet" => Self::Violet,
            "wheat" => Self::Wheat,
            "white" => Self::White,
            "whiteSmoke" => Self::WhiteSmoke,
            "yellow" => Self::Yellow,
            "yellowGreen" => Self::YellowGreen,

            // ECMA-376 ST_PresetColorVal long-form aliases (dark*, light*, medium*).
            "darkBlue" => Self::DkBlue,
            "darkCyan" => Self::DkCyan,
            "darkGoldenrod" => Self::DkGoldenrod,
            "darkGray" => Self::DkGray,
            "darkGreen" => Self::DkGreen,
            "darkKhaki" => Self::DkKhaki,
            "darkMagenta" => Self::DkMagenta,
            "darkOliveGreen" => Self::DkOliveGreen,
            "darkOrange" => Self::DkOrange,
            "darkOrchid" => Self::DkOrchid,
            "darkRed" => Self::DkRed,
            "darkSalmon" => Self::DkSalmon,
            "darkSeaGreen" => Self::DkSeaGreen,
            "darkSlateBlue" => Self::DkSlateBlue,
            "darkSlateGray" => Self::DkSlateGray,
            "darkTurquoise" => Self::DkTurquoise,
            "darkViolet" => Self::DkViolet,
            "lightBlue" => Self::LtBlue,
            "lightCoral" => Self::LtCoral,
            "lightCyan" => Self::LtCyan,
            "lightGoldenrodYellow" => Self::LtGoldenrodYellow,
            "lightGray" => Self::LtGray,
            "lightGreen" => Self::LtGreen,
            "lightPink" => Self::LtPink,
            "lightSalmon" => Self::LtSalmon,
            "lightSeaGreen" => Self::LtSeaGreen,
            "lightSkyBlue" => Self::LtSkyBlue,
            "lightSlateGray" => Self::LtSlateGray,
            "lightSteelBlue" => Self::LtSteelBlue,
            "lightYellow" => Self::LtYellow,
            "mediumAquamarine" => Self::MedAquamarine,
            "mediumBlue" => Self::MedBlue,
            "mediumOrchid" => Self::MedOrchid,
            "mediumPurple" => Self::MedPurple,
            "mediumSeaGreen" => Self::MedSeaGreen,
            "mediumSlateBlue" => Self::MedSlateBlue,
            "mediumSpringGreen" => Self::MedSpringGreen,
            "mediumTurquoise" => Self::MedTurquoise,
            "mediumVioletRed" => Self::MedVioletRed,

            // Grey spelling variants (British spelling accepted by the spec).
            "grey" => Self::Gray,
            "dimGrey" => Self::DimGray,
            "dkGrey" => Self::DkGray,
            "dkSlateGrey" => Self::DkSlateGray,
            "ltGrey" => Self::LtGray,
            "ltSlateGrey" => Self::LtSlateGray,
            "slateGrey" => Self::SlateGray,
            "darkGrey" => Self::DkGray,
            "darkSlateGrey" => Self::DkSlateGray,
            "lightGrey" => Self::LtGray,
            "lightSlateGrey" => Self::LtSlateGray,

            _ => Self::Black, // safe default
        }
    }

    #[must_use]
    pub fn to_ooxml(&self) -> &'static str {
        match self {
            Self::AliceBlue => "aliceBlue",
            Self::AntiqueWhite => "antiqueWhite",
            Self::Aqua => "aqua",
            Self::Aquamarine => "aquamarine",
            Self::Azure => "azure",
            Self::Beige => "beige",
            Self::Bisque => "bisque",
            Self::Black => "black",
            Self::BlanchedAlmond => "blanchedAlmond",
            Self::Blue => "blue",
            Self::BlueViolet => "blueViolet",
            Self::Brown => "brown",
            Self::BurlyWood => "burlyWood",
            Self::CadetBlue => "cadetBlue",
            Self::Chartreuse => "chartreuse",
            Self::Chocolate => "chocolate",
            Self::Coral => "coral",
            Self::CornflowerBlue => "cornflowerBlue",
            Self::Cornsilk => "cornsilk",
            Self::Crimson => "crimson",
            Self::Cyan => "cyan",
            Self::DkBlue => "dkBlue",
            Self::DkCyan => "dkCyan",
            Self::DkGoldenrod => "dkGoldenrod",
            Self::DkGray => "dkGray",
            Self::DkGreen => "dkGreen",
            Self::DkKhaki => "dkKhaki",
            Self::DkMagenta => "dkMagenta",
            Self::DkOliveGreen => "dkOliveGreen",
            Self::DkOrange => "dkOrange",
            Self::DkOrchid => "dkOrchid",
            Self::DkRed => "dkRed",
            Self::DkSalmon => "dkSalmon",
            Self::DkSeaGreen => "dkSeaGreen",
            Self::DkSlateBlue => "dkSlateBlue",
            Self::DkSlateGray => "dkSlateGray",
            Self::DkTurquoise => "dkTurquoise",
            Self::DkViolet => "dkViolet",
            Self::DeepPink => "deepPink",
            Self::DeepSkyBlue => "deepSkyBlue",
            Self::DimGray => "dimGray",
            Self::DodgerBlue => "dodgerBlue",
            Self::Firebrick => "firebrick",
            Self::FloralWhite => "floralWhite",
            Self::ForestGreen => "forestGreen",
            Self::Fuchsia => "fuchsia",
            Self::Gainsboro => "gainsboro",
            Self::GhostWhite => "ghostWhite",
            Self::Gold => "gold",
            Self::Goldenrod => "goldenrod",
            Self::Gray => "gray",
            Self::Green => "green",
            Self::GreenYellow => "greenYellow",
            Self::Honeydew => "honeydew",
            Self::HotPink => "hotPink",
            Self::IndianRed => "indianRed",
            Self::Indigo => "indigo",
            Self::Ivory => "ivory",
            Self::Khaki => "khaki",
            Self::Lavender => "lavender",
            Self::LavenderBlush => "lavenderBlush",
            Self::LawnGreen => "lawnGreen",
            Self::LemonChiffon => "lemonChiffon",
            Self::LtBlue => "ltBlue",
            Self::LtCoral => "ltCoral",
            Self::LtCyan => "ltCyan",
            Self::LtGoldenrodYellow => "ltGoldenrodYellow",
            Self::LtGray => "ltGray",
            Self::LtGreen => "ltGreen",
            Self::LtPink => "ltPink",
            Self::LtSalmon => "ltSalmon",
            Self::LtSeaGreen => "ltSeaGreen",
            Self::LtSkyBlue => "ltSkyBlue",
            Self::LtSlateGray => "ltSlateGray",
            Self::LtSteelBlue => "ltSteelBlue",
            Self::LtYellow => "ltYellow",
            Self::Lime => "lime",
            Self::LimeGreen => "limeGreen",
            Self::Linen => "linen",
            Self::Magenta => "magenta",
            Self::Maroon => "maroon",
            Self::MedAquamarine => "medAquamarine",
            Self::MedBlue => "medBlue",
            Self::MedOrchid => "medOrchid",
            Self::MedPurple => "medPurple",
            Self::MedSeaGreen => "medSeaGreen",
            Self::MedSlateBlue => "medSlateBlue",
            Self::MedSpringGreen => "medSpringGreen",
            Self::MedTurquoise => "medTurquoise",
            Self::MedVioletRed => "medVioletRed",
            Self::MidnightBlue => "midnightBlue",
            Self::MintCream => "mintCream",
            Self::MistyRose => "mistyRose",
            Self::Moccasin => "moccasin",
            Self::NavajoWhite => "navajoWhite",
            Self::Navy => "navy",
            Self::OldLace => "oldLace",
            Self::Olive => "olive",
            Self::OliveDrab => "oliveDrab",
            Self::Orange => "orange",
            Self::OrangeRed => "orangeRed",
            Self::Orchid => "orchid",
            Self::PaleGoldenrod => "paleGoldenrod",
            Self::PaleGreen => "paleGreen",
            Self::PaleTurquoise => "paleTurquoise",
            Self::PaleVioletRed => "paleVioletRed",
            Self::PapayaWhip => "papayaWhip",
            Self::PeachPuff => "peachPuff",
            Self::Peru => "peru",
            Self::Pink => "pink",
            Self::Plum => "plum",
            Self::PowderBlue => "powderBlue",
            Self::Purple => "purple",
            Self::Red => "red",
            Self::RosyBrown => "rosyBrown",
            Self::RoyalBlue => "royalBlue",
            Self::SaddleBrown => "saddleBrown",
            Self::Salmon => "salmon",
            Self::SandyBrown => "sandyBrown",
            Self::SeaGreen => "seaGreen",
            Self::SeaShell => "seaShell",
            Self::Sienna => "sienna",
            Self::Silver => "silver",
            Self::SkyBlue => "skyBlue",
            Self::SlateBlue => "slateBlue",
            Self::SlateGray => "slateGray",
            Self::Snow => "snow",
            Self::SpringGreen => "springGreen",
            Self::SteelBlue => "steelBlue",
            Self::Tan => "tan",
            Self::Teal => "teal",
            Self::Thistle => "thistle",
            Self::Tomato => "tomato",
            Self::Turquoise => "turquoise",
            Self::Violet => "violet",
            Self::Wheat => "wheat",
            Self::White => "white",
            Self::WhiteSmoke => "whiteSmoke",
            Self::Yellow => "yellow",
            Self::YellowGreen => "yellowGreen",
        }
    }
}
