/**
 * Cross-language roundtrip tests.
 *
 * Reads binary fixtures generated by Rust's `generate_test_fixtures` binary
 * and verifies the TS decoders produce the expected values from the JSON
 * sidecar files.
 *
 * If fixtures are missing, tests fail loudly with a regeneration command.
 *
 * Regenerate fixtures:
 *   cargo run -p compute-wire --bin generate-test-fixtures
 */

// Polyfill window for Node test environment (devtools reporting uses `window`)
if (typeof globalThis.window === 'undefined') {
  (globalThis as any).window = {};
}

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'node:url';
import { BinaryMutationReader } from '../binary-mutation-reader';
import { BinaryViewportBuffer, CellAccessor, ValueType } from '../binary-viewport-buffer';

const TEST_DIR = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(TEST_DIR, 'fixtures');

function loadFixture(name: string): { bin: Uint8Array; json: any } {
  const binPath = path.join(FIXTURES_DIR, `${name}.bin`);
  const jsonPath = path.join(FIXTURES_DIR, `${name}.json`);

  if (!fs.existsSync(binPath)) {
    throw new Error(
      `Fixture ${name}.bin not found at ${binPath}. Regenerate with: cargo run -p compute-wire --bin generate-test-fixtures`,
    );
  }

  if (!fs.existsSync(jsonPath)) {
    throw new Error(
      `Fixture ${name}.json not found at ${jsonPath}. Regenerate with: cargo run -p compute-wire --bin generate-test-fixtures`,
    );
  }

  const bin = new Uint8Array(fs.readFileSync(binPath));
  const json = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  return { bin, json };
}

// Load fixtures eagerly so dynamic test generation works at describe-time
const viewportFixture = loadFixture('viewport');
const mutationFixture = loadFixture('mutation');

// ==========================================================================
// Viewport roundtrip tests
// ==========================================================================

describe('Cross-language roundtrip: viewport', () => {
  const json = viewportFixture.json;
  let buf: BinaryViewportBuffer;
  let accessor: CellAccessor;

  beforeAll(() => {
    buf = new BinaryViewportBuffer();
    buf.setBuffer(viewportFixture.bin);
    accessor = buf.createAccessor();
  });

  // --- Header fields ---

  test('header: startRow', () => {
    expect(buf.getStartRow()).toBe(json.startRow);
  });

  test('header: startCol', () => {
    expect(buf.getStartCol()).toBe(json.startCol);
  });

  test('header: rows (viewportRows)', () => {
    expect(buf.getRows()).toBe(json.rows);
  });

  test('header: cols (viewportCols)', () => {
    expect(buf.getCols()).toBe(json.cols);
  });

  test('header: cellCount', () => {
    expect(buf.getCellCount()).toBe(json.cellCount);
  });

  test('header: generation', () => {
    expect(buf.getGeneration()).toBe(json.generation);
  });

  // --- Cell data ---

  describe('cell data', () => {
    for (const cell of json.cells) {
      const label = `cell (${cell.row}, ${cell.col})`;

      describe(label, () => {
        beforeEach(() => {
          // moveTo takes absolute row/col (internally subtracts startRow/startCol)
          const ok = accessor.moveTo(cell.row, cell.col);
          expect(ok).toBe(true);
        });

        test('valueType', () => {
          expect(accessor.valueType).toBe(cell.valueType);
        });

        test('numberValue', () => {
          if (cell.numberValue === null || cell.numberValue === undefined) {
            // Null/empty cells or text cells: numberValue should be NaN
            expect(accessor.numberValue).toBeNaN();
          } else {
            expect(accessor.numberValue).toBeCloseTo(cell.numberValue, 10);
          }
        });

        test('displayText', () => {
          const expected = cell.display ?? null;
          expect(accessor.displayText).toBe(expected);
        });

        test('errorText', () => {
          const expected = cell.error ?? null;
          expect(accessor.errorText).toBe(expected);
        });

        if (cell.hasFormula !== undefined) {
          test('hasFormula', () => {
            expect(accessor.hasFormula).toBe(cell.hasFormula);
          });
        }

        if (cell.hasComment !== undefined) {
          test('hasComment', () => {
            expect(accessor.hasComment).toBe(cell.hasComment);
          });
        }

        if (cell.hasHyperlink !== undefined) {
          test('hasHyperlink', () => {
            expect(accessor.hasHyperlink).toBe(cell.hasHyperlink);
          });
        }

        if (cell.isProjectedPosition !== undefined) {
          test('isProjectedPosition', () => {
            expect(accessor.isProjectedPosition).toBe(cell.isProjectedPosition);
          });
        }

        if (cell.formatIdx !== undefined) {
          test('formatIdx', () => {
            expect(accessor.formatIdx).toBe(cell.formatIdx);
          });
        }
      });
    }
  });

  // --- Cells without flags default to false ---

  test('cells without flag fields default to false', () => {
    // Pick the text cell which has no flag fields set in JSON
    const textCell = json.cells.find((c: any) => c.valueType === ValueType.Text);
    if (textCell) {
      accessor.moveTo(textCell.row, textCell.col);
      if (textCell.hasFormula === undefined) {
        expect(accessor.hasFormula).toBe(false);
      }
      if (textCell.hasComment === undefined) {
        expect(accessor.hasComment).toBe(false);
      }
      if (textCell.hasHyperlink === undefined) {
        expect(accessor.hasHyperlink).toBe(false);
      }
    }
  });

  // --- Merges ---

  test('merges', () => {
    const merges = buf.getMerges();
    const expectedMerges = json.merges ?? [];
    expect(merges.length).toBe(expectedMerges.length);

    for (let i = 0; i < expectedMerges.length; i++) {
      const m = merges[i];
      const e = expectedMerges[i];
      expect(m.start_row).toBe(e.startRow);
      expect(m.start_col).toBe(e.startCol);
      expect(m.end_row).toBe(e.endRow);
      expect(m.end_col).toBe(e.endCol);
    }
  });

  // --- Row dimensions ---

  test('row dimensions', () => {
    const rowDims = buf.getRowDimensions();
    const expectedRowDims = json.rowDimensions ?? [];
    expect(rowDims.length).toBe(expectedRowDims.length);

    for (let i = 0; i < expectedRowDims.length; i++) {
      const d = rowDims[i];
      const e = expectedRowDims[i];
      expect(d.row).toBe(e.row);
      expect(d.height).toBeCloseTo(e.height, 5);
      expect(d.hidden).toBe(e.hidden);
    }
  });

  // --- Col dimensions ---

  test('col dimensions', () => {
    const colDims = buf.getColDimensions();
    const expectedColDims = json.colDimensions ?? [];
    expect(colDims.length).toBe(expectedColDims.length);

    for (let i = 0; i < expectedColDims.length; i++) {
      const d = colDims[i];
      const e = expectedColDims[i];
      expect(d.col).toBe(e.col);
      expect(d.width).toBeCloseTo(e.width, 5);
      expect(d.hidden).toBe(e.hidden);
    }
  });
});

// ==========================================================================
// Mutation roundtrip tests
// ==========================================================================

describe('Cross-language roundtrip: mutation', () => {
  const json = mutationFixture.json;
  let reader: BinaryMutationReader;

  beforeAll(() => {
    reader = new BinaryMutationReader(mutationFixture.bin);
  });

  // --- Header fields ---

  test('header: patchCount', () => {
    expect(reader.patchCount).toBe(json.patchCount);
  });

  test('header: generation', () => {
    expect(reader.generation).toBe(json.generation);
  });

  test('header: sheetId', () => {
    expect(reader.sheetId()).toBe(json.sheetId);
  });

  test('header: hasErrors', () => {
    expect(reader.hasErrors).toBe(json.hasErrors);
  });

  test('header: hasProjectionChanges', () => {
    expect(reader.hasProjectionChanges).toBe(json.hasProjectionChanges);
  });

  // --- Cell patches ---

  describe('cell patches', () => {
    test('patch count matches', () => {
      expect(reader.patchCount).toBe(json.patches.length);
    });

    for (let i = 0; i < json.patches.length; i++) {
      const patch = json.patches[i];
      const label = `patch[${i}] (${patch.row}, ${patch.col})`;

      describe(label, () => {
        test('row', () => {
          expect(reader.patchRow(i)).toBe(patch.row);
        });

        test('col', () => {
          expect(reader.patchCol(i)).toBe(patch.col);
        });

        test('displayText', () => {
          const expected = patch.display ?? null;
          expect(reader.patchDisplayText(i)).toBe(expected);
        });

        test('errorText', () => {
          const expected = patch.error ?? null;
          expect(reader.patchErrorText(i)).toBe(expected);
        });

        if (patch.numberValue !== undefined && patch.numberValue !== null) {
          test('numberValue', () => {
            expect(reader.patchNumberValue(i)).toBeCloseTo(patch.numberValue, 10);
          });
        }
      });
    }
  });

  // --- Spill patches ---

  describe('spill patches', () => {
    test('spillPatchCount', () => {
      expect(reader.spillPatchCount).toBe(json.spillPatchCount);
    });

    for (let i = 0; i < json.spillPatches.length; i++) {
      const spill = json.spillPatches[i];
      const label = `spillPatch[${i}] (${spill.row}, ${spill.col})`;

      describe(label, () => {
        test('row', () => {
          expect(reader.spillPatchRow(i)).toBe(spill.row);
        });

        test('col', () => {
          expect(reader.spillPatchCol(i)).toBe(spill.col);
        });

        test('displayText', () => {
          const expected = spill.display ?? null;
          expect(reader.spillPatchDisplayText(i)).toBe(expected);
        });
      });
    }
  });
});
