import { defineConfig } from 'tsup';

export default defineConfig({
  entry: { mog: 'src/mog.ts' },
  format: ['cjs'],
  target: 'node18',
  outDir: 'dist',
  tsconfig: 'tsconfig.json',
  dts: false,
  splitting: false,
  sourcemap: true,
  clean: true,
  shims: true,
  noExternal: [],
  external: [
    '@mog-sdk/node',
    '@mog-sdk/darwin-arm64',
    '@mog-sdk/darwin-x64',
    '@mog-sdk/linux-x64-gnu',
    '@mog-sdk/linux-x64-musl',
    '@mog-sdk/linux-arm64-gnu',
    '@mog-sdk/linux-arm64-musl',
    '@mog-sdk/win32-x64-msvc',
    'node:child_process',
    'node:crypto',
    'node:fs',
    'node:fs/promises',
    'node:net',
    'node:os',
    'node:path',
    'node:url',
  ],
});
