#!/usr/bin/env node
/**
 * Generate TSX React components from SVG source files and produce index.ts.
 *
 * Pipeline: .svg (checked in) → .tsx (generated, gitignored) → tsc → dist/
 *
 * Usage: node scripts/generate.mjs
 */

import { execSync } from 'child_process';
import { readdirSync, writeFileSync, statSync } from 'fs';
import { join } from 'path';

const SRC = new URL('../src', import.meta.url).pathname;

// ---------------------------------------------------------------------------
// Export name overrides: when the simple `PascalCase + Svg` convention doesn't
// match the existing public API. Keys are `category/SvgComponentName`.
// ---------------------------------------------------------------------------
const EXPORT_OVERRIDES = {
  'view/PageLayout': 'PageLayoutViewSvg',
  'layers/BringForward': 'BringForwardLayerSvg',
  'layers/BringToFront': 'BringToFrontLayerSvg',
  'layers/SendBackward': 'SendBackwardLayerSvg',
  'layers/SendToBack': 'SendToBackLayerSvg',
  'insert-illustrations/3DModels': 'Model3DSvg',
};

// Category display names for section headers in index.ts
const CATEGORY_LABELS = {
  'text-formatting': 'Text Formatting',
  alignment: 'Alignment',
  clipboard: 'Clipboard',
  borders: 'Borders',
  colors: 'Colors',
  navigation: 'Navigation',
  'file-operations': 'File Operations',
  'data-tables': 'Data & Tables',
  'sort-filter': 'Sort & Filter',
  formulas: 'Formulas',
  'view-zoom': 'View & Zoom',
  view: 'View (Window/Display Options)',
  charts: 'Charts',
  layers: 'Layers (Z-Order)',
  drawing: 'Drawing',
  shapes: 'Shapes',
  'insert-illustrations': 'Insert & Illustrations',
  comments: 'Comments',
  ui: 'UI Elements',
  misc: 'Misc',
};

// Ordered categories for index.ts (matches existing order)
const CATEGORY_ORDER = [
  'text-formatting',
  'alignment',
  'clipboard',
  'borders',
  'colors',
  'navigation',
  'file-operations',
  'data-tables',
  'sort-filter',
  'formulas',
  'view-zoom',
  'view',
  'charts',
  'layers',
  'drawing',
  'shapes',
  'insert-illustrations',
  'comments',
  'ui',
  'misc',
];

/**
 * Convert kebab-case SVG filename to PascalCase component name.
 * e.g. "align-bottom.svg" → "AlignBottom"
 *      "3d-models.svg"    → "3DModels"
 */
function svgToPascal(svgFilename) {
  const stem = svgFilename.replace(/\.svg$/, '');
  if (/^\d/.test(stem)) {
    const parts = stem.split('-');
    return (
      parts[0].toUpperCase() +
      parts
        .slice(1)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join('')
    );
  }
  return stem
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

// ---------------------------------------------------------------------------
// Step 1: Find all SVG categories (subdirectories of src/ that contain .svg)
// ---------------------------------------------------------------------------
const categories = readdirSync(SRC)
  .filter((d) => {
    const full = join(SRC, d);
    return statSync(full).isDirectory() && readdirSync(full).some((f) => f.endsWith('.svg'));
  })
  .sort();

// ---------------------------------------------------------------------------
// Step 2: Run svgr per category directory (one npx call per dir, not per file)
// ---------------------------------------------------------------------------
console.log('Generating TSX from SVG...');

for (const cat of categories) {
  const catDir = join(SRC, cat);
  execSync(
    `npx @svgr/cli --out-dir "${catDir}" --typescript --jsx-runtime automatic --no-dimensions --no-index "${catDir}"`,
    { encoding: 'utf8', stdio: 'pipe' },
  );
  console.log(`  ${cat}`);
}

// ---------------------------------------------------------------------------
// Step 3: Generate index.ts
// ---------------------------------------------------------------------------
console.log('Generating index.ts...');

const lines = [
  '// AUTO-GENERATED by scripts/generate.mjs — do not edit manually.',
  '// Source of truth: SVG files in src/*/',
  '',
  "export { ICON_SIZES, wrapIcon, wrapIconWithStyle, type IconSize } from './wrappers';",
  '',
];

const orderedCats = [
  ...CATEGORY_ORDER.filter((c) => categories.includes(c)),
  ...categories.filter((c) => !CATEGORY_ORDER.includes(c)),
];

for (const cat of orderedCats) {
  const label = CATEGORY_LABELS[cat] || cat;
  lines.push(`// ${'='.repeat(77)}`);
  lines.push(`// ${label}`);
  lines.push(`// ${'='.repeat(77)}`);
  lines.push('');

  const catDir = join(SRC, cat);
  const svgFiles = readdirSync(catDir)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  for (const svgFile of svgFiles) {
    const componentName = svgToPascal(svgFile);
    const key = `${cat}/${componentName}`;
    const exportName = EXPORT_OVERRIDES[key] || `${componentName}Svg`;
    lines.push(`export { default as ${exportName} } from './${cat}/${componentName}';`);
  }
  lines.push('');
}

writeFileSync(join(SRC, 'index.ts'), lines.join('\n'));

console.log(`Done. Generated components for ${categories.length} categories.`);
