import type { ApiCompatibilityEntry } from './types';
import { addressHelperCompatibilityRegistry } from './address-helper-registry';

const WORKBOOK_API_COMPATIBILITY_REPORT = 'api-compatibility:workbook-api-issues';
const VERSIONED_API_COMPATIBILITY_PLAN = 'api-compatibility:versioned-api-compatibility-layer';
const NAMESPACED_SUB_API_PLAN = 'api-compatibility:namespaced-sub-apis';
const WORKSHEET_METHOD_GUIDANCE = 'api-compatibility:mog-api/worksheet-method-guidance';

export const apiCompatibilityRegistry = [
  {
    id: 'mog-api.layout.office-column-selector.input-alias',
    observedPath: 'ws.layout.setColumnWidth("B", width)',
    canonicalPath: 'ws.layout.setColumnWidth',
    status: 'input_alias',
    appliesTo: 'argument',
    ownerTheme: 'api-compatibility/layout-column-addressing',
    ownerPackage: '@mog-sdk/kernel',
    firstObservedVersion: '0.10.4',
    canonicalSince: '0.10.5',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'trace',
        reference: 'https://github.com/fundamental-research-labs/mog/issues/326#issue-1',
      },
      {
        source: 'source',
        reference: 'api-compatibility:layout/office-style-column-selectors',
      },
    ],
    behavior:
      'Worksheet layout column inputs accept zero-based numeric indexes plus Excel/Office-style bare names and whole-column references such as B, $B, B:B, and B:D. Multi-column selectors expand only on mutation and batch APIs; scalar reads require exactly one column. Pixel-width methods remain pixels, and character-width methods remain explicit.',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'input_alias',
      kernel: 'input_alias',
      'api-describe': 'input_alias',
      'agent-guidance': 'input_alias',
      docs: 'input_alias',
      python: 'structured_diagnostic',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-layout-column-selectors address-resolver sdk-runtime-node',
      'pnpm --filter @mog/types-api typecheck',
      'pnpm --filter @mog-sdk/sdk test -- api-spec api-compatibility',
    ],
  },
  {
    id: 'mog-api.worksheet.describeRange.no-range',
    observedPath: 'ws.describeRange()',
    canonicalPath: 'ws.describeRange',
    status: 'contract_extension',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/worksheet-description',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: '0.9.0',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#wsdescriberange-with-no-range`,
      },
      {
        source: 'source',
        reference: 'api-compatibility:worksheet/describe-range-no-range',
      },
    ],
    behavior:
      'Calling describeRange with no range or undefined describes the used range with the same empty-sheet and large-sheet safeguards as describe(), while preserving includeStyle.',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'contract_extension',
      kernel: 'contract_extension',
      'api-describe': 'contract_extension',
      'agent-guidance': 'contract_extension',
      docs: 'contract_extension',
      python: 'structured_diagnostic',
      'api-eval': 'contract_extension',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-impl',
      'pnpm --filter @mog/types-api typecheck',
      'dev/api-eval/scenarios/api-compatibility/describe-range-no-arg.ts',
    ],
  },
  {
    id: 'mog-api.worksheet.getCharts.alias',
    observedPath: 'ws.getCharts',
    canonicalPath: 'ws.charts.list',
    status: 'supported_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/chart-api-discoverability',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: '0.9.0',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      { source: 'trace', reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#wsgetcharts` },
      {
        source: 'source',
        reference: 'api-compatibility:chart/imported-chart-api-discoverability',
      },
    ],
    behavior:
      'Worksheet.getCharts(options?) is a typed public alias for Worksheet.charts.list(options?) with identical ordering, materialization behavior, and returned Chart records.',
    runtimeSurfaces: [
      'typescript',
      'kernel',
      'executeCode-preflight',
      'api-describe',
      'agent-guidance',
      'docs',
      'api-eval',
    ],
    surfaceDisposition: {
      typescript: 'supported_alias',
      kernel: 'supported_alias',
      'executeCode-preflight': 'supported_alias',
      'api-describe': 'supported_alias',
      'agent-guidance': 'supported_alias',
      docs: 'supported_alias',
      python: 'structured_diagnostic',
      'api-eval': 'supported_alias',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-charts worksheet-impl',
      'pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe',
      'dev/api-eval/scenarios/api-compatibility/chart-learned-path.ts',
    ],
  },
  {
    id: 'mog-api.chart.imported-short-id.input-alias',
    observedPath: 'chart-import-N',
    canonicalPath: 'ws.charts.*(chartTarget)',
    status: 'input_alias',
    appliesTo: 'argument',
    ownerTheme: 'api-compatibility/chart-id-compatibility',
    ownerPackage: '@mog-sdk/kernel',
    firstObservedVersion: '0.8.1',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'prior_version',
        reference: 'api-compatibility:chart/imported-chart-id-alias-contract',
      },
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#describe--describerange-on-sheets-with-imported-charts`,
      },
    ],
    behavior:
      'Worksheet-scoped chart targets accept an exact stable ID or exact display name as a bare string. Explicit { id } and { name } selectors disambiguate collisions and duplicate names. ID selectors also resolve numeric imported aliases such as chart-import-0 to the current sheet-qualified canonical ID. Returned IDs and persisted state remain canonical.',
    runtimeSurfaces: ['typescript', 'kernel', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'input_alias',
      kernel: 'input_alias',
      'executeCode-preflight': 'input_alias',
      'api-describe': 'input_alias',
      'agent-guidance': 'input_alias',
      docs: 'input_alias',
      python: 'structured_diagnostic',
      'api-eval': 'input_alias',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-charts',
      'dev/api-eval/scenarios/charts/chart-imported-consistency.ts',
    ],
  },
  {
    id: 'mog-api.chart.not-found-guidance',
    observedPath: 'chartNotFound suggestion: getCharts()',
    canonicalPath: 'ws.charts.list',
    status: 'structured_diagnostic',
    appliesTo: 'result',
    ownerTheme: 'api-compatibility/chart-api-discoverability',
    ownerPackage: '@mog-sdk/kernel',
    firstObservedVersion: '0.9.0',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'source',
        reference: 'api-compatibility:chart/imported-chart-api-discoverability#stale-hint-surface',
      },
    ],
    behavior:
      'First-party chart-not-found hints must name ws.charts.list() and api.describe("ws.charts"), not the learned root alias.',
    runtimeSurfaces: ['kernel', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'Use ws.charts.list() or api.describe("ws.charts") to enumerate worksheet charts.',
      replacements: ['ws.charts.list', 'api.describe("ws.charts")'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- api-errors'],
  },
  {
    id: 'mog-api.pivot.handle.getInfo.contract-extension',
    observedPath: 'ws.pivots.get(...).getInfo',
    canonicalPath: 'type:PivotTableHandle.getInfo',
    status: 'contract_extension',
    appliesTo: 'handle',
    ownerTheme: 'api-compatibility/pivot-handle-introspection',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: '0.9.0',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#pivot-handle-introspection`,
      },
      {
        source: 'source',
        reference: 'api-compatibility:pivot/handle-introspection-gap',
      },
    ],
    behavior:
      'Pivot handles expose side-effect-free getInfo() bound to the pivot ID captured when the handle was created.',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'contract_extension',
      kernel: 'contract_extension',
      'executeCode-preflight': 'contract_extension',
      'api-describe': 'contract_extension',
      'agent-guidance': 'contract_extension',
      docs: 'contract_extension',
      python: 'structured_diagnostic',
      'api-eval': 'contract_extension',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-pivots',
      'pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe',
      'dev/api-eval/scenarios/pivots/pivot-get-info.ts',
    ],
  },
  {
    id: 'mog-api.pivot.handle.describe.unsupported',
    observedPath: 'ws.pivots.get(...).describe',
    canonicalPath: 'type:PivotTableHandle.getInfo',
    status: 'structured_diagnostic',
    appliesTo: 'handle',
    ownerTheme: 'api-compatibility/pivot-handle-introspection',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.0',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [{ source: 'source', reference: VERSIONED_API_COMPATIBILITY_PLAN }],
    behavior:
      'Handle describe() is intentionally not added in the pilot; agents should use handle.getInfo() for structured pivot introspection.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'Pivot handles do not expose describe(); use handle.getInfo() for structured pivot introspection.',
      replacements: ['type:PivotTableHandle.getInfo', 'ws.pivots.getInfo'],
    },
    verification: ['dev/api-eval/scenarios/api-compatibility/unsupported-learned-path.ts'],
  },
  {
    id: 'mog-api.pivot.collection.setItemVisibility.alias',
    observedPath: 'ws.pivots.setItemVisibility',
    canonicalPath: 'ws.pivots.setPivotItemVisibility',
    status: 'supported_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/pivot-item-visibility',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: '0.9.0',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      { source: 'trace', reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#setitemvisibility` },
      {
        source: 'source',
        reference: 'api-compatibility:pivot/set-item-visibility-contract',
      },
    ],
    behavior:
      'WorksheetPivots.setItemVisibility(name, fieldId, visibleItems) delegates to setPivotItemVisibility with identical filters, refresh policy, errors, and readbacks.',
    runtimeSurfaces: [
      'typescript',
      'kernel',
      'executeCode-preflight',
      'api-describe',
      'agent-guidance',
      'docs',
      'api-eval',
    ],
    surfaceDisposition: {
      typescript: 'supported_alias',
      kernel: 'supported_alias',
      'executeCode-preflight': 'supported_alias',
      'api-describe': 'supported_alias',
      'agent-guidance': 'supported_alias',
      docs: 'supported_alias',
      python: 'structured_diagnostic',
      'api-eval': 'supported_alias',
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-pivots',
      'dev/api-eval/scenarios/pivots/pivot-item-visibility.ts',
    ],
  },
  {
    id: 'mog-api.pivot.itemVisibility.blank-semantics',
    observedPath: 'handle.setItemVisibility(field, {"(blank)": false})',
    canonicalPath: 'type:PivotTableHandle.setItemVisibility',
    status: 'semantic_compatibility',
    appliesTo: 'argument',
    ownerTheme: 'api-compatibility/pivot-item-visibility',
    ownerPackage: '@mog-sdk/kernel',
    firstObservedVersion: '0.9.0',
    canonicalSince: '0.9.1',
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      { source: 'trace', reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#setitemvisibility` },
      {
        source: 'source',
        reference: 'api-compatibility:pivot/set-item-visibility-contract#likely-root-cause',
      },
    ],
    behavior:
      'Displayed blank pivot items round-trip to the canonical blank source key for Null, empty string, and whitespace-only strings without colliding with literal "(blank)" text.',
    runtimeSurfaces: ['typescript', 'kernel', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'semantic_compatibility',
      kernel: 'semantic_compatibility',
      'executeCode-preflight': 'semantic_compatibility',
      'api-describe': 'semantic_compatibility',
      'agent-guidance': 'semantic_compatibility',
      docs: 'semantic_compatibility',
      python: 'structured_diagnostic',
      'api-eval': 'semantic_compatibility',
    },
    verification: [
      'cargo test -p compute-pivot',
      'pnpm --filter @mog-sdk/kernel test -- worksheet-pivots',
      'dev/api-eval/scenarios/pivots/pivot-item-visibility.ts',
    ],
  },
  {
    id: 'mog-api.worksheet.getCellValue.unsupported',
    observedPath: 'ws.getCellValue',
    canonicalPath: 'ws.getValue',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'sdk-agent-guidance/worksheet-api-usage',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.2',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [{ source: 'source', reference: WORKSHEET_METHOD_GUIDANCE }],
    behavior:
      'Worksheet does not expose getCellValue(); use ws.getValue(address) for the computed value or (await ws.getCell(address)).value when full cell data is needed.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.getCellValue(address) is not a Mog worksheet method. Use await ws.getValue(address), or (await ws.getCell(address)).value when full cell data is needed.',
      replacements: ['ws.getValue', 'ws.getCell'],
    },
    verification: ['pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe'],
  },
  {
    id: 'mog-api.worksheet.rawCellData.unsupported',
    observedPath: 'ws.rawCellData',
    canonicalPath: 'ws.getRawCellData',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'sdk-agent-guidance/worksheet-api-usage',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.2',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [{ source: 'source', reference: WORKSHEET_METHOD_GUIDANCE }],
    behavior:
      'Worksheet raw cell data reads use ws.getRawCellData(address); there is no ws.rawCellData() shortcut.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.rawCellData(address) is not a Mog worksheet method. Use await ws.getRawCellData(address).',
      replacements: ['ws.getRawCellData'],
    },
    verification: ['pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe'],
  },
  {
    id: 'mog-api.worksheet.getFormat.unsupported',
    observedPath: 'ws.getFormat',
    canonicalPath: 'ws.formats.getDisplayedCellProperties',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'sdk-agent-guidance/worksheet-api-usage',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.2',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [{ source: 'source', reference: WORKSHEET_METHOD_GUIDANCE }],
    behavior:
      'Worksheet formatting reads are namespaced under ws.formats; use displayed properties for effective formatting or ws.formats.get() for explicit stored formatting.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.getFormat(address) is not a Mog worksheet method. Use ws.formats.getDisplayedCellProperties(address) for effective formatting, or ws.formats.get(address) for explicit stored formatting.',
      replacements: ['ws.formats.getDisplayedCellProperties', 'ws.formats.get'],
    },
    verification: ['pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe'],
  },
  {
    id: 'mog-api.validation.validationsAdd.unsupported',
    observedPath: 'ws.validations.add',
    canonicalPath: 'ws.validations.setList',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/validation-conditional-formatting-helpers',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.4',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'source',
        reference: 'api-compatibility:validation-conditional-formatting-helpers',
      },
    ],
    behavior:
      'Worksheet validation mutations are set-style operations. For list validation, agents should use the intent-level ws.validations.setList(range, source, options) helper; for advanced schemas, use ws.validations.set(range, rule).',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.validations.add(...) is not a Mog worksheet validation method. Use ws.validations.setList(range, source, options) for list validation, or ws.validations.set(range, rule) for an explicit validation rule.',
      replacements: ['ws.validations.setList', 'ws.validations.set'],
    },
    verification: ['pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe'],
  },
  {
    id: 'mog-api.validation.dataValidationAdd.unsupported',
    observedPath: 'ws.dataValidation.add',
    canonicalPath: 'ws.validations.setList',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/validation-conditional-formatting-helpers',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: '0.9.4',
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'source',
        reference: 'api-compatibility:validation-conditional-formatting-helpers',
      },
    ],
    behavior:
      'Mog exposes worksheet data validation under ws.validations, not ws.dataValidation. List validation should use ws.validations.setList(range, source, options).',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.dataValidation.add(...) is not a Mog worksheet method. Use ws.validations.setList(range, source, options) for list validation.',
      replacements: ['ws.validations.setList'],
    },
    verification: ['pnpm --filter @mog-sdk/sdk test -- agent-guidance api-describe'],
  },
  ...addressHelperCompatibilityRegistry,
  {
    id: 'mog-api.chart.root.listCharts.deprecated',
    observedPath: 'ws.listCharts',
    canonicalPath: 'ws.charts.list',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root chart listing alias delegates to ws.charts.list(options?).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.listCharts() is deprecated. Use ws.charts.list() for canonical chart listing.',
      replacements: ['ws.charts.list'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-charts worksheet-impl'],
  },
  {
    id: 'mog-api.chart.root.getChart.deprecated',
    observedPath: 'ws.getChart',
    canonicalPath: 'ws.charts.get',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root chart getter delegates to ws.charts.get(chartTarget).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.getChart(target) is deprecated. Use ws.charts.get(target).',
      replacements: ['ws.charts.get'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-charts worksheet-impl'],
  },
  {
    id: 'mog-api.chart.root.updateChart.deprecated',
    observedPath: 'ws.updateChart',
    canonicalPath: 'ws.charts.update',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root chart updater delegates to ws.charts.update(chartTarget, updates).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.updateChart(target, updates) is deprecated. Use ws.charts.update(target, updates).',
      replacements: ['ws.charts.update'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-charts worksheet-impl'],
  },
  {
    id: 'mog-api.chart.root.removeChart.deprecated',
    observedPath: 'ws.removeChart',
    canonicalPath: 'ws.charts.remove',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root chart remover delegates to ws.charts.remove(chartTarget).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.removeChart(target) is deprecated. Use ws.charts.remove(target).',
      replacements: ['ws.charts.remove'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-charts worksheet-impl'],
  },
  {
    id: 'mog-api.chart.root.addChart.unsupported',
    observedPath: 'ws.addChart',
    canonicalPath: 'ws.charts.add',
    status: 'structured_diagnostic',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior:
      'The old addChart return contract is not promoted as a hidden shim; learned calls are diagnosed to ws.charts.add(config).',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.addChart(config) is not part of the compatibility runtime. Use ws.charts.add(config).',
      replacements: ['ws.charts.add'],
    },
    verification: ['dev/api-eval/scenarios/api-compatibility/unsupported-learned-path.ts'],
  },
  {
    id: 'mog-api.chart.collection.listCharts.deprecated',
    observedPath: 'ws.charts.listCharts',
    canonicalPath: 'ws.charts.list',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/chart-api-discoverability',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.10.2',
    removeAfter: 'none',
    evidence: [
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#privateco-imported-chart-learned-paths`,
      },
    ],
    behavior: 'Deprecated chart collection listing alias delegates to ws.charts.list(options?).',
    runtimeSurfaces: [
      'typescript',
      'kernel',
      'executeCode-preflight',
      'agent-guidance',
      'docs',
      'api-eval',
    ],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'ws.charts.listCharts() is deprecated. Use ws.charts.list() for canonical chart listing.',
      replacements: ['ws.charts.list'],
    },
    verification: [
      'pnpm --filter @mog-sdk/kernel test -- worksheet-charts',
      'pnpm --filter @mog-sdk/sdk test -- agent-guidance',
      'dev/api-eval/scenarios/api-compatibility/pv23-imported-chart-learned-paths.ts',
    ],
  },
  {
    id: 'mog-api.chart.record.getAxisItem.unsupported',
    observedPath: 'chart.getAxisItem',
    canonicalPath: 'ws.charts.getAxisItem',
    status: 'structured_diagnostic',
    appliesTo: 'result',
    ownerTheme: 'api-compatibility/chart-api-discoverability',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#privateco-imported-chart-learned-paths`,
      },
    ],
    behavior:
      'Chart records returned by ws.charts.get/list are data records; use ws.charts.getAxisItem(chartTarget, ...) or ws.charts.setAxisTitle(chartTarget, ...) for axis reads and mutations. Targets accept exact IDs or names; use { id: chart.id } when selecting a known record.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'chart.getAxisItem(...) is a stale chart-record path. Use ws.charts.getAxisItem({ id: chart.id }, ...) or ws.charts.setAxisTitle({ id: chart.id }, axisRole, title).',
      replacements: ['ws.charts.getAxisItem', 'ws.charts.setAxisTitle', 'ws.charts.getAppModel'],
    },
    verification: [
      'pnpm --filter @mog-sdk/sdk test -- agent-guidance',
      'dev/api-eval/scenarios/api-compatibility/pv23-imported-chart-learned-paths.ts',
    ],
  },
  {
    id: 'mog-api.chart.record.updateRaw.unsupported',
    observedPath: 'chart.updateRaw',
    canonicalPath: 'ws.charts.update',
    status: 'structured_diagnostic',
    appliesTo: 'result',
    ownerTheme: 'api-compatibility/chart-api-discoverability',
    ownerPackage: '@mog-sdk/sdk',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: null,
    removeAfter: null,
    evidence: [
      {
        source: 'trace',
        reference: `${WORKBOOK_API_COMPATIBILITY_REPORT}#privateco-imported-chart-learned-paths`,
      },
    ],
    behavior:
      'Chart records returned by ws.charts.get/list are data records; chart mutations live on ws.charts and should use focused helpers instead of raw patching.',
    runtimeSurfaces: ['executeCode-preflight', 'agent-guidance', 'docs', 'api-eval'],
    surfaceDisposition: {
      typescript: 'structured_diagnostic',
      kernel: 'structured_diagnostic',
      'executeCode-preflight': 'structured_diagnostic',
      'api-describe': 'structured_diagnostic',
      'agent-guidance': 'structured_diagnostic',
      docs: 'structured_diagnostic',
      python: 'structured_diagnostic',
      'api-eval': 'structured_diagnostic',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message:
        'chart.updateRaw(...) is a stale chart-record path. Use focused helpers such as ws.charts.setLegendVisible(chart.id, visible), ws.charts.setChartTitleVisible(chart.id, visible), or ws.charts.switchSeriesOrientation(chart.id).',
      replacements: [
        'ws.charts.setLegendVisible',
        'ws.charts.setChartTitleVisible',
        'ws.charts.switchSeriesOrientation',
        'ws.charts.update',
      ],
    },
    verification: [
      'pnpm --filter @mog-sdk/sdk test -- agent-guidance',
      'dev/api-eval/scenarios/api-compatibility/pv23-imported-chart-learned-paths.ts',
    ],
  },
  {
    id: 'mog-api.pivot.root.addPivotTable.deprecated',
    observedPath: 'ws.addPivotTable',
    canonicalPath: 'ws.pivots.add',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root pivot creation alias delegates to ws.pivots.add(config).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.addPivotTable(config) is deprecated. Use ws.pivots.add(config).',
      replacements: ['ws.pivots.add'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-pivots worksheet-impl'],
  },
  {
    id: 'mog-api.pivot.root.removePivotTable.deprecated',
    observedPath: 'ws.removePivotTable',
    canonicalPath: 'ws.pivots.remove',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root pivot removal alias delegates to ws.pivots.remove(name).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.removePivotTable(name) is deprecated. Use ws.pivots.remove(name).',
      replacements: ['ws.pivots.remove'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-pivots worksheet-impl'],
  },
  {
    id: 'mog-api.pivot.root.listPivotTables.deprecated',
    observedPath: 'ws.listPivotTables',
    canonicalPath: 'ws.pivots.list',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root pivot listing alias delegates to ws.pivots.list().',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.listPivotTables() is deprecated. Use ws.pivots.list().',
      replacements: ['ws.pivots.list'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-pivots worksheet-impl'],
  },
  {
    id: 'mog-api.pivot.root.getPivotTable.deprecated',
    observedPath: 'ws.getPivotTable',
    canonicalPath: 'ws.pivots.get',
    status: 'deprecated_alias',
    appliesTo: 'method',
    ownerTheme: 'api-compatibility/namespaced-sub-apis',
    ownerPackage: '@mog-sdk/contracts',
    firstObservedVersion: null,
    canonicalSince: null,
    deprecatedSince: '0.9.1',
    removeAfter: 'none',
    evidence: [{ source: 'prior_version', reference: NAMESPACED_SUB_API_PLAN }],
    behavior: 'Deprecated root pivot getter alias delegates to ws.pivots.get(name).',
    runtimeSurfaces: ['typescript', 'kernel', 'api-describe', 'agent-guidance', 'docs'],
    surfaceDisposition: {
      typescript: 'deprecated_alias',
      kernel: 'deprecated_alias',
      'executeCode-preflight': 'deprecated_alias',
      'api-describe': 'deprecated_alias',
      'agent-guidance': 'deprecated_alias',
      docs: 'deprecated_alias',
      python: 'structured_diagnostic',
      'api-eval': 'deprecated_alias',
    },
    diagnostics: {
      code: 'MOG002_MOG_API_USAGE',
      message: 'ws.getPivotTable(name) is deprecated. Use ws.pivots.get(name).',
      replacements: ['ws.pivots.get'],
    },
    verification: ['pnpm --filter @mog-sdk/kernel test -- worksheet-pivots worksheet-impl'],
  },
] satisfies readonly ApiCompatibilityEntry[];
