import '@mog/app-spreadsheet/register';

import {
  MogSpreadsheetApp as RuntimeOwnedMogSpreadsheetApp,
  mountSpreadsheetApp as mountRuntimeOwnedSpreadsheetApp,
} from './app-attachment';

export { createSpreadsheetRuntime } from './runtime';
export type {
  AlreadyAttached,
  AttachFailed,
  DetachFailed,
  Disposed,
  HostCommandOwner,
  MogSpreadsheetAppProps,
  MogSpreadsheetAttachmentEvents,
  MogSpreadsheetColorScheme,
  MogSpreadsheetCommandBarPolicy,
  MogSpreadsheetChromePolicy,
  MogSpreadsheetCommandPolicy,
  MogSpreadsheetFeaturePolicy,
  MogSpreadsheetLifecycleEvents,
  MogSpreadsheetResolvedColorScheme,
  MogSpreadsheetThemeAxis,
  MogSpreadsheetThemePolicy,
  MogSpreadsheetWorkspacePolicy,
  CommandBarTabId,
  FormulaAIContextCell,
  FormulaAIContextCellValue,
  FormulaAIExplainContext,
  FormulaAIExplainRequest,
  FormulaAIExplainResult,
  FormulaAIExplainSource,
  FormulaAIRequestOptions,
  FormulaAIService,
  OpenWorkbookId,
  SemanticWorkbookId,
  StaleEpoch,
  SpreadsheetActorKind,
  SpreadsheetActorRef,
  SpreadsheetActorSession,
  SpreadsheetActiveSheetSnapshot,
  SpreadsheetAlreadyAttachedError,
  SpreadsheetAppAttachmentHandle,
  SpreadsheetAppError,
  SpreadsheetAppEvent,
  SpreadsheetAppEventBase,
  SpreadsheetAppHandle,
  SpreadsheetAppStatus,
  SpreadsheetAttachFailedError,
  SpreadsheetAttachmentState,
  SpreadsheetApprovalRequest,
  SpreadsheetApprovalResult,
  SpreadsheetAuthorizationResult,
  SpreadsheetCapability,
  SpreadsheetCapabilityContext,
  SpreadsheetCapabilityIntent,
  SpreadsheetCommandRequest,
  SpreadsheetCommandResult,
  SpreadsheetDecoration,
  SpreadsheetDecorationHandle,
  SpreadsheetDecorationSnapshot,
  SpreadsheetDetachFailedError,
  SpreadsheetDirtyState,
  SpreadsheetDocumentSource,
  SpreadsheetDisposedError,
  SpreadsheetEditLevel,
  SpreadsheetExportRequest,
  SpreadsheetFeatureGateCapabilities,
  SpreadsheetFeatureGateCapability,
  SpreadsheetFocusSnapshot,
  SpreadsheetHostAuthority,
  SpreadsheetLifecycleError,
  SpreadsheetLifecycleErrorKind,
  SpreadsheetMarkSavedInput,
  SpreadsheetOpenWorkbookRequest,
  SpreadsheetPersistenceMode,
  SpreadsheetPolicyDecision,
  SpreadsheetPolicySnapshot,
  SpreadsheetReadCapability,
  SpreadsheetResolvedActor,
  SpreadsheetResourceRef,
  SpreadsheetRuntime,
  SpreadsheetRuntimeAssetPolicy,
  SpreadsheetRuntimeHostPolicy,
  SpreadsheetRuntimeOptions,
  SpreadsheetRuntimeServices,
  SpreadsheetSaveRequest,
  SpreadsheetSaveResult,
  SpreadsheetSaveState,
  SpreadsheetScreenshotOptions,
  SpreadsheetSelectionSnapshot,
  SpreadsheetSlotContributions,
  SpreadsheetSlotHandle,
  SpreadsheetSlotName,
  SpreadsheetStaleEpochError,
  SpreadsheetBuiltInFeatureGateCapability,
  SpreadsheetVersionControlFeatureGateCapability,
  SpreadsheetViewHandle,
  SpreadsheetWorkbookFacade,
  SpreadsheetWorkbookHandle,
  SpreadsheetWorkbookSession,
  SpreadsheetWorkbookStatus,
  SpreadsheetWriteCapability,
  SpreadsheetWriteScope,
  WorkbookSessionId,
} from './public-types';

export const MogSpreadsheetApp = RuntimeOwnedMogSpreadsheetApp;
export const mountSpreadsheetApp = mountRuntimeOwnedSpreadsheetApp;
