// Generated by scripts/generate-workbook-facade-matrix.mjs from runtime/sdk/src/generated/api-spec.json.
// Keep this artifact checked in. The boundary check fails if any public Workbook
// or child-handle method is missing an explicit decision.
import type { SpreadsheetCapability } from './public-types';

export type SpreadsheetFacadeDecision = 'allow' | 'deny';

export interface SpreadsheetFacadeMatrixEntry {
  readonly decision: SpreadsheetFacadeDecision;
  readonly capability?: SpreadsheetCapability;
  readonly reason?: string;
  readonly returns?: readonly string[];
}

export const WORKBOOK_FACADE_GENERATED_FROM = 'runtime/sdk/src/generated/api-spec.json' as const;

export const WORKBOOK_SUB_API_INTERFACES = {
  wb: {
    sheets: 'WorkbookSheets',
    slicers: 'WorkbookSlicers',
    slicerStyles: 'WorkbookSlicerStyles',
    timelineStyles: 'WorkbookTimelineStyles',
    pivotTableStyles: 'WorkbookPivotTableStyles',
    functions: 'WorkbookFunctions',
    names: 'WorkbookNames',
    scenarios: 'WorkbookScenarios',
    history: 'WorkbookHistory',
    tableStyles: 'WorkbookTableStyles',
    cellStyles: 'WorkbookCellStyles',
    properties: 'WorkbookProperties',
    protection: 'WorkbookProtection',
    security: 'WorkbookSecurity',
    notifications: 'WorkbookNotifications',
    theme: 'WorkbookTheme',
    viewport: 'WorkbookViewport',
    changes: 'WorkbookChanges',
    diagnostics: 'WorkbookDiagnostics',
    links: 'WorkbookLinks',
  },
  ws: {
    cells: 'WorksheetCellsAccessor',
    whatIf: 'WorksheetWhatIf',
    diagrams: 'WorksheetDiagrams',
    changes: 'WorksheetChanges',
    formats: 'WorksheetFormats',
    layout: 'WorksheetLayout',
    view: 'WorksheetView',
    structure: 'WorksheetStructure',
    charts: 'WorksheetCharts',
    objects: 'WorksheetObjectCollection',
    shapes: 'WorksheetShapeCollection',
    pictures: 'WorksheetPictureCollection',
    textBoxes: 'WorksheetTextBoxCollection',
    drawings: 'WorksheetDrawingCollection',
    equations: 'WorksheetEquationCollection',
    textEffects: 'WorksheetTextEffectCollection',
    connectors: 'WorksheetConnectorCollection',
    filters: 'WorksheetFilters',
    formControls: 'WorksheetFormControls',
    conditionalFormats: 'WorksheetConditionalFormatting',
    validations: 'WorksheetValidation',
    tables: 'WorksheetTables',
    pivots: 'WorksheetPivots',
    slicers: 'WorksheetSlicers',
    sparklines: 'WorksheetSparklines',
    comments: 'WorksheetComments',
    customProperties: 'WorksheetCustomProperties',
    hyperlinks: 'WorksheetHyperlinks',
    outline: 'WorksheetOutline',
    protection: 'WorksheetProtection',
    print: 'WorksheetPrint',
    settings: 'WorksheetSettings',
    bindings: 'WorksheetBindings',
    names: 'WorksheetNames',
    styles: 'WorksheetStyles',
  },
} as const;

export const WORKBOOK_FACADE_CAPABILITY_MATRIX = {
  Workbook: {
    markClean: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    getSheet: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getSheetById: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    findSheet: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getSheetByIndex: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getOrCreateSheet: {
      decision: 'allow',
      capability: 'workbook:write',
      returns: ['Worksheet'],
    },
    getSheets: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getSheetCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSheetNames: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    undoGroup: {
      decision: 'allow',
      capability: 'workbook:undo-group',
    },
    batch: {
      decision: 'allow',
      capability: 'workbook:undo-group',
    },
    createCheckpoint: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    restoreCheckpoint: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    listCheckpoints: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    calculate: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCalculationMode: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCalculationMode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getIterativeCalculation: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getUsePrecisionAsDisplayed: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setUsePrecisionAsDisplayed: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    on: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    executeCode: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    getWorkbookSnapshot: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFunctionCatalog: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFunctionInfo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    describeRanges: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    toXlsx: {
      decision: 'allow',
      capability: 'workbook:export',
    },
    insertWorksheets: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    save: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    captureScreenshot: {
      decision: 'allow',
      capability: 'workbook:screenshot',
      returns: ['Worksheet'],
    },
    copyRangeFrom: {
      decision: 'allow',
      capability: 'workbook:write',
      returns: ['Worksheet'],
    },
    indexToAddress: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addressToIndex: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    union: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCultureInfo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDecimalSeparator: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getThousandsSeparator: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    searchAllSheets: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getChartDataPointTrack: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setChartDataPointTrack: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSettings: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSettings: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    replaceSettings: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCustomLists: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addCustomList: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updateCustomList: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteCustomList: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setCustomLists: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCustomSetting: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCustomSetting: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteCustomSetting: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    listCustomSettings: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCustomSettingCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    close: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    dispose: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    '[Symbol.asyncDispose]': {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    getActiveCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSelectedRanges: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSelectedRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getActiveChart: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getActiveShape: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getActiveSlicer: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setActivePrincipal: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    activePrincipal: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    securityActive: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    makePrincipal: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
  },
  Worksheet: {
    getName: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setName: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getIndex: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSheetId: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCell: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setDateValue: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setTimeValue: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRanges: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setArrayFormula: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearData: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearOrResetContents: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getControl: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setControl: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getValue: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    evaluate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    validateFormulaSyntax: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    validateFormulaCircularReference: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFormula: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFormulas: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFormulasR1C1: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFormulaArray: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRawCellData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRawRangeData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRangeWithIdentity: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    describe: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    describeRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    summarize: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getUsedRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCurrentRegion: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findDataEdge: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findLastRow: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findLastColumn: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findCells: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findByValue: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findByFormula: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    regexSearch: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    signCheck: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    findInRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    replaceAll: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getExtendedRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isEntireColumn: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isEntireRow: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getVisibleView: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSpecialCells: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getValueForEditing: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDisplayValue: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDisplayValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getValueTypes: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getNumberFormatCategories: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sortRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    sortByColor: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    autoFill: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    fillSeries: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    moveTo: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    copyFrom: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setCells: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    toCSV: {
      decision: 'allow',
      capability: 'workbook:export',
    },
    toJSON: {
      decision: 'allow',
      capability: 'workbook:export',
    },
    getDependents: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getPrecedents: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    enableCalculation: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    calculate: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSelectionAggregates: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    formatValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getVisibility: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setVisibility: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getNext: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getNextOrNull: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getPrevious: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    getPreviousOrNull: {
      decision: 'allow',
      capability: 'workbook:read',
      returns: ['Worksheet'],
    },
    on: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
    refreshActiveCellData: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    refreshActiveCellEditSource: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getActiveCellEditSource: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setBoundsReader: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookSheets: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
      returns: ['Worksheet'],
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    move: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    rename: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setActive: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    copy: {
      decision: 'allow',
      capability: 'workbook:write',
      returns: ['Worksheet'],
    },
    hide: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    show: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setSelectedIds: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    on: {
      decision: 'deny',
      reason: 'raw lifecycle, event, security, persistence, or code execution bypass',
    },
  },
  WorkbookSlicers: {
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemOrNullObject: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookSlicerStyles: {
    getDefault: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDefault: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookTimelineStyles: {
    getDefault: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDefault: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookPivotTableStyles: {
    getDefault: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDefault: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookFunctions: {
    invoke: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    vlookup: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sum: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    average: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    count: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    max: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    min: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    concatenate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookNames: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    createFromSelection: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getValue: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getType: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getArrayValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getArrayTypes: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getValueAsJson: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    recalculateDependents: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookScenarios: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getActiveScenarioId: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getActiveScenarioState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    apply: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    restore: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookHistory: {
    undo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    redo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canUndo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canRedo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    goToIndex: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    subscribe: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setNextDescription: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookTableStyles: {
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDefault: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDefault: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookCellStyles: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getStyle: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCatalog: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookProperties: {
    getDocumentProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDocumentProperties: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCustomProperty: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCustomProperty: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeCustomProperty: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    listCustomProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookProtection: {
    isProtected: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getOptions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    protect: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unprotect: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookSecurity: {
    addPolicy: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    removePolicy: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    updatePolicy: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    getPolicies: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    getEffectiveAccess: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    explainAccess: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    applyTemplate: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
    removeTemplate: {
      decision: 'allow',
      capability: 'workbook:policy-admin',
    },
  },
  WorkbookNotifications: {
    getAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    subscribe: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    notify: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    info: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    success: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    warning: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    error: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    dismiss: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    dismissAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookTheme: {
    getWorkbookTheme: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setWorkbookTheme: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getChromeTheme: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setChromeTheme: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookViewport: {
    createRegion: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resetSheetRegions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRenderScheduler: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    subscribe: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setShowFormulas: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorkbookChanges: {
    track: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookDiagnostics: {
    getFormulaReferences: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getResolvedChartSpec: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorkbookLinks: {
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    create: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    retarget: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    break: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    delete: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getStatus: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    refresh: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    refreshAll: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    watchStatus: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getUsages: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    copySource: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    listPackageDiagnostics: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetCellsAccessor: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetWhatIf: {
    goalSeek: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    dataTable: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    createDataTable: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetDiagrams: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addNode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeNode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updateNode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    moveNode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getNode: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDiagram: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDiagramsOnSheet: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    changeLayout: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    changeQuickStyle: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    changeColorTheme: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getComputedLayout: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    invalidateLayout: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    invalidateAllLayouts: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetChanges: {
    track: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetFormats: {
    set: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setRanges: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    hasExplicit: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clearCell: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearRanges: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDisplayedCellProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDisplayedRangeProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    adjustIndent: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clearFill: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearFillForRanges: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getNumberFormatCategory: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getNumberFormatLocal: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setNumberFormatLocal: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    applyPattern: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCellProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCellProperties: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getRowProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRowProperties: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getColumnProperties: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setColumnProperties: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetLayout: {
    getRowHeight: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRowHeight: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getColumnWidth: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setColumnWidth: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getColumnWidthChars: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setColumnWidthChars: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setColumnWidths: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setColumnWidthsChars: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    autoFitColumn: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    autoFitColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    autoFitRow: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    autoFitRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRowHeightsBatch: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColWidthsBatch: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColWidthsBatchChars: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRowVisible: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setColumnVisible: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    isRowHidden: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isColumnHidden: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unhideRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unhideColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    hideRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    hideColumns: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getHiddenRowsBitmap: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getHiddenColumnsBitmap: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    resetRowHeight: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    resetColumnWidth: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRowPosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColPosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRangePosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetView: {
    freezeRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    freezeColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    freezePanes: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unfreeze: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFrozenPanes: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    freezeAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSplitConfig: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSplitConfig: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setGridlines: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setHeadings: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getViewOptions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setShowFormulas: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getTabColor: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setTabColor: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getScrollPosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setScrollPosition: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetStructure: {
    insertRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    insertColumns: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteColumns: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    insertCellsWithShift: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteCellsWithShift: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getRowCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    textToColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    removeDuplicates: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    merge: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unmerge: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getMergedRegions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getMergeAtCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetCharts: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    exportImage: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDataRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setType: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getByName: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    bringToFront: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sendToBack: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    bringForward: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sendBackward: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    linkToTable: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unlinkFromTable: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isLinkedToTable: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addSeries: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeSeries: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSeries: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    updateSeries: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSeriesCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    reorderSeries: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSeriesValues: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setSeriesCategories: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSeriesBinOptions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSeriesBinOptions: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSeriesBoxwhiskerOptions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSeriesBoxwhiskerOptions: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    formatPoint: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setPointDataLabel: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addTrendline: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeTrendline: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getTrendline: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getTrendlineCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDataTable: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setBubbleSizes: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    onActivated: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    onDeactivated: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getAxisItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setAxisTitle: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setCategoryNames: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getSeriesDimensionValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSeriesDimensionDataSourceString: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSeriesDimensionDataSourceType: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDataLabelSubstring: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDataLabelHeight: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setDataLabelWidth: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDataLabelTailAnchor: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setTitleFormula: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getTitleSubstring: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    activate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetObjectCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getInfo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    removeMany: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    bringToFront: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sendToBack: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    bringForward: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    sendBackward: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    convertToTextEffect: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    convertToTextBox: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    computeObjectBounds: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    computeAllObjectBounds: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    group: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    ungroup: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetShapeCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetPictureCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetTextBoxCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetDrawingCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetEquationCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDefaultStyle: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDefaults: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetTextEffectCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDefaultConfig: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDefaults: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetConnectorCollection: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetFilters: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    applyAdvanced: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    byColor: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setAutoFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearAutoFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAutoFilter: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getForRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setColumnFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    applyDynamicFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearColumnFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getUniqueValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFilterDropdownData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setCriteria: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearCriteria: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearAllCriteria: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    apply: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getInfo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFilterUniqueValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isEnabled: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isDataFiltered: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    listDetails: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSortState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSortState: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetFormControls: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addCheckbox: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addComboBox: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getAtPosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    move: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resize: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetConditionalFormatting: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearRuleStyle: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    changeRuleType: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeRule: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearInRanges: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    reorder: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    cloneForPaste: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetValidation: {
    set: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    peek: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDropdownItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDropdownItemsWithRevision: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearInRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeById: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    validate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getErrorsInRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetTables: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFirst: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnByName: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    convertToRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    rename: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAtCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clearFilters: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setStylePreset: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resize: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    renameColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    toggleTotalsRow: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    toggleHeaderRow: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    applyAutoExpansion: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setCalculatedColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearCalculatedColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDataBodyRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getHeaderRowRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getTotalRowRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addRow: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteRow: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    deleteRowsAt: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getRowCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRowRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRowValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setRowValues: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getColumnDataBodyRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnHeaderRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnTotalRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnValues: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setColumnValues: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setHighlightFirstColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setHighlightLastColumn: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowBandedColumns: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowBandedRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowFilterButton: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowHeaders: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowTotals: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    applyIconFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAutoFilter: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetPivots: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addWithSheet: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    rename: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getInfo: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addPlacement: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updatePlacement: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removePlacement: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    movePlacement: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    renameValuePlacement: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setSortByValue: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    moveField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setAggregateFunction: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setShowValuesAs: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setSortOrder: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resetPlacement: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeFilter: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resetField: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setLayout: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setStyle: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    detectFields: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    compute: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    queryPivot: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    refresh: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    refreshAll: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDrillDownData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addCalculatedField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addCalculatedFieldAndPlace: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updateCalculatedField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeCalculatedField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDataBodyRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getColumnLabelRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRowLabelRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getFilterAxisRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getAllPivotItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setPivotItemVisibility: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    toggleExpanded: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setAllExpanded: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getExpansionState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getDataSourceType: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setDataSource: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAllowMultipleFiltersPerField: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setAllowMultipleFiltersPerField: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAutoFormat: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setAutoFormat: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getPreserveFormatting: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setPreserveFormatting: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getDataHierarchy: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getPivotItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getEnableMultipleFilterItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setEnableMultipleFilterItems: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetSlicers: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getByName: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItems: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItem: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getItemOrNullObject: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSelection: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearSelection: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    duplicate: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetSparklines: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addGroup: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getAtCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getGroup: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    listGroups: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updateGroup: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeGroup: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearInRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearAll: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addToGroup: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeFromGroup: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    ungroupAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getWithDataInRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetComments: {
    addNote: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setNote: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getNote: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    removeNote: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    noteCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    listNotes: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getNoteAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setNoteVisible: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setNoteHeight: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setNoteWidth: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    resolveThread: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getForCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    addReply: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    convertNoteToThread: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getThread: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getById: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getLocation: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getParentByReplyId: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getReplyCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getReplyAt: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getNoteLocation: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    hasComment: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    removeForCell: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clean: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetCustomProperties: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    set: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    delete: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    count: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetHyperlinks: {
    set: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetOutline: {
    groupRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    ungroupRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    groupColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    ungroupColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    toggleCollapsed: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    expandAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    collapseAll: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getState: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getLevel: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getMaxLevel: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    subtotal: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSettings: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSettings: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    showOutlineLevels: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetProtection: {
    isProtected: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    protect: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    protectWithOptions: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    unprotect: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canEditCell: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canEditCellFast: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canDoStructureOp: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    canSort: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getConfig: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getSelectionMode: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSelectionMode: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    pauseProtection: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    resumeProtection: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    checkPassword: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setPassword: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    updateOptions: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetPrint: {
    getSettings: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setSettings: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getArea: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setArea: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clearArea: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    addPageBreak: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removePageBreak: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getPageBreaks: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clearPageBreaks: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setPrintTitleRows: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setPrintTitleColumns: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getPrintTitleRows: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getPrintTitleColumns: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clearPrintTitles: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    setPrintMargins: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getCellAfterBreak: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getHeaderFooterImages: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setHeaderFooterImage: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    removeHeaderFooterImage: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetSettings: {
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    set: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getStandardHeight: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getStandardWidth: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    setStandardWidth: {
      decision: 'allow',
      capability: 'workbook:write',
    },
  },
  WorksheetBindings: {
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getProjectionRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getProjectionSource: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    isProjectedPosition: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getViewportProjectionData: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetNames: {
    add: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    has: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getCount: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    get: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    getRange: {
      decision: 'allow',
      capability: 'workbook:read',
    },
    remove: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    update: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    clear: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    list: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
  WorksheetStyles: {
    applyStyle: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    applyStyleToRange: {
      decision: 'allow',
      capability: 'workbook:write',
    },
    getStyle: {
      decision: 'allow',
      capability: 'workbook:read',
    },
  },
} as const satisfies Record<string, Record<string, SpreadsheetFacadeMatrixEntry>>;
