/**
 * 3D Bridge Type Mappers
 *
 * Converts bridge-generated types (PascalCase enum variants from Rust serde)
 * into the shared contract types (camelCase OOXML string literals).
 *
 * Bridge-ts codegen emits Rust enum variant names as-is (PascalCase), but
 * the TS contracts in @mog-sdk/contracts/drawing/three-d use
 * the original OOXML attribute string values (camelCase).
 *
 * @module @mog/drawing-canvas/bridges/three-d-bridge
 */

import type {
  Bevel,
  BevelPresetType,
  Camera,
  ColorRef,
  LightRig,
  LightRigDirection,
  LightRigType,
  PresetCameraType,
  PresetMaterialType,
  Rotation3D,
  Scene3D,
  Shape3D,
} from '@mog-sdk/contracts/drawing/three-d';

// =============================================================================
// Bridge Enum Types (PascalCase — as generated by bridge-ts from Rust)
// =============================================================================

/** Bridge-generated PresetCameraType (PascalCase variant names). */
type BridgePresetCameraType =
  | 'LegacyObliqueTopLeft'
  | 'LegacyObliqueTop'
  | 'LegacyObliqueTopRight'
  | 'LegacyObliqueFront'
  | 'LegacyObliqueLeft'
  | 'LegacyObliqueRight'
  | 'LegacyPerspectiveTopLeft'
  | 'LegacyPerspectiveTop'
  | 'LegacyPerspectiveTopRight'
  | 'LegacyPerspectiveFront'
  | 'LegacyPerspectiveLeft'
  | 'LegacyPerspectiveRight'
  | 'OrthographicFront'
  | 'IsometricTopUp'
  | 'IsometricTopDown'
  | 'IsometricBottomUp'
  | 'IsometricBottomDown'
  | 'IsometricLeftUp'
  | 'IsometricLeftDown'
  | 'IsometricRightUp'
  | 'IsometricRightDown'
  | 'IsometricOffAxis1Left'
  | 'IsometricOffAxis1Right'
  | 'IsometricOffAxis1Top'
  | 'IsometricOffAxis2Left'
  | 'IsometricOffAxis2Right'
  | 'IsometricOffAxis2Top'
  | 'IsometricOffAxis3Left'
  | 'IsometricOffAxis3Right'
  | 'IsometricOffAxis3Bottom'
  | 'IsometricOffAxis4Left'
  | 'IsometricOffAxis4Right'
  | 'IsometricOffAxis4Bottom'
  | 'ObliqueTopLeft'
  | 'ObliqueTop'
  | 'ObliqueTopRight'
  | 'ObliqueLeft'
  | 'ObliqueRight'
  | 'ObliqueBottomLeft'
  | 'ObliqueBottom'
  | 'ObliqueBottomRight'
  | 'PerspectiveFront'
  | 'PerspectiveLeft'
  | 'PerspectiveRight'
  | 'PerspectiveAbove'
  | 'PerspectiveAboveLeftFacing'
  | 'PerspectiveAboveRightFacing'
  | 'PerspectiveContrastingLeftFacing'
  | 'PerspectiveContrastingRightFacing'
  | 'PerspectiveHeroicLeftFacing'
  | 'PerspectiveHeroicRightFacing'
  | 'PerspectiveHeroicExtremeLeftFacing'
  | 'PerspectiveHeroicExtremeRightFacing'
  | 'PerspectiveBelow'
  | 'PerspectiveRelaxed'
  | 'PerspectiveRelaxedModerately';

/** Bridge-generated LightRigType (PascalCase variant names). */
type BridgeLightRigType =
  | 'Balanced'
  | 'BrightRoom'
  | 'Chilly'
  | 'Contrasting'
  | 'Flat'
  | 'Flood'
  | 'Freezing'
  | 'Glow'
  | 'Harsh'
  | 'LegacyFlat1'
  | 'LegacyFlat2'
  | 'LegacyFlat3'
  | 'LegacyFlat4'
  | 'LegacyHarsh1'
  | 'LegacyHarsh2'
  | 'LegacyHarsh3'
  | 'LegacyHarsh4'
  | 'LegacyNormal1'
  | 'LegacyNormal2'
  | 'LegacyNormal3'
  | 'LegacyNormal4'
  | 'Morning'
  | 'Soft'
  | 'Sunrise'
  | 'Sunset'
  | 'ThreePt'
  | 'TwoPt';

/** Bridge-generated LightRigDirection (PascalCase variant names). */
type BridgeLightRigDirection =
  | 'Top'
  | 'TopLeft'
  | 'TopRight'
  | 'Left'
  | 'Right'
  | 'Bottom'
  | 'BottomLeft'
  | 'BottomRight';

/** Bridge-generated BevelPresetType (PascalCase variant names). */
type BridgeBevelPresetType =
  | 'RelaxedInset'
  | 'Circle'
  | 'Slope'
  | 'Cross'
  | 'Angle'
  | 'SoftRound'
  | 'Convex'
  | 'CoolSlant'
  | 'Divot'
  | 'Riblet'
  | 'HardEdge'
  | 'ArtDeco';

/** Bridge-generated PresetMaterialType (PascalCase variant names). */
type BridgePresetMaterialType =
  | 'DkEdge'
  | 'Flat'
  | 'LegacyMatte'
  | 'LegacyMetal'
  | 'LegacyPlastic'
  | 'LegacyWireframe'
  | 'Matte'
  | 'Metal'
  | 'Plastic'
  | 'Powder'
  | 'SoftEdge'
  | 'SoftMetal'
  | 'TranslucentPowder'
  | 'WarmMatte';

/** Bridge-generated ColorRef (tagged union with PascalCase type discriminant). */
type BridgeColorRef =
  | { type: 'SchemeClr'; val: string }
  | { type: 'SrgbClr'; val: string }
  | { type: 'HslClr'; hue: number; sat: number; lum: number }
  | { type: 'SysClr'; val: string }
  | { type: 'PrstClr'; val: string };

/** Bridge-generated Rotation3D (snake_case fields — same as Rust). */
interface BridgeRotation3D {
  lat: number;
  lon: number;
  rev: number;
}

/** Bridge-generated Camera (snake_case fields). */
interface BridgeCamera {
  prst: BridgePresetCameraType;
  fov: number | null;
  rot: BridgeRotation3D | null;
}

/** Bridge-generated LightRig (snake_case fields). */
interface BridgeLightRig {
  rig: BridgeLightRigType;
  dir: BridgeLightRigDirection;
  rot: BridgeRotation3D | null;
}

/** Bridge-generated Scene3D (snake_case fields). */
interface BridgeScene3D {
  camera: BridgeCamera;
  light_rig: BridgeLightRig;
}

/** Bridge-generated Bevel (snake_case fields). */
interface BridgeBevel {
  w: number | null;
  h: number | null;
  prst: BridgeBevelPresetType | null;
}

/** Bridge-generated Shape3D (snake_case fields). */
interface BridgeShape3D {
  bevel_t: BridgeBevel | null;
  bevel_b: BridgeBevel | null;
  extrusion_h: number | null;
  extrusion_clr: BridgeColorRef | null;
  contour_w: number | null;
  contour_clr: BridgeColorRef | null;
  prst_material: BridgePresetMaterialType | null;
  z: number | null;
}

// =============================================================================
// Enum Mapping Tables
// =============================================================================

const PRESET_CAMERA_MAP: Record<BridgePresetCameraType, PresetCameraType> = {
  LegacyObliqueTopLeft: 'legacyObliqueTopLeft',
  LegacyObliqueTop: 'legacyObliqueTop',
  LegacyObliqueTopRight: 'legacyObliqueTopRight',
  LegacyObliqueFront: 'legacyObliqueFront',
  LegacyObliqueLeft: 'legacyObliqueLeft',
  LegacyObliqueRight: 'legacyObliqueRight',
  LegacyPerspectiveTopLeft: 'legacyPerspectiveTopLeft',
  LegacyPerspectiveTop: 'legacyPerspectiveTop',
  LegacyPerspectiveTopRight: 'legacyPerspectiveTopRight',
  LegacyPerspectiveFront: 'legacyPerspectiveFront',
  LegacyPerspectiveLeft: 'legacyPerspectiveLeft',
  LegacyPerspectiveRight: 'legacyPerspectiveRight',
  OrthographicFront: 'orthographicFront',
  IsometricTopUp: 'isometricTopUp',
  IsometricTopDown: 'isometricTopDown',
  IsometricBottomUp: 'isometricBottomUp',
  IsometricBottomDown: 'isometricBottomDown',
  IsometricLeftUp: 'isometricLeftUp',
  IsometricLeftDown: 'isometricLeftDown',
  IsometricRightUp: 'isometricRightUp',
  IsometricRightDown: 'isometricRightDown',
  IsometricOffAxis1Left: 'isometricOffAxis1Left',
  IsometricOffAxis1Right: 'isometricOffAxis1Right',
  IsometricOffAxis1Top: 'isometricOffAxis1Top',
  IsometricOffAxis2Left: 'isometricOffAxis2Left',
  IsometricOffAxis2Right: 'isometricOffAxis2Right',
  IsometricOffAxis2Top: 'isometricOffAxis2Top',
  IsometricOffAxis3Left: 'isometricOffAxis3Left',
  IsometricOffAxis3Right: 'isometricOffAxis3Right',
  IsometricOffAxis3Bottom: 'isometricOffAxis3Bottom',
  IsometricOffAxis4Left: 'isometricOffAxis4Left',
  IsometricOffAxis4Right: 'isometricOffAxis4Right',
  IsometricOffAxis4Bottom: 'isometricOffAxis4Bottom',
  ObliqueTopLeft: 'obliqueTopLeft',
  ObliqueTop: 'obliqueTop',
  ObliqueTopRight: 'obliqueTopRight',
  ObliqueLeft: 'obliqueLeft',
  ObliqueRight: 'obliqueRight',
  ObliqueBottomLeft: 'obliqueBottomLeft',
  ObliqueBottom: 'obliqueBottom',
  ObliqueBottomRight: 'obliqueBottomRight',
  PerspectiveFront: 'perspectiveFront',
  PerspectiveLeft: 'perspectiveLeft',
  PerspectiveRight: 'perspectiveRight',
  PerspectiveAbove: 'perspectiveAbove',
  PerspectiveAboveLeftFacing: 'perspectiveAboveLeftFacing',
  PerspectiveAboveRightFacing: 'perspectiveAboveRightFacing',
  PerspectiveContrastingLeftFacing: 'perspectiveContrastingLeftFacing',
  PerspectiveContrastingRightFacing: 'perspectiveContrastingRightFacing',
  PerspectiveHeroicLeftFacing: 'perspectiveHeroicLeftFacing',
  PerspectiveHeroicRightFacing: 'perspectiveHeroicRightFacing',
  PerspectiveHeroicExtremeLeftFacing: 'perspectiveHeroicExtremeLeftFacing',
  PerspectiveHeroicExtremeRightFacing: 'perspectiveHeroicExtremeRightFacing',
  PerspectiveBelow: 'perspectiveBelow',
  PerspectiveRelaxed: 'perspectiveRelaxed',
  PerspectiveRelaxedModerately: 'perspectiveRelaxedModerately',
};

const LIGHT_RIG_MAP: Record<BridgeLightRigType, LightRigType> = {
  Balanced: 'balanced',
  BrightRoom: 'brightRoom',
  Chilly: 'chilly',
  Contrasting: 'contrasting',
  Flat: 'flat',
  Flood: 'flood',
  Freezing: 'freezing',
  Glow: 'glow',
  Harsh: 'harsh',
  LegacyFlat1: 'legacyFlat1',
  LegacyFlat2: 'legacyFlat2',
  LegacyFlat3: 'legacyFlat3',
  LegacyFlat4: 'legacyFlat4',
  LegacyHarsh1: 'legacyHarsh1',
  LegacyHarsh2: 'legacyHarsh2',
  LegacyHarsh3: 'legacyHarsh3',
  LegacyHarsh4: 'legacyHarsh4',
  LegacyNormal1: 'legacyNormal1',
  LegacyNormal2: 'legacyNormal2',
  LegacyNormal3: 'legacyNormal3',
  LegacyNormal4: 'legacyNormal4',
  Morning: 'morning',
  Soft: 'soft',
  Sunrise: 'sunrise',
  Sunset: 'sunset',
  ThreePt: 'threePt',
  TwoPt: 'twoPt',
};

const LIGHT_RIG_DIR_MAP: Record<BridgeLightRigDirection, LightRigDirection> = {
  Top: 't',
  TopLeft: 'tl',
  TopRight: 'tr',
  Left: 'l',
  Right: 'r',
  Bottom: 'b',
  BottomLeft: 'bl',
  BottomRight: 'br',
};

const BEVEL_PRESET_MAP: Record<BridgeBevelPresetType, BevelPresetType> = {
  RelaxedInset: 'relaxedInset',
  Circle: 'circle',
  Slope: 'slope',
  Cross: 'cross',
  Angle: 'angle',
  SoftRound: 'softRound',
  Convex: 'convex',
  CoolSlant: 'coolSlant',
  Divot: 'divot',
  Riblet: 'riblet',
  HardEdge: 'hardEdge',
  ArtDeco: 'artDeco',
};

const MATERIAL_MAP: Record<BridgePresetMaterialType, PresetMaterialType> = {
  DkEdge: 'dkEdge',
  Flat: 'flat',
  LegacyMatte: 'legacyMatte',
  LegacyMetal: 'legacyMetal',
  LegacyPlastic: 'legacyPlastic',
  LegacyWireframe: 'legacyWireframe',
  Matte: 'matte',
  Metal: 'metal',
  Plastic: 'plastic',
  Powder: 'powder',
  SoftEdge: 'softEdge',
  SoftMetal: 'softmetal',
  TranslucentPowder: 'translucentPowder',
  WarmMatte: 'warmMatte',
};

// =============================================================================
// Mapper Functions
// =============================================================================

/** Map a bridge Rotation3D to a contract Rotation3D (field names are identical). */
function mapRotation3D(rot: BridgeRotation3D): Rotation3D {
  return { lat: rot.lat, lon: rot.lon, rev: rot.rev };
}

/** Map a bridge ColorRef (tagged union) to a contract ColorRef. */
function mapColorRef(clr: BridgeColorRef): ColorRef {
  switch (clr.type) {
    case 'SchemeClr':
      return { type: 'schemeClr', val: clr.val };
    case 'SrgbClr':
      return { type: 'srgbClr', val: clr.val };
    case 'HslClr':
      return { type: 'hslClr', val: '', hue: clr.hue, sat: clr.sat, lum: clr.lum };
    case 'SysClr':
      return { type: 'sysClr', val: clr.val };
    case 'PrstClr':
      return { type: 'prstClr', val: clr.val };
  }
}

/** Map a bridge Bevel to a contract Bevel. */
function mapBevel(bevel: BridgeBevel): Bevel {
  const result: Bevel = {};
  if (bevel.w !== null) result.w = bevel.w;
  if (bevel.h !== null) result.h = bevel.h;
  if (bevel.prst !== null) result.prst = BEVEL_PRESET_MAP[bevel.prst];
  return result;
}

/**
 * Map a bridge-generated Scene3D (PascalCase enums, snake_case fields)
 * to the shared contract Scene3D (camelCase OOXML strings, camelCase fields).
 */
export function mapBridgeScene3D(bridge: BridgeScene3D): Scene3D {
  const camera: Camera = {
    prst: PRESET_CAMERA_MAP[bridge.camera.prst],
  };
  if (bridge.camera.fov !== null) camera.fov = bridge.camera.fov;
  if (bridge.camera.rot !== null) camera.rot = mapRotation3D(bridge.camera.rot);

  const lightRig: LightRig = {
    rig: LIGHT_RIG_MAP[bridge.light_rig.rig],
    dir: LIGHT_RIG_DIR_MAP[bridge.light_rig.dir],
  };
  if (bridge.light_rig.rot !== null) lightRig.rot = mapRotation3D(bridge.light_rig.rot);

  return { camera, lightRig };
}

/**
 * Map a bridge-generated Shape3D (PascalCase enums, snake_case fields)
 * to the shared contract Shape3D (camelCase OOXML strings, camelCase fields).
 */
export function mapBridgeShape3D(bridge: BridgeShape3D): Shape3D {
  const result: Shape3D = {};

  if (bridge.bevel_t !== null) result.bevelT = mapBevel(bridge.bevel_t);
  if (bridge.bevel_b !== null) result.bevelB = mapBevel(bridge.bevel_b);
  if (bridge.extrusion_h !== null) result.extrusionH = bridge.extrusion_h;
  if (bridge.extrusion_clr !== null) result.extrusionClr = mapColorRef(bridge.extrusion_clr);
  if (bridge.contour_w !== null) result.contourW = bridge.contour_w;
  if (bridge.contour_clr !== null) result.contourClr = mapColorRef(bridge.contour_clr);
  if (bridge.prst_material !== null) result.prstMaterial = MATERIAL_MAP[bridge.prst_material];
  if (bridge.z !== null) result.z = bridge.z;

  return result;
}
