use serde::{Deserialize, Serialize};

// ===========================================================================
// SECTION: Shape Type Enum (OOXML preset geometries)
// ===========================================================================

/// All supported shape presets.
///
/// Variants serialize to camelCase strings matching the OOXML preset geometry
/// names used by the TypeScript layer.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum ShapeType {
    // ── Basic shapes ────────────────────────────────────────────────────
    Rect,
    RoundRect,
    Ellipse,
    Triangle,
    RtTriangle,
    Diamond,
    Pentagon,
    Hexagon,
    Octagon,
    Parallelogram,
    Trapezoid,
    NonIsoscelesTrapezoid,
    Heptagon,
    Decagon,
    Dodecagon,
    Teardrop,
    Pie,
    PieWedge,
    BlockArc,
    Donut,
    NoSmoking,
    Plaque,

    // ── Rectangle variants ──────────────────────────────────────────────
    Round1Rect,
    Round2SameRect,
    Round2DiagRect,
    Snip1Rect,
    Snip2SameRect,
    Snip2DiagRect,
    SnipRoundRect,

    // ── Arrows ──────────────────────────────────────────────────────────
    RightArrow,
    LeftArrow,
    UpArrow,
    DownArrow,
    LeftRightArrow,
    UpDownArrow,
    QuadArrow,
    Chevron,

    // ── Arrow Callouts ──────────────────────────────────────────────────
    LeftArrowCallout,
    RightArrowCallout,
    UpArrowCallout,
    DownArrowCallout,
    LeftRightArrowCallout,
    UpDownArrowCallout,
    QuadArrowCallout,

    // ── Curved / Special Arrows ─────────────────────────────────────────
    BentArrow,
    UturnArrow,
    CircularArrow,
    LeftCircularArrow,
    LeftRightCircularArrow,
    CurvedRightArrow,
    CurvedLeftArrow,
    CurvedUpArrow,
    CurvedDownArrow,
    SwooshArrow,

    // ── Stars and banners ───────────────────────────────────────────────
    Star4,
    Star5,
    Star6,
    Star7,
    Star8,
    Star10,
    Star12,
    Star16,
    Star24,
    Star32,
    Ribbon,
    Ribbon2,
    EllipseRibbon,
    EllipseRibbon2,
    LeftRightRibbon,
    Banner,

    // ── Callouts ────────────────────────────────────────────────────────
    WedgeRectCallout,
    WedgeRoundRectCallout,
    WedgeEllipseCallout,
    Cloud,
    Callout1,
    Callout2,
    Callout3,
    BorderCallout1,
    BorderCallout2,
    BorderCallout3,
    AccentCallout1,
    AccentCallout2,
    AccentCallout3,
    AccentBorderCallout1,
    AccentBorderCallout2,
    AccentBorderCallout3,

    // ── Lines and connectors ────────────────────────────────────────────
    Line,
    LineArrow,
    LineDoubleArrow,
    Curve,
    Arc,
    Connector,
    BentConnector2,
    BentConnector3,
    BentConnector4,
    BentConnector5,
    CurvedConnector2,
    CurvedConnector3,
    CurvedConnector4,
    CurvedConnector5,

    // ── Flowchart ───────────────────────────────────────────────────────
    FlowChartProcess,
    FlowChartDecision,
    FlowChartInputOutput,
    FlowChartPredefinedProcess,
    FlowChartInternalStorage,
    FlowChartDocument,
    FlowChartMultidocument,
    FlowChartTerminator,
    FlowChartPreparation,
    FlowChartManualInput,
    FlowChartManualOperation,
    FlowChartConnector,
    FlowChartPunchedCard,
    FlowChartPunchedTape,
    FlowChartSummingJunction,
    FlowChartOr,
    FlowChartCollate,
    FlowChartSort,
    FlowChartExtract,
    FlowChartMerge,
    FlowChartOfflineStorage,
    FlowChartOnlineStorage,
    FlowChartMagneticTape,
    FlowChartMagneticDisk,
    FlowChartMagneticDrum,
    FlowChartDisplay,
    FlowChartDelay,
    FlowChartAlternateProcess,
    FlowChartOffpageConnector,

    // ── Decorative symbols ──────────────────────────────────────────────
    Heart,
    LightningBolt,
    Sun,
    Moon,
    SmileyFace,
    FoldedCorner,
    Bevel,
    Frame,
    HalfFrame,
    Corner,
    DiagStripe,
    Chord,
    Can,
    Cube,
    Plus,
    Cross,
    IrregularSeal1,
    IrregularSeal2,
    HomePlate,
    Funnel,
    VerticalScroll,
    HorizontalScroll,

    // ── Action Buttons ──────────────────────────────────────────────────
    ActionButtonBlank,
    ActionButtonHome,
    ActionButtonHelp,
    ActionButtonInformation,
    ActionButtonForwardNext,
    ActionButtonBackPrevious,
    ActionButtonEnd,
    ActionButtonBeginning,
    ActionButtonReturn,
    ActionButtonDocument,
    ActionButtonSound,
    ActionButtonMovie,

    // ── Brackets and Braces ─────────────────────────────────────────────
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    BracketPair,
    BracePair,

    // ── Math shapes ─────────────────────────────────────────────────────
    MathPlus,
    MathMinus,
    MathMultiply,
    MathDivide,
    MathEqual,
    MathNotEqual,

    // ── Miscellaneous ───────────────────────────────────────────────────
    Gear6,
    Gear9,
    CornerTabs,
    SquareTabs,
    PlaqueTabs,
    ChartX,
    ChartStar,
    ChartPlus,
}
