//! Expected results recorded from Excel, rather than generated by the solver.

use super::super::FnRate;
use crate::PureFunction;
use value_types::{CellError, CellValue};

fn assert_rate(args: &[f64], expected: Option<f64>) {
    let args: Vec<_> = args.iter().copied().map(CellValue::number).collect();
    let actual = FnRate.call(&args);
    match expected {
        Some(expected) => match actual {
            CellValue::Number(value) => assert!(
                (value.get() - expected).abs() < 2e-14,
                "RATE{args:?}: expected {expected}, got {}",
                value.get()
            ),
            _ => panic!("RATE{args:?}: expected {expected}, got {actual:?}"),
        },
        None => assert!(
            matches!(actual, CellValue::Error(CellError::Num, _)),
            "RATE{args:?}: expected #NUM!, got {actual:?}"
        ),
    }
}

#[test]
fn zero_cash_flow_period_grid_matches_excel_numbers_and_errors() {
    let numeric = [
        (2, -0.99999988072370694),
        (3, -0.99999974478297993),
        (4, -0.99999959914231695),
        (5, -0.99999940914518248),
        (6, -0.9999993377532328),
        (7, -0.99999911486961435),
        (8, -0.99999900334535141),
        (9, -0.99999890950868897),
        (10, -0.99999874110137132),
        (16, -0.99985887613770819),
        (17, -0.99975698307779726),
        (18, -0.99960674644003267),
        (19, -0.99939592326836457),
        (20, -0.99911207191253926),
        (21, -0.99874300865843957),
        (22, -0.99827719470247378),
        (23, -0.99770403998497403),
        (24, -0.9970141220397587),
    ];
    for nper in 1..=120 {
        let expected = numeric.iter().find(|(n, _)| *n == nper).map(|(_, r)| *r);
        assert_rate(&[f64::from(nper), 0.0, -100.0], expected);
    }
}

#[test]
fn guesses_change_boundary_convergence_as_in_excel() {
    let cases = [
        (-0.9, -0.99999933172265532, Some(-0.99972708182165315)),
        (-0.5, -0.99999927033806513, Some(-0.99864187439962215)),
        (-0.1, -0.99999930224255829, Some(-0.99755670529424145)),
        (0.0, -0.99999931680943965, Some(-0.99728541361294942)),
        (0.01, -0.99999930998175623, Some(-0.99725828445129594)),
        (0.05, -0.99999928267102289, Some(-0.99714976781477305)),
        (0.1, -0.9999993377532328, Some(-0.9970141220397587)),
        (0.2, -0.99999927758281415, Some(-0.99674283054762669)),
        (0.5, -0.99999929875022242, None),
        (1.0, -0.99999927391726551, None),
        (2.0, -0.99999934314214056, None),
    ];
    for (guess, six, twenty_four) in cases {
        assert_rate(&[6.0, 0.0, -100.0, 0.0, 0.0, guess], Some(six));
        assert_rate(&[24.0, 0.0, -100.0, 0.0, 0.0, guess], twenty_four);
    }
    for guess in [-1.0, -2.0] {
        assert_rate(&[6.0, 0.0, -100.0, 0.0, 0.0, guess], None);
    }
}

#[test]
fn fractional_periods_probe_both_sides_of_excel_convergence_thresholds() {
    for (nper, expected) in [
        (0.5, None),
        (1.1, None),
        (15.4266820691593, None),
        (15.4267020691593, Some(-0.999899999376052)),
        (24.5519149978422, Some(-0.996580328499780)),
        (24.5519349978422, None),
    ] {
        assert_rate(&[nper, 0.0, -100.0], expected);
    }
    for (nper, guess, expected) in [
        (15.0, 0.2, None),
        (16.0, -0.1, Some(-0.999884520640691)),
        (15.0, 1.0, Some(-0.999861803358558)),
        (16.0, -0.5, None),
    ] {
        assert_rate(&[nper, 0.0, -100.0, 0.0, 0.0, guess], expected);
    }
}

#[test]
fn principal_sign_timing_and_signed_zero_preserve_excel_behavior() {
    for (pv, expected) in [(-100.0, -0.9999993377532328), (100.0, -0.999999338498713)] {
        for timing in [0.0, 1.0] {
            assert_rate(&[6.0, -0.0, pv, -0.0, timing], Some(expected));
        }
    }
    assert_rate(&[24.0, 0.0, 100.0], Some(-0.997017483748689));
}

#[test]
fn cash_flow_scale_and_underflow_match_excel() {
    for (pv, expected) in [
        (-1e-300, Some(-0.904345053273092)),
        (1e-300, Some(-0.904452730509239)),
        (-1.0, Some(-0.9999993377532328)),
        (-1e6, Some(-0.9999993377532328)),
        (-1e30, Some(-0.999999337753233)),
        (-1e31, Some(-0.999999546738359)),
        (-1e32, Some(-0.999999689774076)),
        (-1e34, Some(-0.999999854676341)),
        (-1e35, None),
        (-1e300, None),
        (1e300, None),
    ] {
        assert_rate(&[6.0, 0.0, pv], expected);
    }
}
