export const VERSION_DOMAIN_SUPPORT_MANIFEST_TEST_CREATED_AT = '2026-06-21T00:00:00.000Z';
export const VERSION_DOMAIN_SUPPORT_MANIFEST_TEST_NOW = new Date('2026-06-21T00:05:00.000Z');
export const VERSION_DOMAIN_SUPPORT_MANIFEST_TEST_ONE_MINUTE_MS = 60 * 1000;
export const VERSION_DOMAIN_SUPPORT_MANIFEST_TEST_TEN_MINUTES_MS =
  10 * VERSION_DOMAIN_SUPPORT_MANIFEST_TEST_ONE_MINUTE_MS;
export const VERSION_DOMAIN_DETECTOR_NOOP_SYNTHETIC_SHEET_ID = 'sheet-detector-noop';
