//! Emit TypeScript code from the parsed API representation.

use crate::types::*;

/// Collect all `TsType::Named` references from an API's method params and return types.
/// Filters out `"unknown"` (opaque JSON from `serde_json::Value`).
pub fn collect_named_from_api(api: &TsApi) -> std::collections::BTreeSet<String> {
    use std::collections::BTreeSet;
    let mut names = BTreeSet::new();
    for svc in &api.services {
        for method in &svc.methods {
            for param in &method.params {
                collect_named_from_type(&param.ts_type, &mut names);
            }
            collect_named_from_type(&method.return_type, &mut names);
        }
    }
    names.remove("unknown");
    names
}

/// Generate TypeScript source for a complete API.
pub fn emit_api(api: &TsApi, imports: Option<&ImportConfig>) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by bridge-ts. Do not edit.\n\n");
    out.push_str("import type { BridgeTransport } from '@rust-bridge/client';\n");

    if let Some(config) = imports {
        let referenced = collect_named_from_api(api);

        // Build lookup: local_name → true for all configured imports
        let mut configured: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for group in &config.groups {
            for ti in &group.types {
                configured.insert(ti.local_name.clone());
            }
        }

        // Validate: every referenced Named type must be in config
        for name in &referenced {
            if !configured.contains(name) {
                panic!(
                    "bridge-ts: type '{}' is referenced in the API but not mapped in ImportConfig. \
                     Add it to an ImportGroup.",
                    name
                );
            }
        }

        // Emit import lines — only include groups that have at least one referenced type
        for group in &config.groups {
            let used: Vec<&TypeImport> = group
                .types
                .iter()
                .filter(|ti| referenced.contains(&ti.local_name))
                .collect();
            if used.is_empty() {
                continue;
            }
            let specs: Vec<String> = used
                .iter()
                .map(|ti| match &ti.imported_name {
                    Some(imported) => format!("{} as {}", imported, ti.local_name),
                    None => ti.local_name.clone(),
                })
                .collect();
            out.push_str(&format!(
                "import type {{ {} }} from '{}';\n",
                specs.join(", "),
                group.from
            ));
        }
        out.push('\n');
    } else {
        out.push('\n'); // preserve existing blank line after BridgeTransport import
    }

    for (i, svc) in api.services.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&emit_service(svc));
    }

    out
}

/// Generate TypeScript for a single service/module.
pub fn emit_service(svc: &TsService) -> String {
    let mut out = String::new();

    let client_name = format!("{}Client", &svc.rust_name);
    let factory_name = format!("create{}", &client_name);
    let type_snake = to_snake_case(&svc.rust_name);

    // Compute effective prefix for command names
    let effective_prefix = match &svc.fn_prefix {
        Some(p) if !p.is_empty() => p.clone(),
        Some(_) => String::new(),   // explicit "" = no prefix
        None => type_snake.clone(), // default = type_snake
    };

    // --- Client factory function ---
    out.push_str(&format!(
        "export function {}(transport: BridgeTransport) {{\n",
        factory_name
    ));
    out.push_str("  return {\n");

    for method in &svc.methods {
        out.push_str(&emit_factory_method(svc, method, &effective_prefix));
    }

    // Auto-generate destroy for stateful services
    if let Some(key) = &svc.key {
        let camel_key = to_camel_case(&key.param_name);
        let destroy_cmd = if effective_prefix.is_empty() {
            "destroy".to_string()
        } else {
            format!("{}_destroy", effective_prefix)
        };
        out.push_str(&format!(
            "    destroy({camel_key}: string): Promise<void> {{\n"
        ));
        out.push_str(&format!(
            "      return transport.call('{destroy_cmd}', {{ {camel_key} }});\n",
        ));
        out.push_str("    },\n");
    }

    out.push_str("  } as const;\n");
    out.push_str("}\n\n");

    // --- Client interface ---
    out.push_str(&format!("export interface {} {{\n", client_name));

    for method in &svc.methods {
        out.push_str(&emit_interface_method(svc, method));
    }

    if let Some(key) = &svc.key {
        let camel_key = to_camel_case(&key.param_name);
        out.push_str(&format!("  destroy({camel_key}: string): Promise<void>;\n"));
    }

    out.push_str("}\n");

    out
}

/// Emit one method inside the factory's return object.
fn emit_factory_method(svc: &TsService, method: &TsMethod, effective_prefix: &str) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let command_name = if effective_prefix.is_empty() {
        method.rust_name.clone()
    } else {
        format!("{}_{}", effective_prefix, method.rust_name)
    };
    let return_ts = method.return_type.to_ts_string();

    // Build parameter list
    let mut params = Vec::new();

    // Key param comes first for stateful services (except lifecycle create — key is generated)
    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        params.push(format!("{}: string", camel_key));
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        params.push(format!("{}: {}", camel_p, p.ts_type.to_ts_string()));
    }

    let params_str = params.join(", ");

    // Build args object for transport.call (camelCase keys to match Tauri 2 convention)
    let mut args = Vec::new();

    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        // TS variable is already camelCase, so shorthand { docId } gives camelCase key
        args.push(camel_key);
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        // TS variable is already camelCase, so shorthand { sheetId } gives camelCase key
        args.push(camel_p);
    }

    let args_str = if args.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", args.join(", "))
    };

    format!(
        "    {camel_name}({params_str}): Promise<{return_ts}> {{\n      return transport.call('{command_name}', {args_str});\n    }},\n"
    )
}

/// Emit one method signature in the interface.
fn emit_interface_method(svc: &TsService, method: &TsMethod) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let return_ts = method.return_type.to_ts_string();

    let mut params = Vec::new();

    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        params.push(format!("{}: string", camel_key));
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        params.push(format!("{}: {}", camel_p, p.ts_type.to_ts_string()));
    }

    let params_str = params.join(", ");

    format!("  {camel_name}({params_str}): Promise<{return_ts}>;\n")
}

/// Convert `PascalCase` or `camelCase` to `snake_case`.
pub fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else {
            result.push(ch);
        }
    }
    result
}

/// Convert `snake_case` to `camelCase`.
///
/// Strips leading underscores (Rust's "unused" convention) so that
/// `_sheet_id` becomes `sheetId`, not `SheetId`.
pub fn to_camel_case(s: &str) -> String {
    let s = s.strip_prefix('_').unwrap_or(s);
    let mut result = String::new();
    let mut capitalize_next = false;
    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_uppercase().next().unwrap());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

// ─── Bridge Emitters ──────────────────────────────────────────────────────

/// Classification of how a bridge method should be wrapped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BridgePattern {
    /// `core.mutate(transport.call(...))` — binary tuple returns `[Uint8Array, MutationResult]`
    Mutate,
    /// `core.query(transport.call(...))` — read methods
    Query,
    /// `transport.call(...)` directly — no docId, no guard
    Pure,
    /// Don't generate (lifecycle, skip(ts_bridge))
    Skip,
}

/// Check if a return type is a binary mutation tuple like `[Uint8Array, MutationResult]`.
pub fn is_binary_mutation_return(ty: &TsType) -> bool {
    matches!(ty, TsType::Tuple(elems) if elems.len() == 2
        && elems[0] == TsType::Uint8Array
        && matches!(&elems[1], TsType::Named(n) if n == "MutationResult"))
}

/// Classify how a bridge method should be wrapped based on its access level and return type.
pub fn classify_bridge_pattern(method: &TsMethod) -> BridgePattern {
    if method.access == MethodAccess::LifecycleCreate {
        return BridgePattern::Skip;
    }
    if method.skip_platforms.iter().any(|p| p == "ts_bridge") {
        return BridgePattern::Skip;
    }
    match method.access {
        MethodAccess::Pure => BridgePattern::Pure,
        MethodAccess::Read => BridgePattern::Query,
        // `LifecycleSubscribe` travels over the wire identically to `Write` — the
        // distinction only matters for the kind manifest. Same return-type
        // dispatch as `Write`.
        MethodAccess::Write | MethodAccess::LifecycleSubscribe => {
            if is_binary_mutation_return(&method.return_type) {
                BridgePattern::Mutate
            } else {
                // Void, Boolean, Uint8Array, other Named types — use Query
                // which is generic and preserves the return type.
                BridgePattern::Query
            }
        }
        MethodAccess::LifecycleCreate => BridgePattern::Skip,
    }
}

/// Compute the bridge interface return type for a method.
///
/// For `Mutate` pattern, unwraps `[Uint8Array, T]` → `T` (the second tuple element).
/// For all other patterns, returns the type as-is.
fn bridge_return_type(method: &TsMethod, pattern: BridgePattern) -> String {
    match pattern {
        BridgePattern::Mutate => {
            if let TsType::Tuple(elems) = &method.return_type
                && elems.len() == 2
            {
                return elems[1].to_ts_string();
            }
            // Fallback (shouldn't happen if classify is correct)
            method.return_type.to_ts_string()
        }
        _ => method.return_type.to_ts_string(),
    }
}

/// Collect all `TsType::Named` references from bridge-eligible methods only.
/// Filters out `"unknown"` and skipped methods. For Mutate methods, collects
/// from the unwrapped return type (second tuple element) rather than the full tuple.
fn collect_named_from_bridge(api: &TsApi) -> std::collections::BTreeSet<String> {
    use std::collections::BTreeSet;
    let mut names = BTreeSet::new();
    for svc in &api.services {
        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            for param in &method.params {
                collect_named_from_type(&param.ts_type, &mut names);
            }
            match pattern {
                BridgePattern::Mutate => {
                    // Only collect from the unwrapped type (second tuple element)
                    if let TsType::Tuple(elems) = &method.return_type
                        && elems.len() == 2
                    {
                        collect_named_from_type(&elems[1], &mut names);
                    }
                }
                _ => {
                    collect_named_from_type(&method.return_type, &mut names);
                }
            }
        }
    }
    names.remove("unknown");
    names
}

/// Configuration for the bridge output.
#[derive(Debug, Clone)]
pub struct BridgeConfig {
    /// Import path for `ComputeCore`, e.g. `"./compute-core"`.
    pub core_import_path: String,
    /// The type name for the core object, e.g. `"ComputeCore"`.
    pub core_type_name: String,
    /// The interface name for generated methods, e.g. `"GeneratedBridgeMethods"`.
    pub interface_name: String,
    /// The class name for the generated bridge base, e.g. `"GeneratedBridgeBase"`.
    pub class_name: String,
}

impl Default for BridgeConfig {
    fn default() -> Self {
        Self {
            core_import_path: "./compute-core".into(),
            core_type_name: "ComputeCore".into(),
            interface_name: "GeneratedBridgeMethods".into(),
            class_name: "GeneratedBridgeBase".into(),
        }
    }
}

/// Generate TypeScript bridge code for a complete API.
///
/// Produces an interface (`GeneratedBridgeMethods`) and a base class
/// (`GeneratedBridgeBase`) that wraps transport calls with `core.mutate()`,
/// `core.query()`, or bare `transport.call()`.
pub fn emit_bridge(
    api: &TsApi,
    imports: Option<&ImportConfig>,
    bridge_config: Option<&BridgeConfig>,
) -> String {
    let config = bridge_config.cloned().unwrap_or_default();
    let mut out = String::new();

    out.push_str("// Auto-generated by bridge-ts. Do not edit.\n\n");
    out.push_str("import type { BridgeTransport } from '@rust-bridge/client';\n");
    out.push_str(&format!(
        "import type {{ {} }} from '{}';\n",
        config.core_type_name, config.core_import_path
    ));

    if let Some(import_config) = imports {
        let referenced = collect_named_from_bridge(api);

        let mut configured: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for group in &import_config.groups {
            for ti in &group.types {
                configured.insert(ti.local_name.clone());
            }
        }

        for name in &referenced {
            if !configured.contains(name) {
                panic!(
                    "bridge-ts: type '{}' is referenced in the bridge API but not mapped in ImportConfig. \
                     Add it to an ImportGroup.",
                    name
                );
            }
        }

        for group in &import_config.groups {
            let used: Vec<&TypeImport> = group
                .types
                .iter()
                .filter(|ti| referenced.contains(&ti.local_name))
                .collect();
            if used.is_empty() {
                continue;
            }
            let specs: Vec<String> = used
                .iter()
                .map(|ti| match &ti.imported_name {
                    Some(imported) => format!("{} as {}", imported, ti.local_name),
                    None => ti.local_name.clone(),
                })
                .collect();
            out.push_str(&format!(
                "import type {{ {} }} from '{}';\n",
                specs.join(", "),
                group.from
            ));
        }
    }

    out.push('\n');

    // --- Interface ---
    out.push_str("/**\n");
    out.push_str(" * Generated bridge methods.\n");
    out.push_str(
        " * Each method wraps transport.call() with the appropriate bridge scaffolding.\n",
    );
    out.push_str(" */\n");
    out.push_str(&format!("export interface {} {{\n", config.interface_name));

    for svc in &api.services {
        let effective_prefix = compute_effective_prefix(svc);
        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            out.push_str(&emit_bridge_interface_method(method, pattern));
        }
        let _ = effective_prefix; // used only in factory below
    }

    out.push_str("}\n\n");

    // --- Base class ---
    out.push_str(&format!(
        "export class {} implements {} {{\n",
        config.class_name, config.interface_name
    ));
    out.push_str(&format!("  readonly core: {};\n\n", config.core_type_name));
    out.push_str(&format!(
        "  constructor(core: {}) {{\n    this.core = core;\n  }}\n\n",
        config.core_type_name
    ));

    for svc in &api.services {
        let effective_prefix = compute_effective_prefix(svc);
        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            out.push_str(&emit_bridge_class_method(
                svc,
                method,
                &effective_prefix,
                pattern,
            ));
        }
    }

    out.push_str("}\n");

    out
}

/// Compute the effective command name prefix for a service.
fn compute_effective_prefix(svc: &TsService) -> String {
    match &svc.fn_prefix {
        Some(p) if !p.is_empty() => p.clone(),
        Some(_) => String::new(),
        None => to_snake_case(&svc.rust_name),
    }
}

/// Emit one method signature in the bridge interface (no key param).
fn emit_bridge_interface_method(method: &TsMethod, pattern: BridgePattern) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let return_ts = bridge_return_type(method, pattern);

    let params: Vec<String> = method
        .params
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                to_camel_case(&p.rust_name),
                p.ts_type.to_ts_string()
            )
        })
        .collect();

    let params_str = params.join(", ");

    format!("  {camel_name}({params_str}): Promise<{return_ts}>;\n")
}

/// Emit one method in the bridge base class.
pub fn emit_bridge_class_method(
    svc: &TsService,
    method: &TsMethod,
    effective_prefix: &str,
    pattern: BridgePattern,
) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let command_name = if effective_prefix.is_empty() {
        method.rust_name.clone()
    } else {
        format!("{}_{}", effective_prefix, method.rust_name)
    };

    // Build parameter list with types (no key param — bridge hides it)
    let params: Vec<String> = method
        .params
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                to_camel_case(&p.rust_name),
                p.ts_type.to_ts_string()
            )
        })
        .collect();
    let params_str = params.join(", ");

    // Return type: unwrapped for Mutate (core.mutate strips the Uint8Array), raw otherwise
    let return_ts = bridge_return_type(method, pattern);
    // Wire type for transport.call<T>: the actual Rust return type.
    // - Mutate: [Uint8Array, MutationResult] (raw binary tuple)
    // - Query/Pure: pass-through, <T> = return type
    let wire_type = method.return_type.to_ts_string();

    // Build args object — inject docId for non-pure methods
    let mut args = Vec::new();
    if pattern != BridgePattern::Pure
        && let Some(key) = &svc.key
    {
        let camel_key = to_camel_case(&key.param_name);
        args.push(format!("{}: this.core.{}", camel_key, camel_key));
    }
    for p in &method.params {
        args.push(to_camel_case(&p.rust_name));
    }

    let args_str = if args.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", args.join(", "))
    };

    let call_expr = format!("this.core.transport.call<{wire_type}>('{command_name}', {args_str})");

    let body = match pattern {
        BridgePattern::Mutate => format!("this.core.mutate({})", call_expr),
        BridgePattern::Query => format!("this.core.query({})", call_expr),
        BridgePattern::Pure => call_expr,
        BridgePattern::Skip => unreachable!(),
    };

    format!("  {camel_name}({params_str}): Promise<{return_ts}> {{\n    return {body};\n  }}\n\n")
}

// ─── Tauri Handler Registry ─────────────────────────────────────────────────

/// Configuration for Tauri handler registry generation.
pub struct HandlerRegistryConfig {
    /// Maps service `rust_name` → Rust module path relative to the crate root.
    /// e.g., `("ComputeService", "commands::compute")`.
    pub service_modules: Vec<(String, String)>,
    /// Additional hand-written command paths (e.g., `"commands::file::read_file"`).
    pub manual_commands: Vec<String>,
}

/// Collect Tauri command paths from a parsed bridge API.
///
/// For each non-skipped method, constructs `{module_path}::{prefix}_{method_name}`.
/// For stateful services, also adds the auto-generated `{prefix}_destroy` command.
pub fn collect_tauri_handler_names(api: &TsApi, config: &HandlerRegistryConfig) -> Vec<String> {
    let module_map: std::collections::HashMap<&str, &str> = config
        .service_modules
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();

    // Use BTreeSet for deterministic ordering and automatic deduplication.
    // Multiple services can map to the same module (e.g., YrsComputeEngine and
    // ComputeService both map to commands::compute), producing identical entries.
    let mut handlers = std::collections::BTreeSet::new();

    for svc in &api.services {
        let module_path = match module_map.get(svc.rust_name.as_str()) {
            Some(path) => *path,
            None => panic!(
                "No module mapping for service '{}'. Add it to HandlerRegistryConfig.service_modules.",
                svc.rust_name
            ),
        };

        let prefix = compute_effective_prefix(svc);

        for method in &svc.methods {
            // Skip methods not available in Tauri
            if method.skip_platforms.iter().any(|p| p == "tauri") {
                continue;
            }

            let command_name = if prefix.is_empty() {
                method.rust_name.clone()
            } else {
                format!("{}_{}", prefix, method.rust_name)
            };

            handlers.insert(format!("{}::{}", module_path, command_name));
        }

        // Auto-generated destroy for stateful services
        if svc.key.is_some() {
            let destroy_name = if prefix.is_empty() {
                "destroy".to_string()
            } else {
                format!("{}_destroy", prefix)
            };
            handlers.insert(format!("{}::{}", module_path, destroy_name));
        }
    }

    // Add manual (hand-written) commands
    for cmd in &config.manual_commands {
        handlers.insert(cmd.clone());
    }

    handlers.into_iter().collect()
}

/// Emit a `tauri::generate_handler![...]` expression for inclusion via `include!()`.
///
/// The generated file is designed to be used as:
/// ```rust,ignore
/// .invoke_handler(include!("handlers.gen.rs"))
/// ```
pub fn emit_handler_registry(handlers: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// DO NOT EDIT — generated by bridge-ts handler registry codegen.\n");
    out.push_str("// Regenerate: pnpm generate:bridge\n");
    out.push_str("//\n");
    out.push_str("// This file is included by lib.rs via include!() and contains a single\n");
    out.push_str("// expression: the tauri::generate_handler![...] invocation.\n\n");
    out.push_str("tauri::generate_handler![\n");
    for handler in handlers {
        out.push_str(&format!("    {},\n", handler));
    }
    out.push_str("]\n");
    out
}

/// Emit a `command-metadata.gen.ts` file with bytes-tuple, recalc, security,
/// and transport param metadata.
///
/// Iterates the parsed API and classifies each method:
/// - `BYTES_TUPLE_COMMANDS`: methods where `is_binary_mutation_return()` is true
/// - `RECALC_COMMANDS`: commands that trigger formula evaluation and need clock injection
/// - `BRIDGE_COMMAND_SECURITY_LEVELS`: security levels for bridge-generated commands
/// - `NAPI_SERDE_PARAM_INDICES`: param positions that the generated NAPI binding
///   receives as JSON strings because they are structured serde values.
pub fn emit_command_metadata(
    api: &TsApi,
    recalc_exclusions: &[&str],
    security_overrides: &[(&str, &str)],
) -> String {
    let mut bytes_tuple = Vec::new();
    let mut recalc = Vec::new();
    let mut napi_serde_params: Vec<(String, Vec<usize>)> = Vec::new();
    let recalc_exclude: std::collections::HashSet<&str> =
        recalc_exclusions.iter().copied().collect();
    let security_map: std::collections::HashMap<&str, &str> =
        security_overrides.iter().copied().collect();

    for svc in &api.services {
        let prefix = compute_effective_prefix(svc);

        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }

            let command_name = if prefix.is_empty() {
                method.rust_name.clone()
            } else {
                format!("{}_{}", prefix, method.rust_name)
            };

            let is_recalc_result = matches!(method.access, MethodAccess::Write)
                && matches!(&method.return_type, TsType::Named(name) if name == "RecalcResult");

            if pattern == BridgePattern::Mutate {
                bytes_tuple.push(command_name.clone());
            }
            if (pattern == BridgePattern::Mutate || is_recalc_result)
                && !recalc_exclude.contains(command_name.as_str())
            {
                recalc.push(command_name.clone());
            }

            let serde_indices: Vec<usize> = method
                .params
                .iter()
                .enumerate()
                .filter_map(|(idx, param)| {
                    if ts_param_needs_napi_json(param) {
                        Some(idx)
                    } else {
                        None
                    }
                })
                .collect();
            if !serde_indices.is_empty() {
                napi_serde_params.push((command_name, serde_indices));
            }
        }
    }

    bytes_tuple.sort();
    recalc.sort();
    napi_serde_params.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// DO NOT EDIT — generated by bridge-ts command metadata codegen.\n");
    out.push_str("// Regenerate: pnpm generate:bridge\n");
    out.push_str("//\n");
    out.push_str("// Source: #[bridge::api] annotations in compute-core and xlsx-api\n\n");

    // BYTES_TUPLE_COMMANDS
    out.push_str("/** Commands that return `[Uint8Array, MutationResult]` binary tuples. */\n");
    out.push_str("export const BYTES_TUPLE_COMMANDS = new Set([\n");
    for cmd in &bytes_tuple {
        out.push_str(&format!("  '{}',\n", cmd));
    }
    out.push_str("]);\n\n");

    // NAPI_SERDE_PARAM_INDICES
    out.push_str("/**\n");
    out.push_str(" * Positional params that must be JSON-stringified before calling NAPI.\n");
    out.push_str(" * NAPI generated wrappers receive structured serde params as strings,\n");
    out.push_str(" * while [bytes], [str], [parse], and primitive params are passed raw.\n");
    out.push_str(" */\n");
    out.push_str("export const NAPI_SERDE_PARAM_INDICES: Record<string, number[]> = {\n");
    for (cmd, indices) in &napi_serde_params {
        let rendered = indices
            .iter()
            .map(|idx| idx.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("  '{}': [{}],\n", cmd, rendered));
    }
    out.push_str("};\n\n");

    // RECALC_COMMANDS
    out.push_str(
        "/** Commands that trigger formula evaluation and therefore need clock injection. */\n",
    );
    out.push_str("export const RECALC_COMMANDS = new Set([\n");
    for cmd in &recalc {
        out.push_str(&format!("  '{}',\n", cmd));
    }
    out.push_str("]);\n\n");

    // BRIDGE_COMMAND_SECURITY_LEVELS
    out.push_str("/**\n");
    out.push_str(" * Security levels for bridge-generated commands.\n");
    out.push_str(
        " * Hand-written commands (credentials, file dialogs, etc.) are managed separately.\n",
    );
    out.push_str(" */\n");
    out.push_str("export const BRIDGE_COMMAND_SECURITY_LEVELS: Record<string, string> = {\n");
    let mut security_entries: Vec<(String, String)> = Vec::new();
    for svc in &api.services {
        let prefix = compute_effective_prefix(svc);
        let default_level = security_map
            .get(svc.rust_name.as_str())
            .unwrap_or(&"Public");

        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            let command_name = if prefix.is_empty() {
                method.rust_name.clone()
            } else {
                format!("{}_{}", prefix, method.rust_name)
            };
            security_entries.push((command_name, default_level.to_string()));
        }
    }
    security_entries.sort_by(|a, b| a.0.cmp(&b.0));
    for (cmd, level) in &security_entries {
        out.push_str(&format!("  '{}': '{}',\n", cmd, level));
    }
    out.push_str("};\n");

    out
}

fn ts_param_needs_napi_json(param: &TsParam) -> bool {
    if param.is_parse {
        return false;
    }
    match &param.ts_type {
        TsType::String | TsType::Number | TsType::Boolean | TsType::Uint8Array => false,
        TsType::Void => false,
        TsType::Nullable(_) | TsType::Array(_) | TsType::Tuple(_) | TsType::Named(_) => true,
        TsType::Record(_, _) => true,
    }
}

// ─── Bridge Method Kind Manifest ───────────────────────────────────────────

/// Map a `MethodAccess` to its TS-bridge "kind" string used in the kind manifest.
///
/// Returns `None` for accesses that don't appear on the generated bridge
/// interface (currently `LifecycleCreate`, which is skipped from emission).
pub fn method_access_to_kind(access: MethodAccess) -> Option<&'static str> {
    match access {
        MethodAccess::Pure => Some("read"),
        MethodAccess::Read => Some("read"),
        MethodAccess::Write => Some("write"),
        MethodAccess::LifecycleSubscribe => Some("lifecycle"),
        MethodAccess::LifecycleCreate => None,
    }
}

/// Emit a `manifest.gen.ts` file mapping each generated bridge method to its
/// kind tag (`'read' | 'write' | 'lifecycle'`).
///
/// Entries are emitted in the same declaration order as `compute-bridge.gen.ts`
/// (service iteration order, then method iteration order within each service)
/// so the two files diff together. Methods skipped from the bridge (lifecycle
/// constructors, `#[bridge::skip(ts_bridge)]`) are also skipped from the
/// manifest. Method names use the camelCase TS form, matching the bridge
/// interface.
pub fn emit_kind_manifest(api: &TsApi) -> String {
    let mut entries: Vec<(String, &'static str)> = Vec::new();
    for svc in &api.services {
        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            let kind = match method_access_to_kind(method.access) {
                Some(k) => k,
                None => continue,
            };
            let camel_name = to_camel_case(&method.rust_name);
            entries.push((camel_name, kind));
        }
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED FILE — DO NOT EDIT.\n");
    out.push_str("// Regenerate via: pnpm generate:bridge\n");
    out.push_str("//\n");
    out.push_str("// Source of truth: `MethodAccess` on each `#[bridge::*]` method\n");
    out.push_str("// in compute-core. Methods tagged `#[bridge::write(kind = \"subscribe\")]`\n");
    out.push_str("// are surfaced here as `'lifecycle'` (subscription register/unregister).\n\n");

    out.push_str("export type BridgeMethodKind = 'read' | 'write' | 'lifecycle';\n\n");

    out.push_str(
        "export const BRIDGE_METHOD_KIND: Readonly<Record<string, BridgeMethodKind>> = Object.freeze({\n",
    );
    for (name, kind) in &entries {
        out.push_str(&format!("  {}: '{}',\n", name, kind));
    }
    out.push_str("});\n");

    out
}

// ─── Type Definition Emitters ──────────────────────────────────────────────

/// Emit a single type definition to TypeScript.
pub fn emit_type_def(def: &TsTypeDef) -> String {
    match def {
        TsTypeDef::Interface(iface) => emit_interface(iface),
        TsTypeDef::StringUnion(union) => emit_string_union(union),
        TsTypeDef::TaggedUnion(union) => emit_tagged_union(union),
        TsTypeDef::TypeAlias { name, target } => emit_type_alias(name, target),
    }
}

/// Emit a `TsInterface` as a TypeScript `export interface`.
///
/// ```typescript
/// export interface ColWidth {
///   col: number;
///   width: number;
///   customWidth?: boolean;
///   hidden?: boolean;
/// }
/// ```
pub fn emit_interface(iface: &TsInterface) -> String {
    let mut out = String::new();
    out.push_str(&format!("export interface {} {{\n", iface.name));
    for field in &iface.fields {
        if field.optional {
            out.push_str(&format!(
                "  {}?: {};\n",
                field.ts_name,
                field.ts_type.to_ts_string()
            ));
        } else {
            out.push_str(&format!(
                "  {}: {};\n",
                field.ts_name,
                field.ts_type.to_ts_string()
            ));
        }
    }
    out.push_str("}\n");
    out
}

/// Emit a `TsStringUnion` as a TypeScript string union type.
///
/// ```typescript
/// export type Axis = "row" | "col";
/// ```
pub fn emit_string_union(union: &TsStringUnion) -> String {
    let variants: Vec<String> = union
        .variants
        .iter()
        .map(|v| format!("\"{}\"", v))
        .collect();
    format!("export type {} = {};\n", union.name, variants.join(" | "))
}

/// Emit a `TsTaggedUnion` as a TypeScript discriminated union.
///
/// Output varies by `TagStyle`:
/// - **External**: `{ VariantName: DataType }`
/// - **Adjacent**: `{ tag: "Variant"; content: DataType }` (unit variants omit content)
/// - **Internal**: `{ tag: "Variant" } & DataType` (unit variants are just the tag object)
/// - **Untagged**: `DataType1 | DataType2`
pub fn emit_tagged_union(union: &TsTaggedUnion) -> String {
    match &union.tag_style {
        TagStyle::External => emit_tagged_external(union),
        TagStyle::Adjacent { tag, content } => emit_tagged_adjacent(union, tag, content),
        TagStyle::Internal { tag } => emit_tagged_internal(union, tag),
        TagStyle::Untagged => emit_tagged_untagged(union),
    }
}

/// Emit a `TypeAlias` as a TypeScript type alias.
///
/// ```typescript
/// export type SheetId = string;
/// ```
pub fn emit_type_alias(name: &str, target: &TsType) -> String {
    format!("export type {} = {};\n", name, target.to_ts_string())
}

fn emit_tagged_external(union: &TsTaggedUnion) -> String {
    let mut out = format!("export type {} =\n", union.name);
    for (i, variant) in union.variants.iter().enumerate() {
        let data_str = if variant.data_type == TsType::Void {
            format!("{{ {}: null }}", variant.variant_name)
        } else {
            format!(
                "{{ {}: {} }}",
                variant.variant_name,
                variant.data_type.to_ts_string()
            )
        };
        if i < union.variants.len() - 1 {
            out.push_str(&format!("  | {}\n", data_str));
        } else {
            out.push_str(&format!("  | {};\n", data_str));
        }
    }
    out
}

fn emit_tagged_adjacent(union: &TsTaggedUnion, tag: &str, content: &str) -> String {
    let mut out = format!("export type {} =\n", union.name);
    for (i, variant) in union.variants.iter().enumerate() {
        let data_str = if variant.data_type == TsType::Void {
            format!("{{ {}: \"{}\" }}", tag, variant.variant_name)
        } else {
            format!(
                "{{ {}: \"{}\"; {}: {} }}",
                tag,
                variant.variant_name,
                content,
                variant.data_type.to_ts_string()
            )
        };
        if i < union.variants.len() - 1 {
            out.push_str(&format!("  | {}\n", data_str));
        } else {
            out.push_str(&format!("  | {};\n", data_str));
        }
    }
    out
}

fn emit_tagged_internal(union: &TsTaggedUnion, tag: &str) -> String {
    let mut out = format!("export type {} =\n", union.name);
    for (i, variant) in union.variants.iter().enumerate() {
        let data_str = if variant.data_type == TsType::Void {
            format!("{{ {}: \"{}\" }}", tag, variant.variant_name)
        } else {
            format!(
                "{{ {}: \"{}\" }} & {}",
                tag,
                variant.variant_name,
                variant.data_type.to_ts_string()
            )
        };
        if i < union.variants.len() - 1 {
            out.push_str(&format!("  | {}\n", data_str));
        } else {
            out.push_str(&format!("  | {};\n", data_str));
        }
    }
    out
}

fn emit_tagged_untagged(union: &TsTaggedUnion) -> String {
    let types: Vec<String> = union
        .variants
        .iter()
        .map(|v| v.data_type.to_ts_string())
        .collect();
    format!("export type {} = {};\n", union.name, types.join(" | "))
}

/// Emit multiple type definitions with a preamble header.
///
/// Type definitions are sorted alphabetically by name for deterministic output.
/// Named types that appear in field/variant types but are not defined in `defs`
/// are listed as external type comments in the preamble.
///
/// When `imports` is provided, external types that have a mapping in the
/// `ImportConfig` are emitted as `import type { ... } from '...'` statements.
/// Types mapped as `unknown` (built-in TS type) are not imported.
pub fn emit_type_defs(defs: &[TsTypeDef], imports: Option<&ImportConfig>) -> String {
    use std::collections::BTreeSet;

    let mut out = String::new();
    out.push_str("// Auto-generated by bridge-ts. Do not edit.\n");

    // Collect all defined type names
    let defined: BTreeSet<String> = defs.iter().map(|d| d.name().to_string()).collect();

    // Collect all Named() references from all type defs
    let mut referenced = BTreeSet::new();
    for def in defs {
        collect_named_types(def, &mut referenced);
    }

    // External types = referenced but not defined, excluding:
    // - "unknown" (built-in TS type)
    // - inline type literals from external_type_map (contain `{`, `[`, `<`, or spaces)
    let external: BTreeSet<&String> = referenced
        .difference(&defined)
        .filter(|name| {
            let s = name.as_str();
            s != "unknown"
                && !s.contains('{')
                && !s.contains('[')
                && !s.contains('<')
                && !s.contains(' ')
        })
        .collect();

    if let Some(config) = imports {
        if !external.is_empty() {
            // Build lookup: local_name → true for all configured imports
            let mut configured: BTreeSet<String> = BTreeSet::new();
            for group in &config.groups {
                for ti in &group.types {
                    configured.insert(ti.local_name.clone());
                }
            }

            // Validate: every external Named type must be in config
            for name in &external {
                if !configured.contains(*name) {
                    panic!(
                        "bridge-ts: type '{}' is referenced in type defs but not mapped in ImportConfig. \
                         Add it to an ImportGroup.",
                        name
                    );
                }
            }

            // Emit import lines — only include groups that have at least one referenced external type
            for group in &config.groups {
                let used: Vec<&TypeImport> = group
                    .types
                    .iter()
                    .filter(|ti| external.contains(&ti.local_name))
                    .collect();
                if used.is_empty() {
                    continue;
                }
                let specs: Vec<String> = used
                    .iter()
                    .map(|ti| match &ti.imported_name {
                        Some(imported) => format!("{} as {}", imported, ti.local_name),
                        None => ti.local_name.clone(),
                    })
                    .collect();
                out.push_str(&format!(
                    "import type {{ {} }} from '{}';\n",
                    specs.join(", "),
                    group.from
                ));
            }
        }
    } else {
        // No import config — emit external types as a comment (legacy behavior)
        if !external.is_empty() {
            out.push_str("// External types:");
            for name in &external {
                out.push_str(&format!(" {}", name));
            }
            out.push('\n');
        }
    }

    // Sort definitions alphabetically
    let mut sorted: Vec<&TsTypeDef> = defs.iter().collect();
    sorted.sort_by_key(|d| d.name());

    for def in sorted {
        out.push('\n');
        out.push_str(&emit_type_def(def));
    }

    out
}

/// Recursively collect all `TsType::Named` type names from a type definition.
fn collect_named_types(def: &TsTypeDef, names: &mut std::collections::BTreeSet<String>) {
    match def {
        TsTypeDef::Interface(iface) => {
            for field in &iface.fields {
                collect_named_from_type(&field.ts_type, names);
            }
        }
        TsTypeDef::StringUnion(_) => {}
        TsTypeDef::TaggedUnion(union) => {
            for variant in &union.variants {
                collect_named_from_type(&variant.data_type, names);
            }
        }
        TsTypeDef::TypeAlias { target, .. } => {
            collect_named_from_type(target, names);
        }
    }
}

/// Recursively collect `Named` types from a `TsType`.
fn collect_named_from_type(ty: &TsType, names: &mut std::collections::BTreeSet<String>) {
    match ty {
        TsType::Named(name) => {
            // Inline object literals (e.g. "{ row: number; col: number }") and
            // built-in TS types (e.g. "unknown") are not external imports.
            if !name.starts_with('{') && name != "unknown" {
                names.insert(name.clone());
            }
        }
        TsType::Array(inner) | TsType::Nullable(inner) => {
            collect_named_from_type(inner, names);
        }
        TsType::Record(k, v) => {
            collect_named_from_type(k, names);
            collect_named_from_type(v, names);
        }
        TsType::Tuple(elems) => {
            for e in elems {
                collect_named_from_type(e, names);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("KvStore"), "kv_store");
        assert_eq!(to_snake_case("KvUtils"), "kv_utils");
        assert_eq!(to_snake_case("MyEngine"), "my_engine");
    }

    #[test]
    fn camel_case_conversion() {
        assert_eq!(to_camel_case("store_id"), "storeId");
        assert_eq!(to_camel_case("validate_key"), "validateKey");
        assert_eq!(to_camel_case("hash_key"), "hashKey");
        assert_eq!(to_camel_case("key"), "key");
        assert_eq!(to_camel_case("get_by_id"), "getById");
        assert_eq!(to_camel_case("max_length"), "maxLength");
        assert_eq!(to_camel_case("list_keys"), "listKeys");
        // Leading underscore stripped (Rust's "unused" convention)
        assert_eq!(to_camel_case("_sheet_id"), "sheetId");
        assert_eq!(to_camel_case("_style_name"), "styleName");
    }

    fn make_kv_utils_api() -> TsApi {
        TsApi {
            services: vec![TsService {
                rust_name: "KvUtils".into(),
                key: None,
                fn_prefix: None,
                methods: vec![
                    TsMethod {
                        rust_name: "validate_key".into(),
                        access: MethodAccess::Pure,
                        params: vec![
                            TsParam {
                                rust_name: "key".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                            TsParam {
                                rust_name: "max_length".into(),
                                ts_type: TsType::Number,
                                is_parse: false,
                            },
                        ],
                        return_type: TsType::Void,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "hash_key".into(),
                        access: MethodAccess::Pure,
                        params: vec![TsParam {
                            rust_name: "key".into(),
                            ts_type: TsType::String,
                            is_parse: false,
                        }],
                        return_type: TsType::Number,
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "is_valid_json".into(),
                        access: MethodAccess::Pure,
                        params: vec![TsParam {
                            rust_name: "value".into(),
                            ts_type: TsType::String,
                            is_parse: false,
                        }],
                        return_type: TsType::Boolean,
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                ],
            }],
        }
    }

    #[test]
    fn emit_stateless_service() {
        let api = make_kv_utils_api();
        let ts = emit_api(&api, None);

        // Factory function
        assert!(ts.contains("export function createKvUtilsClient(transport: BridgeTransport)"));

        // Methods use camelCase
        assert!(ts.contains("validateKey(key: string, maxLength: number): Promise<void>"));
        assert!(ts.contains("hashKey(key: string): Promise<number>"));
        assert!(ts.contains("isValidJson(value: string): Promise<boolean>"));

        // Command names use snake_case
        assert!(ts.contains("'kv_utils_validate_key'"));
        assert!(ts.contains("'kv_utils_hash_key'"));
        assert!(ts.contains("'kv_utils_is_valid_json'"));

        // Interface
        assert!(ts.contains("export interface KvUtilsClient"));

        // No destroy for stateless
        assert!(!ts.contains("destroy"));
    }

    fn make_kv_store_api() -> TsApi {
        TsApi {
            services: vec![TsService {
                rust_name: "KvStore".into(),
                key: Some(ServiceKey {
                    param_name: "store_id".into(),
                }),
                fn_prefix: None,
                methods: vec![
                    TsMethod {
                        rust_name: "new".into(),
                        access: MethodAccess::LifecycleCreate,
                        params: vec![TsParam {
                            rust_name: "config".into(),
                            ts_type: TsType::Named("KvConfig".into()),
                            is_parse: false,
                        }],
                        return_type: TsType::Void,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "get".into(),
                        access: MethodAccess::Read,
                        params: vec![TsParam {
                            rust_name: "key".into(),
                            ts_type: TsType::String,
                            is_parse: false,
                        }],
                        return_type: TsType::String,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "set".into(),
                        access: MethodAccess::Write,
                        params: vec![
                            TsParam {
                                rust_name: "key".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                            TsParam {
                                rust_name: "value".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                        ],
                        return_type: TsType::Void,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "get_by_id".into(),
                        access: MethodAccess::Read,
                        params: vec![TsParam {
                            rust_name: "id".into(),
                            ts_type: TsType::String,
                            is_parse: true,
                        }],
                        return_type: TsType::String,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "list_keys".into(),
                        access: MethodAccess::Read,
                        params: vec![],
                        return_type: TsType::Array(Box::new(TsType::String)),
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "stats".into(),
                        access: MethodAccess::Read,
                        params: vec![],
                        return_type: TsType::Named("StoreStats".into()),
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                ],
            }],
        }
    }

    #[test]
    fn emit_stateful_service() {
        let api = make_kv_store_api();
        let ts = emit_api(&api, None);

        // Factory
        assert!(ts.contains("export function createKvStoreClient(transport: BridgeTransport)"));

        // Lifecycle create: key param comes first
        assert!(ts.contains("new(storeId: string, config: KvConfig): Promise<void>"));

        // Read method: key param first
        assert!(ts.contains("get(storeId: string, key: string): Promise<string>"));

        // Write method: key param first
        assert!(ts.contains("set(storeId: string, key: string, value: string): Promise<void>"));

        // Parse param: id is string on wire
        assert!(ts.contains("getById(storeId: string, id: string): Promise<string>"));

        // No-param methods still get key
        assert!(ts.contains("listKeys(storeId: string): Promise<string[]>"));

        // Auto-generated destroy
        assert!(ts.contains("destroy(storeId: string): Promise<void>"));
        assert!(ts.contains("'kv_store_destroy'"));

        // Interface
        assert!(ts.contains("export interface KvStoreClient"));
    }

    #[test]
    fn emit_command_names_use_snake() {
        let api = make_kv_store_api();
        let ts = emit_api(&api, None);

        assert!(ts.contains("'kv_store_new'"));
        assert!(ts.contains("'kv_store_get'"));
        assert!(ts.contains("'kv_store_set'"));
        assert!(ts.contains("'kv_store_get_by_id'"));
        assert!(ts.contains("'kv_store_list_keys'"));
        assert!(ts.contains("'kv_store_stats'"));
    }

    #[test]
    fn emit_args_object() {
        let api = make_kv_store_api();
        let ts = emit_api(&api, None);

        // Read method should pass camelCase keys
        assert!(ts.contains("{ storeId, key }"));

        // Empty params method should still pass camelCase key
        assert!(ts.contains("{ storeId }"));
    }

    #[test]
    fn emit_import_header() {
        let api = make_kv_utils_api();
        let ts = emit_api(&api, None);
        assert!(ts.contains("import type { BridgeTransport } from '@rust-bridge/client';"));
    }

    #[test]
    fn fn_prefix_overrides_command_names() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "YrsComputeEngine".into(),
                key: Some(ServiceKey {
                    param_name: "doc_id".into(),
                }),
                fn_prefix: Some("compute".into()),
                methods: vec![TsMethod {
                    rust_name: "set_cell".into(),
                    access: MethodAccess::Write,
                    params: vec![TsParam {
                        rust_name: "input".into(),
                        ts_type: TsType::String,
                        is_parse: false,
                    }],
                    return_type: TsType::Named("RecalcResult".into()),
                    is_fallible: true,
                    skip_platforms: vec![],
                }],
            }],
        };
        let ts = emit_api(&api, None);
        assert!(ts.contains("'compute_set_cell'"), "should use fn_prefix");
        assert!(
            !ts.contains("yrs_compute_engine"),
            "should NOT use type_snake"
        );
        assert!(
            ts.contains("'compute_destroy'"),
            "destroy should use fn_prefix too"
        );
    }

    #[test]
    fn fn_prefix_empty_gives_bare_method_name() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "PivotBridge".into(),
                key: None,
                fn_prefix: Some("".into()),
                methods: vec![TsMethod {
                    rust_name: "pivot_compute".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::Named("PivotResult".into()),
                    is_fallible: true,
                    skip_platforms: vec![],
                }],
            }],
        };
        let ts = emit_api(&api, None);
        assert!(
            ts.contains("'pivot_compute'"),
            "empty prefix = bare method name"
        );
        assert!(
            !ts.contains("pivot_bridge_"),
            "should NOT use type_snake prefix"
        );
    }

    #[test]
    fn fn_prefix_none_uses_type_snake_default() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "KvUtils".into(),
                key: None,
                fn_prefix: None,
                methods: vec![TsMethod {
                    rust_name: "hash_key".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::Number,
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let ts = emit_api(&api, None);
        assert!(
            ts.contains("'kv_utils_hash_key'"),
            "None = default type_snake"
        );
    }

    #[test]
    fn emit_interface_simple() {
        let iface = TsInterface {
            name: "ColWidth".into(),
            fields: vec![
                TsField {
                    ts_name: "col".into(),
                    ts_type: TsType::Number,
                    optional: false,
                },
                TsField {
                    ts_name: "width".into(),
                    ts_type: TsType::Number,
                    optional: false,
                },
                TsField {
                    ts_name: "customWidth".into(),
                    ts_type: TsType::Boolean,
                    optional: true,
                },
                TsField {
                    ts_name: "hidden".into(),
                    ts_type: TsType::Boolean,
                    optional: true,
                },
            ],
        };
        let ts = emit_interface(&iface);
        assert!(ts.contains("export interface ColWidth {"));
        assert!(ts.contains("  col: number;"));
        assert!(ts.contains("  width: number;"));
        assert!(ts.contains("  customWidth?: boolean;"));
        assert!(ts.contains("  hidden?: boolean;"));
        assert!(ts.ends_with("}\n"));
    }

    #[test]
    fn emit_string_union_basic() {
        let union = TsStringUnion {
            name: "Axis".into(),
            variants: vec!["row".into(), "col".into()],
        };
        let ts = emit_string_union(&union);
        assert_eq!(ts, "export type Axis = \"row\" | \"col\";\n");
    }

    #[test]
    fn emit_tagged_union_external() {
        let union = TsTaggedUnion {
            name: "IdentityFormulaRef".into(),
            tag_style: TagStyle::External,
            variants: vec![
                TsTaggedVariant {
                    variant_name: "Cell".into(),
                    data_type: TsType::Named("IdentityCellRef".into()),
                },
                TsTaggedVariant {
                    variant_name: "Range".into(),
                    data_type: TsType::Named("IdentityRangeRef".into()),
                },
            ],
        };
        let ts = emit_tagged_union(&union);
        assert!(ts.contains("export type IdentityFormulaRef =\n"));
        assert!(ts.contains("  | { Cell: IdentityCellRef }\n"));
        assert!(ts.contains("  | { Range: IdentityRangeRef };\n"));
    }

    #[test]
    fn emit_tagged_union_adjacent() {
        let union = TsTaggedUnion {
            name: "CellValue".into(),
            tag_style: TagStyle::Adjacent {
                tag: "type".into(),
                content: "value".into(),
            },
            variants: vec![
                TsTaggedVariant {
                    variant_name: "Number".into(),
                    data_type: TsType::Number,
                },
                TsTaggedVariant {
                    variant_name: "Text".into(),
                    data_type: TsType::String,
                },
                TsTaggedVariant {
                    variant_name: "Null".into(),
                    data_type: TsType::Void,
                },
            ],
        };
        let ts = emit_tagged_union(&union);
        assert!(ts.contains("export type CellValue =\n"));
        assert!(ts.contains("  | { type: \"Number\"; value: number }\n"));
        assert!(ts.contains("  | { type: \"Text\"; value: string }\n"));
        // Unit variant (Void) should omit the content field
        assert!(ts.contains("  | { type: \"Null\" };\n"));
        assert!(!ts.contains("\"Null\"; value"));
    }

    #[test]
    fn emit_tagged_union_adjacent_all_unit() {
        let union = TsTaggedUnion {
            name: "Direction".into(),
            tag_style: TagStyle::Adjacent {
                tag: "kind".into(),
                content: "data".into(),
            },
            variants: vec![
                TsTaggedVariant {
                    variant_name: "Up".into(),
                    data_type: TsType::Void,
                },
                TsTaggedVariant {
                    variant_name: "Down".into(),
                    data_type: TsType::Void,
                },
            ],
        };
        let ts = emit_tagged_union(&union);
        assert!(ts.contains("{ kind: \"Up\" }"));
        assert!(ts.contains("{ kind: \"Down\" }"));
        // No content field for any variant
        assert!(!ts.contains("data"));
    }

    #[test]
    fn emit_tagged_union_untagged() {
        let union = TsTaggedUnion {
            name: "Value".into(),
            tag_style: TagStyle::Untagged,
            variants: vec![
                TsTaggedVariant {
                    variant_name: "Num".into(),
                    data_type: TsType::Number,
                },
                TsTaggedVariant {
                    variant_name: "Str".into(),
                    data_type: TsType::String,
                },
                TsTaggedVariant {
                    variant_name: "Bool".into(),
                    data_type: TsType::Boolean,
                },
            ],
        };
        let ts = emit_tagged_union(&union);
        assert_eq!(ts, "export type Value = number | string | boolean;\n");
    }

    #[test]
    fn emit_type_defs_sorted() {
        let defs = vec![
            TsTypeDef::StringUnion(TsStringUnion {
                name: "Zebra".into(),
                variants: vec!["a".into()],
            }),
            TsTypeDef::StringUnion(TsStringUnion {
                name: "Alpha".into(),
                variants: vec!["x".into()],
            }),
        ];
        let ts = emit_type_defs(&defs, None);
        let alpha_pos = ts.find("Alpha").unwrap();
        let zebra_pos = ts.find("Zebra").unwrap();
        assert!(
            alpha_pos < zebra_pos,
            "Alpha should appear before Zebra (alphabetical order)"
        );
    }

    #[test]
    fn emit_type_defs_preamble() {
        let defs = vec![TsTypeDef::Interface(TsInterface {
            name: "Foo".into(),
            fields: vec![TsField {
                ts_name: "bar".into(),
                ts_type: TsType::Named("ExternalThing".into()),
                optional: false,
            }],
        })];
        let ts = emit_type_defs(&defs, None);
        assert!(ts.starts_with("// Auto-generated by bridge-ts. Do not edit.\n"));
        assert!(
            ts.contains("// External types: ExternalThing"),
            "should list external (undefined) Named types"
        );
        assert!(ts.contains("export interface Foo {"));
    }

    #[test]
    fn emit_type_defs_with_imports() {
        let defs = vec![TsTypeDef::Interface(TsInterface {
            name: "Foo".into(),
            fields: vec![
                TsField {
                    ts_name: "value".into(),
                    ts_type: TsType::Named("CellValue".into()),
                    optional: false,
                },
                TsField {
                    ts_name: "data".into(),
                    ts_type: TsType::Named("unknown".into()),
                    optional: true,
                },
            ],
        })];
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./bridge".into(),
                types: vec![TypeImport {
                    local_name: "CellValue".into(),
                    imported_name: Some("ExternalCellValue".into()),
                }],
            }],
        };
        let ts = emit_type_defs(&defs, Some(&config));
        assert!(
            ts.contains("import type { ExternalCellValue as CellValue } from './bridge';"),
            "should emit import statement for external types"
        );
        // unknown should NOT appear in imports
        assert!(
            !ts.contains("import type { unknown"),
            "unknown should not be imported"
        );
        // Should NOT have the comment-style external types
        assert!(
            !ts.contains("// External types:"),
            "should not have comment when imports are provided"
        );
    }

    #[test]
    #[should_panic(expected = "not mapped in ImportConfig")]
    fn emit_type_defs_panics_on_unmapped_type() {
        let defs = vec![TsTypeDef::Interface(TsInterface {
            name: "Foo".into(),
            fields: vec![TsField {
                ts_name: "bar".into(),
                ts_type: TsType::Named("ExternalThing".into()),
                optional: false,
            }],
        })];
        let config = ImportConfig { groups: vec![] };
        emit_type_defs(&defs, Some(&config)); // should panic
    }

    // ─── Import Config Tests ────────────────────────────────────────────────

    use crate::types::{ImportConfig, ImportGroup, TypeImport};

    #[test]
    fn emit_api_none_imports_unchanged() {
        // Backward compat: None imports produces same output as before
        let api = make_kv_utils_api();
        let ts = emit_api(&api, None);
        assert!(ts.contains("import type { BridgeTransport } from '@rust-bridge/client';"));
        assert!(ts.contains("export function createKvUtilsClient"));
        // Just verify it works and doesn't crash
        assert!(ts.contains("hashKey(key: string): Promise<number>"));
    }

    #[test]
    fn emit_api_with_imports() {
        let api = make_kv_store_api();
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./types".into(),
                types: vec![
                    TypeImport {
                        local_name: "StoreStats".into(),
                        imported_name: None,
                    },
                    TypeImport {
                        local_name: "KvConfig".into(),
                        imported_name: None,
                    },
                ],
            }],
        };
        let ts = emit_api(&api, Some(&config));
        assert!(ts.contains("import type { StoreStats, KvConfig } from './types';"));
    }

    #[test]
    fn emit_api_with_alias_imports() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "Foo".into(),
                key: None,
                fn_prefix: None,
                methods: vec![TsMethod {
                    rust_name: "get_value".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::Named("CellValue".into()),
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./bridge".into(),
                types: vec![TypeImport {
                    local_name: "CellValue".into(),
                    imported_name: Some("ExternalCellValue".into()),
                }],
            }],
        };
        let ts = emit_api(&api, Some(&config));
        assert!(ts.contains("import type { ExternalCellValue as CellValue } from './bridge';"));
    }

    #[test]
    #[should_panic(expected = "not mapped in ImportConfig")]
    fn emit_api_panics_on_unmapped_type() {
        let api = make_kv_store_api(); // references StoreStats and KvConfig
        let config = ImportConfig {
            groups: vec![], // empty = no mappings
        };
        emit_api(&api, Some(&config)); // should panic
    }

    #[test]
    fn emit_api_skips_unknown_type() {
        // "unknown" from serde_json::Value should not require an import mapping
        let api = TsApi {
            services: vec![TsService {
                rust_name: "JsonSvc".into(),
                key: None,
                fn_prefix: None,
                methods: vec![TsMethod {
                    rust_name: "get_raw".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::Named("unknown".into()),
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let config = ImportConfig { groups: vec![] };
        let ts = emit_api(&api, Some(&config)); // should NOT panic
        assert!(ts.contains("unknown")); // the type is still emitted
    }

    #[test]
    fn emit_api_unused_import_group_omitted() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "Foo".into(),
                key: None,
                fn_prefix: None,
                methods: vec![TsMethod {
                    rust_name: "bar".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::Void,
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./unused".into(),
                types: vec![TypeImport {
                    local_name: "Unused".into(),
                    imported_name: None,
                }],
            }],
        };
        let ts = emit_api(&api, Some(&config));
        // No methods reference "Unused", so the import line should be omitted
        assert!(!ts.contains("./unused"));
    }

    #[test]
    fn collect_named_from_api_basic() {
        let api = make_kv_store_api();
        let names = collect_named_from_api(&api);
        assert!(names.contains("StoreStats"));
        assert!(names.contains("KvConfig"));
        assert!(!names.contains("unknown")); // filtered
    }

    #[test]
    fn emit_type_alias_string() {
        let ts = emit_type_alias("SheetId", &TsType::String);
        assert_eq!(ts, "export type SheetId = string;\n");
    }

    #[test]
    fn emit_type_alias_number() {
        let ts = emit_type_alias("Score", &TsType::Number);
        assert_eq!(ts, "export type Score = number;\n");
    }

    #[test]
    fn emit_type_def_type_alias() {
        let def = TsTypeDef::TypeAlias {
            name: "CellId".into(),
            target: TsType::String,
        };
        let ts = emit_type_def(&def);
        assert_eq!(ts, "export type CellId = string;\n");
    }

    // ─── Bridge Emitter Tests ─────────────────────────────────────────────

    #[test]
    fn classify_pure_method() {
        let method = TsMethod {
            rust_name: "validate".into(),
            access: MethodAccess::Pure,
            params: vec![],
            return_type: TsType::Boolean,
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Pure);
    }

    #[test]
    fn classify_read_method() {
        let method = TsMethod {
            rust_name: "get_settings".into(),
            access: MethodAccess::Read,
            params: vec![],
            return_type: TsType::Named("Settings".into()),
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Query);
    }

    #[test]
    fn classify_write_with_binary_mutation() {
        let method = TsMethod {
            rust_name: "set_cell".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Tuple(vec![
                TsType::Uint8Array,
                TsType::Named("MutationResult".into()),
            ]),
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Mutate);
    }

    #[test]
    fn classify_write_without_binary_tuple_uses_query() {
        // Write methods returning bare MutationResult (not wrapped in a binary tuple)
        // are classified as Query. All write methods should return (Vec<u8>, MutationResult)
        // tuples; bare MutationResult on a write is a legacy pattern that gets Query treatment.
        let method = TsMethod {
            rust_name: "set_name".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Named("MutationResult".into()),
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Query);
    }

    #[test]
    fn classify_write_void_return() {
        let method = TsMethod {
            rust_name: "clear".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Void,
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Query);
    }

    #[test]
    fn classify_write_non_mutation_result_uses_query() {
        // Write methods that return a concrete type other than MutationResult
        // (e.g. IdentityFormula, Uint8Array) should use Query to preserve the type.
        let method = TsMethod {
            rust_name: "to_identity_formula".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Named("IdentityFormula".into()),
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Query);
    }

    #[test]
    fn classify_write_uint8array_return_uses_query() {
        // Write methods returning Uint8Array (e.g. get_viewport_binary) should use Query.
        let method = TsMethod {
            rust_name: "get_viewport_binary".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Uint8Array,
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Query);
    }

    #[test]
    fn classify_lifecycle_create_skipped() {
        let method = TsMethod {
            rust_name: "new".into(),
            access: MethodAccess::LifecycleCreate,
            params: vec![],
            return_type: TsType::Void,
            is_fallible: false,
            skip_platforms: vec![],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Skip);
    }

    #[test]
    fn classify_skip_ts_bridge() {
        let method = TsMethod {
            rust_name: "internal_op".into(),
            access: MethodAccess::Write,
            params: vec![],
            return_type: TsType::Void,
            is_fallible: false,
            skip_platforms: vec!["ts_bridge".into()],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Skip);
    }

    #[test]
    fn classify_skip_ts_bridge_among_others() {
        let method = TsMethod {
            rust_name: "internal_op".into(),
            access: MethodAccess::Read,
            params: vec![],
            return_type: TsType::String,
            is_fallible: false,
            skip_platforms: vec!["wasm".into(), "ts_bridge".into()],
        };
        assert_eq!(classify_bridge_pattern(&method), BridgePattern::Skip);
    }

    #[test]
    fn is_binary_mutation_return_true_mutation_result() {
        let ty = TsType::Tuple(vec![
            TsType::Uint8Array,
            TsType::Named("MutationResult".into()),
        ]);
        assert!(is_binary_mutation_return(&ty));
    }

    #[test]
    fn is_binary_mutation_return_false_mutation_metadata() {
        // MutationMetadata has been removed; only MutationResult is recognized.
        let ty = TsType::Tuple(vec![
            TsType::Uint8Array,
            TsType::Named("MutationMetadata".into()),
        ]);
        assert!(!is_binary_mutation_return(&ty));
    }

    #[test]
    fn is_binary_mutation_return_false_wrong_second() {
        let ty = TsType::Tuple(vec![TsType::Uint8Array, TsType::Named("OtherType".into())]);
        assert!(!is_binary_mutation_return(&ty));
    }

    #[test]
    fn is_binary_mutation_return_false_wrong_first() {
        let ty = TsType::Tuple(vec![TsType::String, TsType::Named("MutationResult".into())]);
        assert!(!is_binary_mutation_return(&ty));
    }

    #[test]
    fn is_binary_mutation_return_false_single() {
        let ty = TsType::Named("MutationResult".into());
        assert!(!is_binary_mutation_return(&ty));
    }

    #[test]
    fn is_binary_mutation_return_false_three_elements() {
        let ty = TsType::Tuple(vec![
            TsType::Uint8Array,
            TsType::Named("MutationResult".into()),
            TsType::Number,
        ]);
        assert!(!is_binary_mutation_return(&ty));
    }

    fn make_bridge_test_api() -> TsApi {
        TsApi {
            services: vec![TsService {
                rust_name: "ComputeEngine".into(),
                key: Some(ServiceKey {
                    param_name: "doc_id".into(),
                }),
                fn_prefix: Some("compute".into()),
                methods: vec![
                    // LifecycleCreate → Skip
                    TsMethod {
                        rust_name: "new".into(),
                        access: MethodAccess::LifecycleCreate,
                        params: vec![TsParam {
                            rust_name: "config".into(),
                            ts_type: TsType::Named("Config".into()),
                            is_parse: false,
                        }],
                        return_type: TsType::Void,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    // Write + binary tuple → Mutate
                    TsMethod {
                        rust_name: "set_cell".into(),
                        access: MethodAccess::Write,
                        params: vec![
                            TsParam {
                                rust_name: "sheet_id".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                            TsParam {
                                rust_name: "row".into(),
                                ts_type: TsType::Number,
                                is_parse: false,
                            },
                            TsParam {
                                rust_name: "input".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                        ],
                        return_type: TsType::Tuple(vec![
                            TsType::Uint8Array,
                            TsType::Named("MutationResult".into()),
                        ]),
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    // Write with binary tuple → Mutate (all write methods now return tuples)
                    TsMethod {
                        rust_name: "rename_sheet".into(),
                        access: MethodAccess::Write,
                        params: vec![TsParam {
                            rust_name: "name".into(),
                            ts_type: TsType::String,
                            is_parse: false,
                        }],
                        return_type: TsType::Tuple(vec![
                            TsType::Uint8Array,
                            TsType::Named("MutationResult".into()),
                        ]),
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    // Read → Query
                    TsMethod {
                        rust_name: "get_workbook_settings".into(),
                        access: MethodAccess::Read,
                        params: vec![],
                        return_type: TsType::Named("WorkbookSettings".into()),
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                    // Pure → direct transport.call, no docId
                    TsMethod {
                        rust_name: "schema_validate".into(),
                        access: MethodAccess::Pure,
                        params: vec![
                            TsParam {
                                rust_name: "value".into(),
                                ts_type: TsType::String,
                                is_parse: false,
                            },
                            TsParam {
                                rust_name: "schema".into(),
                                ts_type: TsType::Named("SchemaType".into()),
                                is_parse: false,
                            },
                        ],
                        return_type: TsType::Boolean,
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                    // skip(ts_bridge) → Skip
                    TsMethod {
                        rust_name: "internal_only".into(),
                        access: MethodAccess::Read,
                        params: vec![],
                        return_type: TsType::String,
                        is_fallible: false,
                        skip_platforms: vec!["ts_bridge".into()],
                    },
                ],
            }],
        }
    }

    #[test]
    fn emit_bridge_header() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        assert!(ts.contains("// Auto-generated by bridge-ts. Do not edit."));
        assert!(ts.contains("import type { BridgeTransport } from '@rust-bridge/client';"));
        assert!(ts.contains("import type { ComputeCore } from './compute-core';"));
    }

    #[test]
    fn emit_bridge_interface_present() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        assert!(ts.contains("export interface GeneratedBridgeMethods {"));
    }

    #[test]
    fn emit_bridge_factory_present() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        assert!(
            ts.contains("export class GeneratedBridgeBase implements GeneratedBridgeMethods {")
        );
        assert!(ts.contains("readonly core: ComputeCore;"));
        assert!(ts.contains("constructor(core: ComputeCore)"));
    }

    #[test]
    fn emit_bridge_skips_lifecycle() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // LifecycleCreate "new" should not appear
        assert!(!ts.contains("new(config"));
        assert!(!ts.contains("compute_new"));
    }

    #[test]
    fn emit_bridge_skips_ts_bridge_platform() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        assert!(!ts.contains("internalOnly"));
        assert!(!ts.contains("compute_internal_only"));
    }

    #[test]
    fn emit_bridge_mutate_method() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // Interface: return type should be unwrapped to MutationResult
        assert!(ts.contains(
            "setCell(sheetId: string, row: number, input: string): Promise<MutationResult>;"
        ));
        // Class: should use this.core.mutate() and inject docId
        assert!(ts.contains("this.core.mutate(this.core.transport.call<[Uint8Array, MutationResult]>('compute_set_cell', { docId: this.core.docId, sheetId, row, input }))"));
    }

    #[test]
    fn emit_bridge_rename_sheet_uses_mutate() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // Interface: return type should be unwrapped to MutationResult
        assert!(ts.contains("renameSheet(name: string): Promise<MutationResult>;"));
        // Class: should use this.core.mutate() (all write methods use mutate now)
        assert!(ts.contains("this.core.mutate(this.core.transport.call<[Uint8Array, MutationResult]>('compute_rename_sheet', { docId: this.core.docId, name }))"));
    }

    #[test]
    fn emit_bridge_query_method() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // Interface
        assert!(ts.contains("getWorkbookSettings(): Promise<WorkbookSettings>;"));
        // Class: should use this.core.query()
        assert!(ts.contains("this.core.query(this.core.transport.call<WorkbookSettings>('compute_get_workbook_settings', { docId: this.core.docId }))"));
    }

    #[test]
    fn emit_bridge_pure_method() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // Interface
        assert!(
            ts.contains("schemaValidate(value: string, schema: SchemaType): Promise<boolean>;")
        );
        // Class: bare this.core.transport.call with type param, no docId
        assert!(ts.contains("schemaValidate(value: string, schema: SchemaType): Promise<boolean>"));
        assert!(ts.contains(
            "this.core.transport.call<boolean>('compute_schema_validate', { value, schema })"
        ));
        // Should NOT have this.core.query or this.core.mutate for pure
        assert!(!ts.contains(
            "this.core.query(this.core.transport.call<boolean>('compute_schema_validate'"
        ));
        assert!(!ts.contains(
            "this.core.mutate(this.core.transport.call<boolean>('compute_schema_validate'"
        ));
    }

    #[test]
    fn emit_bridge_no_key_param_in_signatures() {
        let api = make_bridge_test_api();
        let ts = emit_bridge(&api, None, None);
        // Interface/factory methods should NOT have docId as a parameter
        assert!(!ts.contains("setCell(docId"));
        assert!(!ts.contains("getWorkbookSettings(docId"));
    }

    #[test]
    fn emit_bridge_with_imports() {
        let api = make_bridge_test_api();
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./types".into(),
                types: vec![
                    TypeImport {
                        local_name: "MutationResult".into(),
                        imported_name: None,
                    },
                    TypeImport {
                        local_name: "WorkbookSettings".into(),
                        imported_name: None,
                    },
                    TypeImport {
                        local_name: "SchemaType".into(),
                        imported_name: None,
                    },
                ],
            }],
        };
        let ts = emit_bridge(&api, Some(&config), None);
        assert!(ts.contains(
            "import type { MutationResult, WorkbookSettings, SchemaType } from './types';"
        ));
    }

    #[test]
    fn emit_bridge_custom_config() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "MyEngine".into(),
                key: None,
                fn_prefix: None,
                methods: vec![TsMethod {
                    rust_name: "ping".into(),
                    access: MethodAccess::Pure,
                    params: vec![],
                    return_type: TsType::String,
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let config = BridgeConfig {
            core_import_path: "./my-core".into(),
            core_type_name: "MyCore".into(),
            interface_name: "MyBridgeMethods".into(),
            class_name: "MyBridgeBase".into(),
        };
        let ts = emit_bridge(&api, None, Some(&config));
        assert!(ts.contains("import type { MyCore } from './my-core';"));
        assert!(ts.contains("export interface MyBridgeMethods {"));
        assert!(ts.contains("export class MyBridgeBase implements MyBridgeMethods {"));
    }

    #[test]
    fn emit_bridge_stateless_pure_no_key_injection() {
        // Stateless service (no key) — pure methods should not try to inject any key
        let api = TsApi {
            services: vec![TsService {
                rust_name: "Utils".into(),
                key: None,
                fn_prefix: Some("utils".into()),
                methods: vec![TsMethod {
                    rust_name: "hash".into(),
                    access: MethodAccess::Pure,
                    params: vec![TsParam {
                        rust_name: "input".into(),
                        ts_type: TsType::String,
                        is_parse: false,
                    }],
                    return_type: TsType::Number,
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let ts = emit_bridge(&api, None, None);
        assert!(ts.contains("transport.call<number>('utils_hash', { input })"));
        assert!(!ts.contains("core.docId"));
    }

    #[test]
    fn emit_bridge_imports_skip_lifecycle_types() {
        // Config type is only used by lifecycle create method — should not be imported
        let api = TsApi {
            services: vec![TsService {
                rust_name: "Engine".into(),
                key: Some(ServiceKey {
                    param_name: "doc_id".into(),
                }),
                fn_prefix: Some("engine".into()),
                methods: vec![
                    TsMethod {
                        rust_name: "new".into(),
                        access: MethodAccess::LifecycleCreate,
                        params: vec![TsParam {
                            rust_name: "config".into(),
                            ts_type: TsType::Named("EngineConfig".into()),
                            is_parse: false,
                        }],
                        return_type: TsType::Void,
                        is_fallible: true,
                        skip_platforms: vec![],
                    },
                    TsMethod {
                        rust_name: "get_status".into(),
                        access: MethodAccess::Read,
                        params: vec![],
                        return_type: TsType::Named("Status".into()),
                        is_fallible: false,
                        skip_platforms: vec![],
                    },
                ],
            }],
        };
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./types".into(),
                types: vec![
                    TypeImport {
                        local_name: "EngineConfig".into(),
                        imported_name: None,
                    },
                    TypeImport {
                        local_name: "Status".into(),
                        imported_name: None,
                    },
                ],
            }],
        };
        let ts = emit_bridge(&api, Some(&config), None);
        // Only Status should be imported, not EngineConfig
        assert!(ts.contains("import type { Status } from './types';"));
        assert!(!ts.contains("EngineConfig"));
    }

    #[test]
    fn emit_bridge_mutation_result_unwrap() {
        let api = TsApi {
            services: vec![TsService {
                rust_name: "Engine".into(),
                key: Some(ServiceKey {
                    param_name: "doc_id".into(),
                }),
                fn_prefix: Some("engine".into()),
                methods: vec![TsMethod {
                    rust_name: "delete_rows".into(),
                    access: MethodAccess::Write,
                    params: vec![],
                    return_type: TsType::Tuple(vec![
                        TsType::Uint8Array,
                        TsType::Named("MutationResult".into()),
                    ]),
                    is_fallible: false,
                    skip_platforms: vec![],
                }],
            }],
        };
        let config = ImportConfig {
            groups: vec![ImportGroup {
                from: "./types".into(),
                types: vec![TypeImport {
                    local_name: "MutationResult".into(),
                    imported_name: None,
                }],
            }],
        };
        let ts = emit_bridge(&api, Some(&config), None);
        // Interface should show unwrapped type
        assert!(ts.contains("deleteRows(): Promise<MutationResult>;"));
        // Class should use this.core.mutate() with wire type
        assert!(ts.contains("this.core.mutate(this.core.transport.call<[Uint8Array, MutationResult]>('engine_delete_rows'"), "got: {}", ts);
    }

    #[test]
    fn factory_method_pure_has_typed_params_and_return() {
        let svc = TsService {
            rust_name: "BridgePure".into(),
            fn_prefix: Some("".into()),
            key: None,
            methods: vec![],
        };
        let method = TsMethod {
            rust_name: "validate".into(),
            access: MethodAccess::Pure,
            params: vec![TsParam {
                rust_name: "input".into(),
                ts_type: TsType::String,
                is_parse: false,
            }],
            return_type: TsType::Boolean,
            is_fallible: false,
            skip_platforms: vec![],
        };
        let output = emit_bridge_class_method(&svc, &method, "", BridgePattern::Pure);
        assert!(
            output.contains("input: string"),
            "should have typed param, got: {}",
            output
        );
        assert!(
            output.contains("): Promise<boolean>"),
            "should have return type, got: {}",
            output
        );
        assert!(
            output.contains("this.core.transport.call<boolean>"),
            "should have <T> on call, got: {}",
            output
        );
    }

    #[test]
    fn factory_method_mutate_has_wire_type_on_call() {
        let svc = TsService {
            rust_name: "ComputeEngine".into(),
            fn_prefix: Some("compute".into()),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            methods: vec![],
        };
        let method = TsMethod {
            rust_name: "set_cell".into(),
            access: MethodAccess::Write,
            params: vec![
                TsParam {
                    rust_name: "sheet_id".into(),
                    ts_type: TsType::Named("SheetId".into()),
                    is_parse: false,
                },
                TsParam {
                    rust_name: "input".into(),
                    ts_type: TsType::String,
                    is_parse: false,
                },
            ],
            return_type: TsType::Tuple(vec![
                TsType::Uint8Array,
                TsType::Named("MutationResult".into()),
            ]),
            is_fallible: false,
            skip_platforms: vec![],
        };
        let output = emit_bridge_class_method(&svc, &method, "compute", BridgePattern::Mutate);
        // Params should be typed
        assert!(
            output.contains("sheetId: SheetId"),
            "should have typed param, got: {}",
            output
        );
        assert!(
            output.contains("input: string"),
            "should have typed param, got: {}",
            output
        );
        // Return type should be unwrapped (MutationResult, not the tuple)
        assert!(
            output.contains("): Promise<MutationResult>"),
            "should have unwrapped return type, got: {}",
            output
        );
        // transport.call<T> should use the RAW wire type (full tuple)
        assert!(
            output.contains("this.core.transport.call<[Uint8Array, MutationResult]>"),
            "should have wire type on call, got: {}",
            output
        );
    }

    #[test]
    fn factory_method_query_has_typed_output() {
        let svc = TsService {
            rust_name: "ComputeEngine".into(),
            fn_prefix: Some("compute".into()),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            methods: vec![],
        };
        let method = TsMethod {
            rust_name: "get_settings".into(),
            access: MethodAccess::Read,
            params: vec![],
            return_type: TsType::Named("Settings".into()),
            is_fallible: false,
            skip_platforms: vec![],
        };
        let output = emit_bridge_class_method(&svc, &method, "compute", BridgePattern::Query);
        assert!(
            output.contains("): Promise<Settings>"),
            "should have return type, got: {}",
            output
        );
        assert!(
            output.contains("this.core.transport.call<Settings>"),
            "should have <T> on call, got: {}",
            output
        );
        assert!(
            output.contains("this.core.query("),
            "should use this.core.query wrapper, got: {}",
            output
        );
    }

    #[test]
    fn emit_type_defs_includes_type_alias() {
        let defs = vec![
            TsTypeDef::TypeAlias {
                name: "SheetId".into(),
                target: TsType::String,
            },
            TsTypeDef::Interface(TsInterface {
                name: "Foo".into(),
                fields: vec![TsField {
                    ts_name: "sheet".into(),
                    ts_type: TsType::Named("SheetId".into()),
                    optional: false,
                }],
            }),
        ];
        let ts = emit_type_defs(&defs, None);
        // SheetId is defined in defs, so it should NOT appear as external
        assert!(!ts.contains("// External types:"));
        assert!(ts.contains("export type SheetId = string;"));
        assert!(ts.contains("export interface Foo {"));
    }
}
