mod emit_support;

use bridge_ts::emit::*;
use bridge_ts::types::*;
use emit_support::make_bridge_test_api;

#[test]
fn emit_bridge_header() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    assert!(ts.contains("// Auto-generated by bridge-ts. Do not edit."));
    assert!(ts.contains("import type { BridgeTransport } from '@rust-bridge/client';"));
    assert!(ts.contains("import type { ComputeCore } from './compute-core';"));
    assert!(ts.contains("import type { MutationAdmissionOptions } from './mutation-admission';"));
}

#[test]
fn emit_bridge_interface_present() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    assert!(ts.contains("export interface GeneratedBridgeMethods {"));
}

#[test]
fn emit_bridge_factory_present() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    assert!(ts.contains("export class GeneratedBridgeBase implements GeneratedBridgeMethods {"));
    assert!(ts.contains("readonly core: ComputeCore;"));
    assert!(ts.contains("constructor(core: ComputeCore)"));
}

#[test]
fn emit_bridge_skips_lifecycle() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // LifecycleCreate "new" should not appear
    assert!(!ts.contains("new(config"));
    assert!(!ts.contains("compute_new"));
}

#[test]
fn emit_bridge_skips_ts_bridge_platform() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    assert!(!ts.contains("internalOnly"));
    assert!(!ts.contains("compute_internal_only"));
}

#[test]
fn emit_bridge_mutate_method() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // Interface: return type should be unwrapped to MutationResult
    assert!(ts.contains(
        "setCell(sheetId: string, row: number, input: string, admissionOptions?: MutationAdmissionOptions): Promise<MutationResult>;"
    ));
    // Class: should use public mutation admission and inject docId
    assert!(ts.contains("this.core.mutatePublic('compute_set_cell', () => this.core.transport.call<[Uint8Array, MutationResult]>('compute_set_cell', { docId: this.core.docId, sheetId, row, input }), undefined, admissionOptions)"));
}

#[test]
fn emit_bridge_rename_sheet_uses_mutate() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // Interface: return type should be unwrapped to MutationResult
    assert!(ts.contains(
        "renameSheet(name: string, admissionOptions?: MutationAdmissionOptions): Promise<MutationResult>;"
    ));
    // Class: should use public mutation admission
    assert!(ts.contains("this.core.mutatePublic('compute_rename_sheet', () => this.core.transport.call<[Uint8Array, MutationResult]>('compute_rename_sheet', { docId: this.core.docId, name }), undefined, admissionOptions)"));
}

#[test]
fn emit_bridge_query_method() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // Interface
    assert!(ts.contains("getWorkbookSettings(): Promise<WorkbookSettings>;"));
    // Class: should use this.core.query()
    assert!(ts.contains("this.core.query(this.core.transport.call<WorkbookSettings>('compute_get_workbook_settings', { docId: this.core.docId }))"));
}

#[test]
fn emit_bridge_pure_method() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // Interface
    assert!(ts.contains("schemaValidate(value: string, schema: SchemaType): Promise<boolean>;"));
    // Class: bare this.core.transport.call with type param, no docId
    assert!(ts.contains("schemaValidate(value: string, schema: SchemaType): Promise<boolean>"));
    assert!(ts.contains(
        "this.core.transport.call<boolean>('compute_schema_validate', { value, schema })"
    ));
    // Should NOT have this.core.query or this.core.mutate for pure
    assert!(
        !ts.contains("this.core.query(this.core.transport.call<boolean>('compute_schema_validate'")
    );
    assert!(!ts.contains("this.core.mutatePublic('compute_schema_validate'"));
}

#[test]
fn emit_bridge_no_key_param_in_signatures() {
    let api = make_bridge_test_api();
    let ts = emit_bridge(&api, None, None);
    // Interface/factory methods should NOT have docId as a parameter
    assert!(!ts.contains("setCell(docId"));
    assert!(!ts.contains("getWorkbookSettings(docId"));
}

#[test]
fn emit_bridge_with_imports() {
    let api = make_bridge_test_api();
    let config = ImportConfig {
        groups: vec![ImportGroup {
            from: "./types".into(),
            types: vec![
                TypeImport {
                    local_name: "MutationResult".into(),
                    imported_name: None,
                },
                TypeImport {
                    local_name: "WorkbookSettings".into(),
                    imported_name: None,
                },
                TypeImport {
                    local_name: "SchemaType".into(),
                    imported_name: None,
                },
            ],
        }],
    };
    let ts = emit_bridge(&api, Some(&config), None);
    assert!(
        ts.contains("import type { MutationResult, WorkbookSettings, SchemaType } from './types';")
    );
}

#[test]
fn emit_bridge_custom_config() {
    let api = TsApi {
        services: vec![TsService {
            rust_name: "MyEngine".into(),
            key: None,
            fn_prefix: None,
            methods: vec![TsMethod {
                rust_name: "ping".into(),
                access: MethodAccess::Pure,
                params: vec![],
                return_type: TsType::String,
                is_fallible: false,
                skip_platforms: vec![],
            }],
        }],
    };
    let config = BridgeConfig {
        core_import_path: "./my-core".into(),
        core_type_name: "MyCore".into(),
        interface_name: "MyBridgeMethods".into(),
        class_name: "MyBridgeBase".into(),
    };
    let ts = emit_bridge(&api, None, Some(&config));
    assert!(ts.contains("import type { MyCore } from './my-core';"));
    assert!(ts.contains("export interface MyBridgeMethods {"));
    assert!(ts.contains("export class MyBridgeBase implements MyBridgeMethods {"));
}

#[test]
fn emit_bridge_stateless_pure_no_key_injection() {
    // Stateless service (no key) — pure methods should not try to inject any key
    let api = TsApi {
        services: vec![TsService {
            rust_name: "Utils".into(),
            key: None,
            fn_prefix: Some("utils".into()),
            methods: vec![TsMethod {
                rust_name: "hash".into(),
                access: MethodAccess::Pure,
                params: vec![TsParam {
                    rust_name: "input".into(),
                    ts_type: TsType::String,
                    is_parse: false,
                }],
                return_type: TsType::Number,
                is_fallible: false,
                skip_platforms: vec![],
            }],
        }],
    };
    let ts = emit_bridge(&api, None, None);
    assert!(ts.contains("transport.call<number>('utils_hash', { input })"));
    assert!(!ts.contains("core.docId"));
}

#[test]
fn emit_bridge_imports_skip_lifecycle_types() {
    // Config type is only used by lifecycle create method — should not be imported
    let api = TsApi {
        services: vec![TsService {
            rust_name: "Engine".into(),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            fn_prefix: Some("engine".into()),
            methods: vec![
                TsMethod {
                    rust_name: "new".into(),
                    access: MethodAccess::LifecycleCreate,
                    params: vec![TsParam {
                        rust_name: "config".into(),
                        ts_type: TsType::Named("EngineConfig".into()),
                        is_parse: false,
                    }],
                    return_type: TsType::Void,
                    is_fallible: true,
                    skip_platforms: vec![],
                },
                TsMethod {
                    rust_name: "get_status".into(),
                    access: MethodAccess::Read,
                    params: vec![],
                    return_type: TsType::Named("Status".into()),
                    is_fallible: false,
                    skip_platforms: vec![],
                },
            ],
        }],
    };
    let config = ImportConfig {
        groups: vec![ImportGroup {
            from: "./types".into(),
            types: vec![
                TypeImport {
                    local_name: "EngineConfig".into(),
                    imported_name: None,
                },
                TypeImport {
                    local_name: "Status".into(),
                    imported_name: None,
                },
            ],
        }],
    };
    let ts = emit_bridge(&api, Some(&config), None);
    // Only Status should be imported, not EngineConfig
    assert!(ts.contains("import type { Status } from './types';"));
    assert!(!ts.contains("EngineConfig"));
}

#[test]
fn emit_bridge_mutation_result_unwrap() {
    let api = TsApi {
        services: vec![TsService {
            rust_name: "Engine".into(),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            fn_prefix: Some("engine".into()),
            methods: vec![TsMethod {
                rust_name: "delete_rows".into(),
                access: MethodAccess::Write,
                params: vec![],
                return_type: TsType::Tuple(vec![
                    TsType::Uint8Array,
                    TsType::Named("MutationResult".into()),
                ]),
                is_fallible: false,
                skip_platforms: vec![],
            }],
        }],
    };
    let config = ImportConfig {
        groups: vec![ImportGroup {
            from: "./types".into(),
            types: vec![TypeImport {
                local_name: "MutationResult".into(),
                imported_name: None,
            }],
        }],
    };
    let ts = emit_bridge(&api, Some(&config), None);
    // Interface should show unwrapped type
    assert!(ts.contains(
        "deleteRows(admissionOptions?: MutationAdmissionOptions): Promise<MutationResult>;"
    ));
    // Class should use public mutation admission with wire type
    assert!(ts.contains("this.core.mutatePublic('engine_delete_rows', () => this.core.transport.call<[Uint8Array, MutationResult]>('engine_delete_rows', { docId: this.core.docId }), undefined, admissionOptions)"), "got: {}", ts);
}

#[test]
fn emit_bridge_system_mutation_method() {
    let api = TsApi {
        services: vec![TsService {
            rust_name: "ComputeEngine".into(),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            fn_prefix: Some("compute".into()),
            methods: vec![TsMethod {
                rust_name: "complete_deferred_hydration".into(),
                access: MethodAccess::Write,
                params: vec![],
                return_type: TsType::Tuple(vec![
                    TsType::Uint8Array,
                    TsType::Named("MutationResult".into()),
                ]),
                is_fallible: true,
                skip_platforms: vec![],
            }],
        }],
    };
    let ts = emit_bridge(&api, None, None);

    assert!(ts.contains(
        "completeDeferredHydration(admissionOptions?: MutationAdmissionOptions): Promise<MutationResult>;"
    ));
    assert!(ts.contains("this.core.mutateSystem('compute_complete_deferred_hydration', () => this.core.transport.call<[Uint8Array, MutationResult]>('compute_complete_deferred_hydration', { docId: this.core.docId }), undefined, admissionOptions)"));
    assert!(!ts.contains("mutatePublic('compute_complete_deferred_hydration'"));
}

#[test]
fn emit_bridge_sync_apply_metadata_uses_system_mutation_unwrap() {
    let api = TsApi {
        services: vec![TsService {
            rust_name: "YrsComputeEngine".into(),
            key: Some(ServiceKey {
                param_name: "doc_id".into(),
            }),
            fn_prefix: Some("compute".into()),
            methods: vec![TsMethod {
                rust_name: "apply_sync_update".into(),
                access: MethodAccess::Write,
                params: vec![
                    TsParam {
                        rust_name: "update".into(),
                        ts_type: TsType::Uint8Array,
                        is_parse: false,
                    },
                    TsParam {
                        rust_name: "sync_context".into(),
                        ts_type: TsType::Named("SyncApplyOperationContextWire".into()),
                        is_parse: true,
                    },
                ],
                return_type: TsType::Tuple(vec![
                    TsType::Uint8Array,
                    TsType::Named("SyncApplyMutationMetadataWire".into()),
                ]),
                is_fallible: true,
                skip_platforms: vec![],
            }],
        }],
    };
    let config = ImportConfig {
        groups: vec![ImportGroup {
            from: "./types".into(),
            types: vec![
                TypeImport {
                    local_name: "MutationResult".into(),
                    imported_name: None,
                },
                TypeImport {
                    local_name: "SyncApplyMutationMetadataWire".into(),
                    imported_name: None,
                },
                TypeImport {
                    local_name: "SyncApplyOperationContextWire".into(),
                    imported_name: None,
                },
            ],
        }],
    };
    let ts = emit_bridge(&api, Some(&config), None);

    assert!(ts.contains(
        "applySyncUpdate(update: Uint8Array, syncContext: SyncApplyOperationContextWire, admissionOptions?: MutationAdmissionOptions): Promise<MutationResult>;"
    ));
    assert!(ts.contains("this.core.mutateSystem('compute_apply_sync_update', async () => { const [viewportPatchesBinary, metadata] = await this.core.transport.call<[Uint8Array, SyncApplyMutationMetadataWire]>('compute_apply_sync_update', { docId: this.core.docId, update, syncContext }); return [viewportPatchesBinary, metadata.mutationResult] as [Uint8Array, MutationResult]; }, undefined, admissionOptions)"));
    assert!(!ts.contains("this.core.query(this.core.transport.call<[Uint8Array, SyncApplyMutationMetadataWire]>('compute_apply_sync_update'"));
}
