//! Integration test: generate TypeScript types from xlsx parser source files.
//!
//! Reads real Rust source files from xlsx/parser/src/ and generates TypeScript
//! interfaces. Also includes ooxml-types worksheet types that are re-exported
//! by the xlsx parser's common/range.rs.

use bridge_ts::{TypeGenConfig, generate_types_from_source};
use std::collections::{BTreeSet, HashMap};

fn xlsx_config() -> TypeGenConfig {
    let mut map = HashMap::new();
    // FiniteF64 is a newtype wrapper used in the xlsx parser
    map.insert("FiniteF64".to_string(), bridge_ts::types::TsType::Number);
    map.insert(
        "serde_json::Value".to_string(),
        bridge_ts::types::TsType::Named("unknown".into()),
    );
    // CellAnchor from ooxml-types (used by SlicerAnchor) — inline as object type
    // Fields: col (u32), col_off (Emu/i64), row (u32), row_off (Emu/i64)
    map.insert(
        "CellAnchor".to_string(),
        bridge_ts::types::TsType::Named(
            "{ col: number; colOff: number; row: number; rowOff: number }".into(),
        ),
    );
    TypeGenConfig {
        external_type_map: map,
        ..Default::default()
    }
}

fn read_xlsx_source(path_from_parser: &str) -> String {
    let path = format!(
        "{}/../../../file-io/xlsx/parser/src/{}",
        env!("CARGO_MANIFEST_DIR"),
        path_from_parser
    );
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e))
}

fn read_ooxml_source(path_from_types: &str) -> String {
    let path = format!(
        "{}/../../../file-io/ooxml/types/src/{}",
        env!("CARGO_MANIFEST_DIR"),
        path_from_types
    );
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e))
}

fn read_domain_source(path_from_domain: &str) -> String {
    let path = format!(
        "{}/../../../domain-types/src/domain/{}",
        env!("CARGO_MANIFEST_DIR"),
        path_from_domain
    );
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e))
}

fn read_xlsx_sources(paths_from_parser: &[&str]) -> String {
    paths_from_parser
        .iter()
        .map(|path| read_xlsx_source(path))
        .collect::<Vec<_>>()
        .join("\n")
}

fn xlsx_result_source_files() -> &'static [&'static str] {
    &[
        "output/results/cells.rs",
        "output/results/comments.rs",
        "output/results/controls.rs",
        "output/results/errors.rs",
        "output/results/metadata.rs",
        "output/results/ole.rs",
        "output/results/print.rs",
        "output/results/status.rs",
        "output/results/styles.rs",
        "output/results/tables.rs",
        "output/results/timings.rs",
        "output/results/views.rs",
        "output/results/workbook.rs",
    ]
}

fn extract_external_types(ts: &str) -> BTreeSet<String> {
    ts.lines()
        .find_map(|line| line.strip_prefix("// External types:"))
        .map(|external_types| {
            external_types
                .split_whitespace()
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn emit_external_types_shim(external_types: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by bridge-ts. Do not edit.\n");
    out.push_str(
        "// Ambient declarations for external types referenced by bridge-ts generated files.\n",
    );
    out.push_str("//\n");
    out.push_str("// These names are defined in Rust crates outside the source set used for\n");
    out.push_str("// xlsx-types.ts generation. The declarations keep @mog/bridge-ts usable as a\n");
    out.push_str(
        "// standalone composite TypeScript project until those sources are included or\n",
    );
    out.push_str("// explicit type imports are configured.\n\n");
    out.push_str("declare global {\n");
    for name in external_types {
        out.push_str(&format!("  type {} = unknown;\n", name));
    }
    out.push_str("}\n\n");
    out.push_str("export {};\n");
    out
}

fn extract_declared_external_types(dts: &str) -> BTreeSet<String> {
    dts.lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            let rest = trimmed.strip_prefix("type ")?;
            Some(rest.split_whitespace().next()?.to_string())
        })
        .collect()
}

// ─── XLSX results.rs ────────────────────────────────────────────────────────

#[test]
fn xlsx_results_generate() {
    let source = read_xlsx_sources(xlsx_result_source_files());
    let ts = generate_types_from_source(&source, &xlsx_config()).unwrap();

    // Should have many interfaces (all the output structs)
    assert!(
        ts.contains("export interface"),
        "should generate interfaces"
    );

    // ColWidth is referenced as a Named type (from range.rs re-export)
    // It should appear in the "External types" comment since it's referenced but not defined here
    assert!(
        ts.contains("ColWidth"),
        "ColWidth should be referenced as a Named type"
    );
}

// ─── Worksheet types (from ooxml-types, re-exported by xlsx parser) ─────────

#[test]
fn xlsx_worksheet_col_width_generated() {
    let source = read_ooxml_source("worksheet/column.rs");
    let ts = generate_types_from_source(&source, &xlsx_config()).unwrap();

    assert!(
        ts.contains("export interface ColWidth"),
        "ColWidth interface"
    );
    // ColWidth uses default serde (snake_case), so fields stay as-is
    assert!(
        ts.contains("custom_width"),
        "ColWidth.custom_width should be snake_case (no rename_all)"
    );
}

// ─── No parse errors ────────────────────────────────────────────────────────

#[test]
fn xlsx_files_parse_without_error() {
    let config = xlsx_config();
    for path in xlsx_result_source_files() {
        let source = read_xlsx_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }
    // Worksheet & slicer types from ooxml-types
    for path in &[
        "worksheet/column.rs",
        "worksheet/row.rs",
        "worksheet/merge.rs",
        "worksheet/pane.rs",
        "slicers.rs",
    ] {
        let source = read_ooxml_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }
    // Domain types used by xlsx parser
    for path in &["external_link.rs"] {
        let source = read_domain_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }
}

#[test]
fn generated_external_type_shim_matches_xlsx_header() {
    let generated_dir = format!("{}/generated", env!("CARGO_MANIFEST_DIR"));
    let xlsx_types = std::fs::read_to_string(format!("{}/xlsx-types.ts", generated_dir))
        .expect("generated/xlsx-types.ts should exist");
    let external_types = std::fs::read_to_string(format!("{}/external-types.d.ts", generated_dir))
        .expect("generated/external-types.d.ts should exist");

    let referenced = extract_external_types(&xlsx_types);
    let declared = extract_declared_external_types(&external_types);

    let missing: Vec<_> = referenced.difference(&declared).cloned().collect();
    assert!(
        missing.is_empty(),
        "generated/external-types.d.ts is missing ambient declarations for: {}",
        missing.join(", ")
    );
}

// ─── Combined output generation ─────────────────────────────────────────────

/// Reads xlsx parser source files and writes a combined xlsx-types.ts
/// to the generated/ directory.
///
/// Run: cargo test -p bridge-ts --test generate_xlsx_types -- generate_combined --nocapture
#[test]
fn generate_combined() {
    let xlsx_base = format!(
        "{}/../../../file-io/xlsx/parser/src",
        env!("CARGO_MANIFEST_DIR")
    );
    let ooxml_base = format!(
        "{}/../../../file-io/ooxml/types/src",
        env!("CARGO_MANIFEST_DIR")
    );
    let domain_base = format!(
        "{}/../../../domain-types/src/domain",
        env!("CARGO_MANIFEST_DIR")
    );
    let config = xlsx_config();

    let source_files = [
        // xlsx parser result types
        format!("{}/output/results/cells.rs", xlsx_base),
        format!("{}/output/results/comments.rs", xlsx_base),
        format!("{}/output/results/controls.rs", xlsx_base),
        format!("{}/output/results/errors.rs", xlsx_base),
        format!("{}/output/results/metadata.rs", xlsx_base),
        format!("{}/output/results/ole.rs", xlsx_base),
        format!("{}/output/results/print.rs", xlsx_base),
        format!("{}/output/results/status.rs", xlsx_base),
        format!("{}/output/results/styles.rs", xlsx_base),
        format!("{}/output/results/tables.rs", xlsx_base),
        format!("{}/output/results/timings.rs", xlsx_base),
        format!("{}/output/results/views.rs", xlsx_base),
        format!("{}/output/results/workbook.rs", xlsx_base),
        // Worksheet & slicer types from ooxml-types
        format!("{}/worksheet/column.rs", ooxml_base),
        format!("{}/worksheet/row.rs", ooxml_base),
        format!("{}/worksheet/merge.rs", ooxml_base),
        format!("{}/worksheet/pane.rs", ooxml_base),
        format!("{}/slicers.rs", ooxml_base),
        // Domain types used by xlsx parser
        format!("{}/external_link.rs", domain_base),
    ];

    let mut all_defs = Vec::new();
    for path in &source_files {
        let source = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
        let defs = bridge_ts::parse_types(&source, &config).unwrap();
        eprintln!("{}: {} types", path.rsplit('/').next().unwrap(), defs.len());
        all_defs.extend(defs);
    }

    let ts = bridge_ts::emit_type_defs(&all_defs, None);
    let external_types = extract_external_types(&ts);
    let external_types_shim = emit_external_types_shim(&external_types);
    eprintln!(
        "\nGenerated xlsx-types.ts: {} bytes, {} types",
        ts.len(),
        all_defs.len()
    );

    // Write to generated/ directory
    let output_dir = format!("{}/generated", env!("CARGO_MANIFEST_DIR"));
    std::fs::create_dir_all(&output_dir).unwrap();
    let output_path = format!("{}/xlsx-types.ts", output_dir);
    std::fs::write(&output_path, &ts).unwrap();
    eprintln!("Written to: {}", output_path);

    let external_types_path = format!("{}/external-types.d.ts", output_dir);
    std::fs::write(&external_types_path, external_types_shim).unwrap();
    eprintln!("Written to: {}", external_types_path);
}
