//! Integration test: generate TypeScript types from ooxml-types source files.
//!
//! Reads real Rust source files from file-io/ooxml/types/src/ and generates
//! TypeScript type definitions. The ooxml-types crate has sub-module directories
//! (drawings/, charts/) so we enumerate all .rs files within them.

use bridge_ts::types::{TsType, TsTypeDef};
use bridge_ts::{TypeGenConfig, emit_type_defs, generate_types_from_source};
use std::collections::HashMap;

fn ooxml_config() -> TypeGenConfig {
    let mut map = HashMap::new();
    // Emu is `pub type Emu = i64` — a measurement unit alias that maps to number in TS
    map.insert("Emu".to_string(), bridge_ts::types::TsType::Number);
    // GeomCoord is `pub type GeomCoord = String` — a coordinate value represented as a string formula
    map.insert("GeomCoord".to_string(), bridge_ts::types::TsType::String);
    // TitleText is `pub type TitleText = ChartText` — alias for ChartText
    map.insert(
        "TitleText".to_string(),
        bridge_ts::types::TsType::Named("ChartText".into()),
    );

    // ── Macro-generated newtypes from drawings/primitives.rs ─────────────
    // These are generated by ooxml_newtype_int! / ooxml_newtype_str! macros
    // and are invisible to the syn parser, so we register them manually.

    // Integer newtypes (ooxml_newtype_int!) → number
    for name in &[
        // Coordinate types
        "StCoordinate",
        "StCoordinateUnqualified",
        "StCoordinate32",
        "StCoordinate32Unqualified",
        "StPositiveCoordinate",
        "StPositiveCoordinate32",
        "StLineWidth",
        // Angle types
        "StAngle",
        "StFixedAngle",
        "StPositiveFixedAngle",
        "StFovAngle",
        // Percentage types
        "StPercentage",
        "StPercentageDecimal",
        "StFixedPercentage",
        "StFixedPercentageDecimal",
        "StPositivePercentage",
        "StPositivePercentageDecimal",
        "StPositiveFixedPercentage",
        "StPositiveFixedPercentageDecimal",
        // Text measurement types
        "StTextPoint",
        "StTextPointUnqualified",
        "StTextNonNegativePoint",
        "StTextFontSize",
        "StTextMargin",
        "StTextIndent",
        "StTextIndentLevelType",
        "StTextColumnCount",
        "StTextFontScalePercent",
        "StTextFontScalePercentOrPercentString",
        // Text spacing types
        "StTextSpacingPercent",
        "StTextSpacingPercentOrPercentString",
        "StTextSpacingPoint",
        // Bullet types
        "StTextBulletSize",
        "StTextBulletSizeDecimal",
        "StTextBulletSizePercent",
        "StTextBulletStartAtNum",
        // Identifier types
        "StDrawingElementId",
        "StStyleMatrixColumnIndex",
        "StPitchFamily",
    ] {
        map.insert(name.to_string(), bridge_ts::types::TsType::Number);
    }

    // String newtypes (ooxml_newtype_str!) → string
    for name in &[
        "StTextTypeface",
        "StGeomGuideName",
        "StGeomGuideFormula",
        "StAdjAngle",
        "StAdjCoordinate",
        "StShapeId",
    ] {
        map.insert(name.to_string(), bridge_ts::types::TsType::String);
    }

    TypeGenConfig {
        external_type_map: map,
        ..Default::default()
    }
}

fn read_ooxml_source(path_from_types: &str) -> String {
    let path = format!(
        "{}/../../../file-io/ooxml/types/src/{}",
        env!("CARGO_MANIFEST_DIR"),
        path_from_types
    );
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e))
}

fn read_ooxml_sources(paths_from_types: &[&str]) -> String {
    paths_from_types
        .iter()
        .map(|path| read_ooxml_source(path))
        .collect::<Vec<_>>()
        .join("\n")
}

fn drawings_text_source_files() -> &'static [&'static str] {
    &[
        "drawings/text/enums.rs",
        "drawings/text/extension.rs",
        "drawings/text/run_props.rs",
        "drawings/text/numbering.rs",
        "drawings/text/bullets.rs",
        "drawings/text/paragraph.rs",
        "drawings/text/body.rs",
    ]
}

fn drawings_color_source_files() -> &'static [&'static str] {
    &[
        "drawings/color/preset.rs",
        "drawings/color/scheme.rs",
        "drawings/color/system.rs",
        "drawings/color/transform.rs",
        "drawings/color/choice.rs",
    ]
}

fn charts_enum_source_files() -> &'static [&'static str] {
    &[
        "charts/enums/chart_kind.rs",
        "charts/enums/axis.rs",
        "charts/enums/display.rs",
        "charts/enums/layout.rs",
        "charts/enums/analysis.rs",
        "charts/enums/print.rs",
    ]
}

fn print_source_files() -> &'static [&'static str] {
    &[
        "print/enums.rs",
        "print/header_footer.rs",
        "print/margins.rs",
        "print/measure.rs",
        "print/options.rs",
        "print/page_breaks.rs",
        "print/paper.rs",
        "print/setup.rs",
    ]
}

fn theme_source_files() -> &'static [&'static str] {
    &[
        "themes/colors.rs",
        "themes/custom_colors.rs",
        "themes/fonts.rs",
        "themes/base.rs",
        "themes/format.rs",
        "themes/mapping.rs",
        "themes/object_defaults.rs",
        "themes/stylesheet.rs",
    ]
}

fn shape_preset_def() -> TsTypeDef {
    let source = read_ooxml_source("drawings/preset.rs");
    let variants = source
        .lines()
        .filter_map(|line| {
            let (_, token) = line.split_once("=>")?;
            let token = token.trim().trim_end_matches(',').trim();
            token
                .strip_prefix('"')?
                .strip_suffix('"')
                .map(str::to_string)
        })
        .collect();

    TsTypeDef::StringUnion(bridge_ts::types::TsStringUnion {
        name: "ShapePreset".to_string(),
        variants,
    })
}

// ─── OOXML drawings ─────────────────────────────────────────────────────────

#[test]
fn ooxml_drawings_generate() {
    let ts = emit_type_defs(&[shape_preset_def()], None);

    // Should generate a ShapePreset string union type
    assert!(
        ts.contains("ShapePreset"),
        "should generate ShapePreset type"
    );

    // Should be a string union (all-unit enum with serde rename)
    assert!(
        ts.contains("export type ShapePreset ="),
        "ShapePreset should be a string union type"
    );
}

#[test]
fn ooxml_drawings_shape_preset_has_expected_variants() {
    let ts = emit_type_defs(&[shape_preset_def()], None);

    // Verify some well-known shape preset values appear in the output
    assert!(ts.contains("\"rect\""), "should contain rect");
    assert!(ts.contains("\"ellipse\""), "should contain ellipse");
    assert!(ts.contains("\"diamond\""), "should contain diamond");
    assert!(ts.contains("\"textBox\""), "should contain textBox");
}

// ─── TextWarpPreset / GeomGuide / PresetTextWarp codegen ────────────────────

#[test]
fn ooxml_drawings_text_warp_preset_generated() {
    let source = read_ooxml_sources(drawings_text_source_files());
    let ts = generate_types_from_source(&source, &ooxml_config()).unwrap();

    assert!(
        ts.contains("TextWarpPreset"),
        "should generate TextWarpPreset type"
    );
    assert!(
        ts.contains("export type TextWarpPreset ="),
        "TextWarpPreset should be a string union type"
    );

    // Verify all 41 values
    let expected_values = [
        "textNoShape",
        "textPlain",
        "textStop",
        "textTriangle",
        "textTriangleInverted",
        "textChevron",
        "textChevronInverted",
        "textRingInside",
        "textRingOutside",
        "textArchUp",
        "textArchDown",
        "textCircle",
        "textButton",
        "textArchUpPour",
        "textArchDownPour",
        "textCirclePour",
        "textButtonPour",
        "textCurveUp",
        "textCurveDown",
        "textCanUp",
        "textCanDown",
        "textWave1",
        "textWave2",
        "textDoubleWave1",
        "textWave4",
        "textInflate",
        "textDeflate",
        "textInflateBottom",
        "textDeflateBottom",
        "textInflateTop",
        "textDeflateTop",
        "textDeflateInflate",
        "textDeflateInflateDeflate",
        "textFadeRight",
        "textFadeLeft",
        "textFadeUp",
        "textFadeDown",
        "textSlantUp",
        "textSlantDown",
        "textCascadeUp",
        "textCascadeDown",
    ];
    for val in &expected_values {
        assert!(
            ts.contains(&format!("\"{}\"", val)),
            "should contain {}",
            val
        );
    }
}

#[test]
fn ooxml_drawings_geom_guide_generated() {
    let source = read_ooxml_source("drawings/geometry.rs");
    let ts = generate_types_from_source(&source, &ooxml_config()).unwrap();

    assert!(
        ts.contains("GeomGuide"),
        "should generate GeomGuide interface"
    );
    assert!(
        ts.contains("name: string"),
        "GeomGuide should have name field"
    );
    assert!(
        ts.contains("fmla: string"),
        "GeomGuide should have fmla field"
    );
}

#[test]
fn ooxml_drawings_preset_text_warp_generated() {
    let source = read_ooxml_sources(drawings_text_source_files());
    let ts = generate_types_from_source(&source, &ooxml_config()).unwrap();

    assert!(
        ts.contains("PresetTextWarp"),
        "should generate PresetTextWarp interface"
    );
    assert!(
        ts.contains("preset: TextWarpPreset"),
        "PresetTextWarp should have preset field"
    );
    assert!(
        ts.contains("adjust_values: GeomGuide[]"),
        "PresetTextWarp should have adjust_values field"
    );
}

// ─── OOXML charts ────────────────────────────────────────────────────────────

#[test]
fn ooxml_charts_generate() {
    let source = read_ooxml_sources(charts_enum_source_files());
    let ts = generate_types_from_source(&source, &ooxml_config()).unwrap();

    // Should generate ChartType as a string union
    assert!(ts.contains("ChartType"), "should generate ChartType type");
}

#[test]
fn ooxml_charts_has_expected_enums() {
    let source = read_ooxml_sources(charts_enum_source_files());
    let ts = generate_types_from_source(&source, &ooxml_config()).unwrap();

    // Verify key chart enums are generated
    assert!(ts.contains("BarDirection"), "should generate BarDirection");
    assert!(ts.contains("Grouping"), "should generate Grouping");
    assert!(ts.contains("OfPieType"), "should generate OfPieType");
    assert!(ts.contains("SplitType"), "should generate SplitType");
    assert!(
        ts.contains("SizeRepresents"),
        "should generate SizeRepresents"
    );
    assert!(ts.contains("CrossBetween"), "should generate CrossBetween");
    assert!(ts.contains("BuiltInUnit"), "should generate BuiltInUnit");
    assert!(
        ts.contains("PictureFormat"),
        "should generate PictureFormat"
    );
}

// ─── No parse errors ────────────────────────────────────────────────────────

#[test]
fn ooxml_files_parse_without_error() {
    let config = ooxml_config();

    // All drawings sub-module files
    for path in &[
        "drawings/geometry.rs",
        "drawings/effects.rs",
        "drawings/fill.rs",
        "drawings/line.rs",
        "drawings/primitives.rs",
        "drawings/properties.rs",
        "drawings/spreadsheet.rs",
        "drawings/style.rs",
        "drawings/table.rs",
        "drawings/three_d.rs",
        "drawings/transform.rs",
    ] {
        let source = read_ooxml_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }
    for path in drawings_text_source_files()
        .iter()
        .chain(drawings_color_source_files())
    {
        let source = read_ooxml_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }

    // All charts sub-module files
    for path in [
        "charts/properties.rs",
        "charts/config.rs",
        "charts/data.rs",
        "charts/series.rs",
        "charts/axis.rs",
        "charts/document.rs",
        "charts/style.rs",
    ]
    .iter()
    .chain(charts_enum_source_files())
    {
        let source = read_ooxml_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }

    // Split top-level module files
    for path in print_source_files().iter().chain(theme_source_files()) {
        let source = read_ooxml_source(path);
        let result = generate_types_from_source(&source, &config);
        assert!(
            result.is_ok(),
            "Failed to parse {}: {}",
            path,
            result.unwrap_err()
        );
    }
}

// ─── Deduplication helpers ───────────────────────────────────────────────────

/// Recursively rename type references within a TsType.
fn rename_type_ref(ty: &mut TsType, from: &str, to: &str) {
    match ty {
        TsType::Named(name) if name == from => *name = to.to_string(),
        TsType::Array(inner) => rename_type_ref(inner, from, to),
        TsType::Nullable(inner) => rename_type_ref(inner, from, to),
        TsType::Record(k, v) => {
            rename_type_ref(k, from, to);
            rename_type_ref(v, from, to);
        }
        TsType::Tuple(elems) => {
            for e in elems {
                rename_type_ref(e, from, to);
            }
        }
        _ => {}
    }
}

/// Rename a type definition and all internal type references from `from` to `to`.
fn rename_type_in_def(def: &mut TsTypeDef, from: &str, to: &str) {
    match def {
        TsTypeDef::Interface(iface) => {
            if iface.name == from {
                iface.name = to.to_string();
            }
            for field in &mut iface.fields {
                rename_type_ref(&mut field.ts_type, from, to);
            }
        }
        TsTypeDef::StringUnion(su) => {
            if su.name == from {
                su.name = to.to_string();
            }
        }
        TsTypeDef::TaggedUnion(tu) => {
            if tu.name == from {
                tu.name = to.to_string();
            }
            for variant in &mut tu.variants {
                rename_type_ref(&mut variant.data_type, from, to);
            }
        }
        TsTypeDef::TypeAlias { name, target } => {
            if name == from {
                *name = to.to_string();
            }
            rename_type_ref(target, from, to);
        }
    }
}

/// Apply a set of renames to all defs in a slice.
fn apply_renames(defs: &mut [TsTypeDef], renames: &[(&str, &str)]) {
    for (from, to) in renames {
        for def in defs.iter_mut() {
            rename_type_in_def(def, from, to);
        }
    }
}

// ─── Combined output generation ─────────────────────────────────────────────

/// Reads ooxml-types source files and writes a combined ooxml-types.ts
/// to the generated/ directory.
///
/// Run: cargo test -p bridge-ts --test generate_ooxml_types -- generate_combined --nocapture
#[test]
fn generate_combined() {
    let base = format!(
        "{}/../../../file-io/ooxml/types/src",
        env!("CARGO_MANIFEST_DIR")
    );
    let config = ooxml_config();

    // Enumerate all source files from drawings/, charts/ sub-directories and
    // top-level modules. Exclude mod.rs (re-exports only) and tests.rs (no public types).
    let mut source_files = vec![
        // drawings sub-modules
        format!("{}/drawings/preset.rs", base),
        format!("{}/drawings/primitives.rs", base),
        format!("{}/drawings/fill.rs", base),
        format!("{}/drawings/line.rs", base),
        format!("{}/drawings/transform.rs", base),
        format!("{}/drawings/geometry.rs", base),
        format!("{}/drawings/properties.rs", base),
        format!("{}/drawings/style.rs", base),
        format!("{}/drawings/effects.rs", base),
        format!("{}/drawings/three_d.rs", base),
        format!("{}/drawings/table.rs", base),
        format!("{}/drawings/spreadsheet.rs", base),
        // charts sub-modules
        format!("{}/charts/properties.rs", base),
        format!("{}/charts/config.rs", base),
        format!("{}/charts/data.rs", base),
        format!("{}/charts/series.rs", base),
        format!("{}/charts/axis.rs", base),
        format!("{}/charts/document.rs", base),
        format!("{}/charts/style.rs", base),
    ];
    source_files.extend(
        drawings_color_source_files()
            .iter()
            .map(|path| format!("{base}/{path}")),
    );
    source_files.extend(
        drawings_text_source_files()
            .iter()
            .map(|path| format!("{base}/{path}")),
    );
    source_files.extend(
        charts_enum_source_files()
            .iter()
            .map(|path| format!("{base}/{path}")),
    );
    source_files.extend(
        print_source_files()
            .iter()
            .map(|path| format!("{base}/{path}")),
    );
    source_files.extend(
        theme_source_files()
            .iter()
            .map(|path| format!("{base}/{path}")),
    );

    // Per-file type renames to resolve duplicate identifiers across OOXML modules.
    // The drawings/ and charts/enums types are considered canonical; newly-added
    // source files (print.rs, charts/style.rs) get prefixed names.
    // Keys are path suffixes matched against each source file path.
    let per_file_renames: &[(&str, &[(&str, &str)])] = &[
        // print/ defines Orientation (Default/Portrait/Landscape) and PageSetup
        // which collide with charts/enums.rs Orientation (MinMax/MaxMin) and
        // charts/properties.rs PageSetup.
        ("print/enums.rs", &[("Orientation", "PrintOrientation")]),
        ("print/setup.rs", &[("PageSetup", "PrintPageSetup")]),
        // charts/style.rs defines ColorTransform (simple tuple variants) which
        // collides with drawings/color.rs ColorTransform (comprehensive tagged union).
        (
            "charts/style.rs",
            &[("ColorTransform", "ChartColorTransform")],
        ),
    ];

    let mut all_defs = Vec::new();
    all_defs.push(shape_preset_def());
    for path in &source_files {
        let source = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
        let mut defs = bridge_ts::parse_types(&source, &config).unwrap();
        let filename = path.rsplit('/').next().unwrap();
        eprintln!("{}: {} types", filename, defs.len());

        // Apply per-file renames to avoid duplicate identifiers
        for (suffix, renames) in per_file_renames {
            if path.ends_with(suffix) {
                apply_renames(&mut defs, renames);
            }
        }

        all_defs.extend(defs);
    }

    let ts = bridge_ts::emit_type_defs(&all_defs, None);
    eprintln!(
        "\nGenerated ooxml-types.ts: {} bytes, {} types",
        ts.len(),
        all_defs.len()
    );

    // Write to generated/ directory
    let output_dir = format!("{}/generated", env!("CARGO_MANIFEST_DIR"));
    std::fs::create_dir_all(&output_dir).unwrap();
    let output_path = format!("{}/ooxml-types.ts", output_dir);
    std::fs::write(&output_path, &ts).unwrap();
    eprintln!("Written to: {}", output_path);
}
