//! Classic TypeScript client emitter.

use crate::types::*;

use super::imports::render_configured_imports;
use super::names::{
    compute_effective_prefix, destroy_command_name, method_command_name, to_camel_case,
};
use super::refs::collect_named_from_api;

/// Generate TypeScript source for a complete API.
pub fn emit_api(api: &TsApi, imports: Option<&ImportConfig>) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by bridge-ts. Do not edit.\n\n");
    out.push_str("import type { BridgeTransport } from '@rust-bridge/client';\n");

    if let Some(config) = imports {
        let referenced = collect_named_from_api(api);
        out.push_str(&render_configured_imports(config, &referenced, "the API"));
        out.push('\n');
    } else {
        out.push('\n'); // preserve existing blank line after BridgeTransport import
    }

    for (i, svc) in api.services.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&emit_service(svc));
    }

    out
}

/// Generate TypeScript for a single service/module.
pub fn emit_service(svc: &TsService) -> String {
    let mut out = String::new();

    let client_name = format!("{}Client", &svc.rust_name);
    let factory_name = format!("create{}", &client_name);
    let effective_prefix = compute_effective_prefix(svc);

    // --- Client factory function ---
    out.push_str(&format!(
        "export function {}(transport: BridgeTransport) {{\n",
        factory_name
    ));
    out.push_str("  return {\n");

    for method in &svc.methods {
        out.push_str(&emit_factory_method(svc, method, &effective_prefix));
    }

    // Auto-generate destroy for stateful services
    if let Some(key) = &svc.key {
        let camel_key = to_camel_case(&key.param_name);
        let destroy_cmd = destroy_command_name(&effective_prefix);
        out.push_str(&format!(
            "    destroy({camel_key}: string): Promise<void> {{\n"
        ));
        out.push_str(&format!(
            "      return transport.call('{destroy_cmd}', {{ {camel_key} }});\n",
        ));
        out.push_str("    },\n");
    }

    out.push_str("  } as const;\n");
    out.push_str("}\n\n");

    // --- Client interface ---
    out.push_str(&format!("export interface {} {{\n", client_name));

    for method in &svc.methods {
        out.push_str(&emit_interface_method(svc, method));
    }

    if let Some(key) = &svc.key {
        let camel_key = to_camel_case(&key.param_name);
        out.push_str(&format!("  destroy({camel_key}: string): Promise<void>;\n"));
    }

    out.push_str("}\n");

    out
}

/// Emit one method inside the factory's return object.
fn emit_factory_method(svc: &TsService, method: &TsMethod, effective_prefix: &str) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let command_name = method_command_name(effective_prefix, &method.rust_name);
    let return_ts = method.return_type.to_ts_string();

    // Build parameter list
    let mut params = Vec::new();

    // Key param comes first for stateful services (except lifecycle create — key is generated)
    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        params.push(format!("{}: string", camel_key));
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        params.push(format!("{}: {}", camel_p, p.ts_type.to_ts_string()));
    }

    let params_str = params.join(", ");

    // Build args object for transport.call (camelCase keys to match Tauri 2 convention)
    let mut args = Vec::new();

    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        // TS variable is already camelCase, so shorthand { docId } gives camelCase key
        args.push(camel_key);
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        // TS variable is already camelCase, so shorthand { sheetId } gives camelCase key
        args.push(camel_p);
    }

    let args_str = if args.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", args.join(", "))
    };

    format!(
        "    {camel_name}({params_str}): Promise<{return_ts}> {{\n      return transport.call('{command_name}', {args_str});\n    }},\n"
    )
}

/// Emit one method signature in the interface.
fn emit_interface_method(svc: &TsService, method: &TsMethod) -> String {
    let camel_name = to_camel_case(&method.rust_name);
    let return_ts = method.return_type.to_ts_string();

    let mut params = Vec::new();

    if let Some(key) = &svc.key
        && method.access != MethodAccess::Pure
    {
        let camel_key = to_camel_case(&key.param_name);
        params.push(format!("{}: string", camel_key));
    }

    for p in &method.params {
        let camel_p = to_camel_case(&p.rust_name);
        params.push(format!("{}: {}", camel_p, p.ts_type.to_ts_string()));
    }

    let params_str = params.join(", ");

    format!("  {camel_name}({params_str}): Promise<{return_ts}>;\n")
}
