//! Command metadata emitter.

use crate::types::*;

use super::bridge::{BridgePattern, classify_bridge_pattern};
use super::names::{compute_effective_prefix, method_command_name};

/// Emit a `command-metadata.gen.ts` file with bytes-tuple, recalc, security,
/// and transport param metadata.
///
/// Iterates the parsed API and classifies each method:
/// - `BYTES_TUPLE_COMMANDS`: methods where `is_binary_mutation_return()` is true
/// - `RECALC_COMMANDS`: commands that trigger formula evaluation and need clock injection
/// - `BRIDGE_COMMAND_SECURITY_LEVELS`: security levels for bridge-generated commands
/// - `NAPI_SERDE_PARAM_INDICES`: param positions that the generated NAPI binding
///   receives as JSON strings because they are structured serde values.
pub fn emit_command_metadata(
    api: &TsApi,
    recalc_exclusions: &[&str],
    security_overrides: &[(&str, &str)],
) -> String {
    let mut bytes_tuple = Vec::new();
    let mut recalc = Vec::new();
    let mut napi_serde_params: Vec<(String, Vec<usize>)> = Vec::new();
    let recalc_exclude: std::collections::HashSet<&str> =
        recalc_exclusions.iter().copied().collect();
    let security_map: std::collections::HashMap<&str, &str> =
        security_overrides.iter().copied().collect();

    for svc in &api.services {
        let prefix = compute_effective_prefix(svc);

        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }

            let command_name = method_command_name(&prefix, &method.rust_name);

            let is_recalc_result = matches!(method.access, MethodAccess::Write)
                && matches!(&method.return_type, TsType::Named(name) if name == "RecalcResult");

            if pattern == BridgePattern::Mutate {
                bytes_tuple.push(command_name.clone());
            }
            if (pattern == BridgePattern::Mutate || is_recalc_result)
                && !recalc_exclude.contains(command_name.as_str())
            {
                recalc.push(command_name.clone());
            }

            let serde_indices: Vec<usize> = method
                .params
                .iter()
                .enumerate()
                .filter_map(|(idx, param)| {
                    if ts_param_needs_napi_json(param) {
                        Some(idx)
                    } else {
                        None
                    }
                })
                .collect();
            if !serde_indices.is_empty() {
                napi_serde_params.push((command_name, serde_indices));
            }
        }
    }

    bytes_tuple.sort();
    recalc.sort();
    napi_serde_params.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// DO NOT EDIT — generated by bridge-ts command metadata codegen.\n");
    out.push_str("// Regenerate: pnpm generate:bridge\n");
    out.push_str("//\n");
    out.push_str("// Source: #[bridge::api] annotations in compute-core and xlsx-api\n\n");

    // BYTES_TUPLE_COMMANDS
    out.push_str("/** Commands that return `[Uint8Array, MutationResult]` binary tuples. */\n");
    out.push_str("export const BYTES_TUPLE_COMMANDS = new Set([\n");
    for cmd in &bytes_tuple {
        out.push_str(&format!("  '{}',\n", cmd));
    }
    out.push_str("]);\n\n");

    // NAPI_SERDE_PARAM_INDICES
    out.push_str("/**\n");
    out.push_str(" * Positional params that must be JSON-stringified before calling NAPI.\n");
    out.push_str(" * NAPI generated wrappers receive structured serde params as strings,\n");
    out.push_str(" * while [bytes], [str], [parse], and primitive params are passed raw.\n");
    out.push_str(" */\n");
    out.push_str("export const NAPI_SERDE_PARAM_INDICES: Record<string, number[]> = {\n");
    for (cmd, indices) in &napi_serde_params {
        let rendered = indices
            .iter()
            .map(|idx| idx.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("  '{}': [{}],\n", cmd, rendered));
    }
    out.push_str("};\n\n");

    // RECALC_COMMANDS
    out.push_str(
        "/** Commands that trigger formula evaluation and therefore need clock injection. */\n",
    );
    out.push_str("export const RECALC_COMMANDS = new Set([\n");
    for cmd in &recalc {
        out.push_str(&format!("  '{}',\n", cmd));
    }
    out.push_str("]);\n\n");

    // BRIDGE_COMMAND_SECURITY_LEVELS
    out.push_str("/**\n");
    out.push_str(" * Security levels for bridge-generated commands.\n");
    out.push_str(
        " * Hand-written commands (credentials, file dialogs, etc.) are managed separately.\n",
    );
    out.push_str(" */\n");
    out.push_str("export const BRIDGE_COMMAND_SECURITY_LEVELS: Record<string, string> = {\n");
    let mut security_entries: Vec<(String, String)> = Vec::new();
    for svc in &api.services {
        let prefix = compute_effective_prefix(svc);
        let default_level = security_map
            .get(svc.rust_name.as_str())
            .unwrap_or(&"Public");

        for method in &svc.methods {
            let pattern = classify_bridge_pattern(method);
            if pattern == BridgePattern::Skip {
                continue;
            }
            let command_name = method_command_name(&prefix, &method.rust_name);
            security_entries.push((command_name, default_level.to_string()));
        }
    }
    security_entries.sort_by(|a, b| a.0.cmp(&b.0));
    for (cmd, level) in &security_entries {
        out.push_str(&format!("  '{}': '{}',\n", cmd, level));
    }
    out.push_str("};\n");

    out
}

fn ts_param_needs_napi_json(param: &TsParam) -> bool {
    if param.is_parse {
        return false;
    }
    match &param.ts_type {
        TsType::String | TsType::Number | TsType::Boolean | TsType::Uint8Array => false,
        TsType::Void => false,
        TsType::Nullable(_) | TsType::Array(_) | TsType::Tuple(_) | TsType::Named(_) => true,
        TsType::Record(_, _) => true,
    }
}
