//! Tauri handler registry emitter.

use crate::types::*;

use super::names::{compute_effective_prefix, destroy_command_name, method_command_name};

/// Configuration for Tauri handler registry generation.
pub struct HandlerRegistryConfig {
    /// Maps service `rust_name` → Rust module path relative to the crate root.
    /// e.g., `("ComputeService", "commands::compute")`.
    pub service_modules: Vec<(String, String)>,
    /// Additional hand-written command paths (e.g., `"commands::file::read_file"`).
    pub manual_commands: Vec<String>,
}

/// Collect Tauri command paths from a parsed bridge API.
///
/// For each non-skipped method, constructs `{module_path}::{prefix}_{method_name}`.
/// For stateful services, also adds the auto-generated `{prefix}_destroy` command.
pub fn collect_tauri_handler_names(api: &TsApi, config: &HandlerRegistryConfig) -> Vec<String> {
    let module_map: std::collections::HashMap<&str, &str> = config
        .service_modules
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();

    // Use BTreeSet for deterministic ordering and automatic deduplication.
    // Multiple services can map to the same module (e.g., YrsComputeEngine and
    // ComputeService both map to commands::compute), producing identical entries.
    let mut handlers = std::collections::BTreeSet::new();

    for svc in &api.services {
        let module_path = match module_map.get(svc.rust_name.as_str()) {
            Some(path) => *path,
            None => panic!(
                "No module mapping for service '{}'. Add it to HandlerRegistryConfig.service_modules.",
                svc.rust_name
            ),
        };

        let prefix = compute_effective_prefix(svc);

        for method in &svc.methods {
            // Skip methods not available in Tauri
            if method.skip_platforms.iter().any(|p| p == "tauri") {
                continue;
            }

            let command_name = method_command_name(&prefix, &method.rust_name);

            handlers.insert(format!("{}::{}", module_path, command_name));
        }

        // Auto-generated destroy for stateful services
        if svc.key.is_some() {
            let destroy_name = destroy_command_name(&prefix);
            handlers.insert(format!("{}::{}", module_path, destroy_name));
        }
    }

    // Add manual (hand-written) commands
    for cmd in &config.manual_commands {
        handlers.insert(cmd.clone());
    }

    handlers.into_iter().collect()
}

/// Emit a `tauri::generate_handler![...]` expression for inclusion via `include!()`.
///
/// The generated file is designed to be used as:
/// ```rust,ignore
/// .invoke_handler(include!("handlers.gen.rs"))
/// ```
pub fn emit_handler_registry(handlers: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// DO NOT EDIT — generated by bridge-ts handler registry codegen.\n");
    out.push_str("// Regenerate: pnpm generate:bridge\n");
    out.push_str("//\n");
    out.push_str("// This file is included by lib.rs via include!() and contains a single\n");
    out.push_str("// expression: the tauri::generate_handler![...] invocation.\n\n");
    out.push_str("tauri::generate_handler![\n");
    for handler in handlers {
        out.push_str(&format!("    {},\n", handler));
    }
    out.push_str("]\n");
    out
}
