use std::fmt;

/// Error returned when parsing a cell or range reference from a string fails.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsePosError {
    kind: ParsePosErrorKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ParsePosErrorKind {
    /// The input string was empty or missing required components.
    Empty,
    /// The column letters were invalid.
    InvalidColumn,
    /// The row number was invalid or out of range.
    InvalidRow,
    /// Range syntax was malformed (missing `:` separator, etc.).
    InvalidRange,
}

impl ParsePosError {
    /// Build an invalid range syntax error without exposing the private error kind.
    pub(super) fn invalid_range() -> Self {
        Self {
            kind: ParsePosErrorKind::InvalidRange,
        }
    }
}

impl fmt::Display for ParsePosError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.kind {
            ParsePosErrorKind::Empty => write!(f, "empty cell reference"),
            ParsePosErrorKind::InvalidColumn => write!(f, "invalid column letters"),
            ParsePosErrorKind::InvalidRow => write!(f, "invalid row number"),
            ParsePosErrorKind::InvalidRange => write!(f, "invalid range syntax"),
        }
    }
}

impl std::error::Error for ParsePosError {}

/// Parse a cell reference like "A1" into (col, row) zero-based indices.
///
/// Returns `Err` if the string is not a valid cell reference.
pub(super) fn parse_cell_ref(s: &str) -> Result<(u32, u32), ParsePosError> {
    if s.is_empty() {
        return Err(ParsePosError {
            kind: ParsePosErrorKind::Empty,
        });
    }
    // Find the boundary between letters and digits
    let digit_start = s.find(|c: char| c.is_ascii_digit()).ok_or(ParsePosError {
        kind: ParsePosErrorKind::InvalidRow,
    })?;
    if digit_start == 0 {
        return Err(ParsePosError {
            kind: ParsePosErrorKind::InvalidColumn,
        });
    }
    let col_part = &s[..digit_start];
    let row_part = &s[digit_start..];
    let col = letter_to_col(col_part).ok_or(ParsePosError {
        kind: ParsePosErrorKind::InvalidColumn,
    })?;
    let row_1based: u32 = row_part.parse().map_err(|_| ParsePosError {
        kind: ParsePosErrorKind::InvalidRow,
    })?;
    if row_1based == 0 {
        return Err(ParsePosError {
            kind: ParsePosErrorKind::InvalidRow,
        });
    }
    Ok((col, row_1based - 1))
}

/// Excel column limits.
pub const MAX_ROWS: u32 = 1_048_576;
/// Excel column limits.
pub const MAX_COLS: u32 = 16_384;

/// Convert a 0-based column index to Excel column letter(s).
/// 0 -> "A", 25 -> "Z", 26 -> "AA", etc.
///
/// Uses a stack-allocated buffer internally (column names are at most 3 chars
/// for valid Excel columns, or up to 7 chars for `u32::MAX`).
///
/// # Examples
///
/// ```
/// use cell_types::col_to_letter;
///
/// assert_eq!(col_to_letter(0), "A");
/// assert_eq!(col_to_letter(25), "Z");
/// assert_eq!(col_to_letter(26), "AA");
/// ```
#[must_use]
pub fn col_to_letter(col: u32) -> String {
    let mut s = String::with_capacity(3);
    col_to_letter_buf(col, &mut s);
    s
}

/// Write a 0-based column index as Excel column letter(s) into `buf`.
///
/// This avoids allocation when the caller already has a `String` to append to.
///
/// # Examples
///
/// ```
/// use cell_types::col_to_letter_buf;
///
/// let mut s = String::new();
/// col_to_letter_buf(0, &mut s);
/// assert_eq!(s, "A");
/// ```
///
/// # Panics
/// This function will not panic under normal usage. The internal `expect` call
/// guards a UTF-8 conversion that cannot fail because all generated bytes are
/// ASCII uppercase `A`-`Z`.
pub fn col_to_letter_buf(col: u32, buf: &mut String) {
    // Excel columns are at most 3 letters (XFD = 16383).
    // For arbitrary u32, 7 chars suffice (26^7 > u32::MAX).
    let mut tmp = [0u8; 7];
    let mut pos = tmp.len();
    let mut c = col;
    loop {
        pos -= 1;
        tmp[pos] = b'A' + (c % 26) as u8;
        if c < 26 {
            break;
        }
        c = c / 26 - 1;
    }
    // All bytes in tmp[pos..] are ASCII uppercase A-Z, so from_utf8 cannot fail.
    let s = std::str::from_utf8(&tmp[pos..]).expect("col_to_letter produced non-UTF8");
    buf.push_str(s);
}

/// Convert Excel column letter(s) to a 0-based column index.
/// "A" -> 0, "Z" -> 25, "AA" -> 26, etc.
///
/// # Examples
///
/// ```
/// use cell_types::letter_to_col;
///
/// assert_eq!(letter_to_col("A"), Some(0));
/// assert_eq!(letter_to_col("AA"), Some(26));
/// assert_eq!(letter_to_col(""), None);
/// assert_eq!(letter_to_col("1"), None);
/// ```
#[must_use]
pub fn letter_to_col(letters: &str) -> Option<u32> {
    if letters.is_empty() {
        return None;
    }
    let mut result: u32 = 0;
    for ch in letters.chars() {
        if !ch.is_ascii_alphabetic() {
            return None;
        }
        result = result
            .checked_mul(26)?
            .checked_add(ch.to_ascii_uppercase() as u32 - 'A' as u32 + 1)?;
    }
    result.checked_sub(1)
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn test_col_to_letter() {
        assert_eq!(col_to_letter(0), "A");
        assert_eq!(col_to_letter(25), "Z");
        assert_eq!(col_to_letter(26), "AA");
        assert_eq!(col_to_letter(701), "ZZ");
        assert_eq!(col_to_letter(702), "AAA");
    }

    #[test]
    fn test_letter_to_col() {
        assert_eq!(letter_to_col("A"), Some(0));
        assert_eq!(letter_to_col("Z"), Some(25));
        assert_eq!(letter_to_col("AA"), Some(26));
        assert_eq!(letter_to_col("ZZ"), Some(701));
        assert_eq!(letter_to_col("XFD"), Some(16383));
    }

    #[test]
    fn test_roundtrip() {
        for i in 0..=16383 {
            assert_eq!(letter_to_col(&col_to_letter(i)), Some(i));
        }
    }

    #[test]
    fn col_to_letter_zero() {
        assert_eq!(col_to_letter(0), "A");
    }

    #[test]
    fn col_to_letter_max_cols_minus_1() {
        assert_eq!(col_to_letter(MAX_COLS - 1), "XFD");
    }

    #[test]
    fn col_to_letter_buf_appends() {
        let mut s = String::from("col:");
        col_to_letter_buf(26, &mut s);
        assert_eq!(s, "col:AA");
    }

    #[test]
    fn letter_to_col_empty() {
        assert_eq!(letter_to_col(""), None);
    }

    #[test]
    fn letter_to_col_digits_rejected() {
        assert_eq!(letter_to_col("123"), None);
    }

    #[test]
    fn letter_to_col_mixed_rejected() {
        assert_eq!(letter_to_col("A1"), None);
    }

    #[test]
    fn letter_to_col_lowercase() {
        assert_eq!(letter_to_col("a"), Some(0));
        assert_eq!(letter_to_col("z"), Some(25));
        assert_eq!(letter_to_col("aa"), Some(26));
        assert_eq!(letter_to_col("xfd"), Some(16383));
    }

    #[test]
    fn max_constants() {
        assert_eq!(MAX_ROWS, 1_048_576);
        assert_eq!(MAX_COLS, 16_384);
    }

    #[test]
    fn parse_cell_ref_invalid_inputs() {
        assert_eq!(
            parse_cell_ref("").unwrap_err().to_string(),
            "empty cell reference"
        );
        assert_eq!(
            parse_cell_ref("123").unwrap_err().to_string(),
            "invalid column letters"
        );
        assert_eq!(
            parse_cell_ref("A").unwrap_err().to_string(),
            "invalid row number"
        );
        assert_eq!(
            parse_cell_ref("A0").unwrap_err().to_string(),
            "invalid row number"
        );
    }

    #[test]
    fn letter_to_col_overflow_returns_none() {
        // Very long column string that would overflow u32
        assert_eq!(letter_to_col("ZZZZZZZZZ"), None);
    }

    #[test]
    fn col_to_letter_large_value() {
        // Beyond Excel max but still valid conversion
        let s = col_to_letter(u32::MAX);
        assert!(!s.is_empty());
        // Roundtrip may not work due to overflow in letter_to_col
    }

    proptest! {
        /// col_to_letter -> letter_to_col roundtrip for all valid Excel columns.
        #[test]
        fn col_letter_roundtrip(col in 0u32..MAX_COLS) {
            let letters = col_to_letter(col);
            prop_assert_eq!(letter_to_col(&letters), Some(col));
        }

        /// letter_to_col -> col_to_letter roundtrip for valid inputs.
        #[test]
        fn letter_col_roundtrip(col in 0u32..MAX_COLS) {
            let letters = col_to_letter(col);
            let back = letter_to_col(&letters).unwrap();
            prop_assert_eq!(col_to_letter(back), letters);
        }
    }
}
